/**
 * Cytoscape schema graph (/graphview → Ontology tab).
 *
 * Generated from ontology/HeritageGraph.yaml — do not edit this file.
 * Run: `make ontology` or `python3 tools/gen_heritage_viz_config.py`
 */
export {
  CATEGORY_COLORS,
  getEdgesForNode,
  getNodeById,
  getNodesByCategory,
  getOntologyGraphData,
  getOntologyStats,
  type OntologyCategory,
  type OntologyEdge,
  type OntologyGraphData,
  type OntologyNode,
} from '@/lib/ontology/__generated__/ontology-graph';
