# Stage 1: Build the app
FROM node:20-alpine AS builder

WORKDIR /app

# Copy package files and install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy source code
COPY . .

# Build Next.js app
# RUN npm run build
RUN npm run build --no-lint

# Stage 2: Run the app
FROM node:20-alpine

WORKDIR /app

# Copy built app from builder
COPY --from=builder /app ./

# Expose port
EXPOSE 3000

# Start the app
CMD ["npm", "run", "start"]