version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: chlod-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=heritage_graph.settings.development
    # depends_on:
    #   - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: chlod-frontend
    ports:
      - "3000:80"  # serve React on http://localhost:3000

#   db:
#     image: postgres:15-alpine
#     container_name: chlod-db
#     environment:
#       POSTGRES_DB: heritage
#       POSTGRES_USER: admin
#       POSTGRES_PASSWORD: admin
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"

# volumes:
#   postgres_data:
