### Stage 1: Build React frontend
FROM node:lts-slim AS builder

# Set working directory
WORKDIR /app

# Copy dependency files
COPY package.json /app

# Install dependencies
RUN npm install

# Copy frontend source code
COPY heritage_graph_ui/ /app/heritage_graph_ui/

# Build the frontend
RUN npm run build

### Stage 2: Serve with Nginx
FROM nginx:1.27.4-alpine3.21-slim

# Copy custom Nginx config
COPY heritage_graph_ui/react_nginx.conf /etc/nginx/conf.d/default.conf

# Copy build output from builder
COPY --from=builder /app/heritage_graph_ui/build /usr/share/nginx/html
