# Generated by Django 5.2.8 on 2026-03-02 18:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heritage_data", "0002_userprofile_profile_image_organization_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Fork",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Why the user forked this contribution"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "forks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Reaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[("upvote", "Upvote"), ("downvote", "Downvote")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "reactions",
            },
        ),
        migrations.CreateModel(
            name="Share",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("twitter", "Twitter/X"),
                            ("facebook", "Facebook"),
                            ("linkedin", "LinkedIn"),
                            ("email", "Email"),
                            ("copy_link", "Copy Link"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "shares",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="comments",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="comments",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent comment for threaded replies",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="heritage_data.comments",
            ),
        ),
        migrations.AddField(
            model_name="comments",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="heritage_data.culturalentity",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="link",
            field=models.CharField(
                blank=True,
                help_text="Frontend URL to navigate to when notification is clicked",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("submission_update", "Submission Update"),
                    ("comment", "Comment"),
                    ("moderation", "Moderation"),
                    ("suggestion_review", "Edit Suggestion Review"),
                    ("review_decision", "Review Decision"),
                    ("revision", "Revision"),
                    ("reaction", "Reaction"),
                    ("fork", "Fork"),
                    ("general", "General"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="comments",
            index=models.Index(
                fields=["submission", "created_at"], name="comments_submiss_6239f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read", "created_at"],
                name="notificatio_user_id_5cf777_idx",
            ),
        ),
        migrations.AlterModelTable(
            name="comments",
            table="comments",
        ),
        migrations.AlterModelTable(
            name="notification",
            table="notifications",
        ),
        migrations.AddField(
            model_name="fork",
            name="forked_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forked_entities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fork",
            name="forked_entity",
            field=models.ForeignKey(
                help_text="The new entity created from the fork",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forked_from",
                to="heritage_data.culturalentity",
            ),
        ),
        migrations.AddField(
            model_name="fork",
            name="forked_from_revision",
            field=models.ForeignKey(
                blank=True,
                help_text="The specific revision that was forked",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forks",
                to="heritage_data.revision",
            ),
        ),
        migrations.AddField(
            model_name="fork",
            name="original_entity",
            field=models.ForeignKey(
                help_text="The entity that was forked",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forks",
                to="heritage_data.culturalentity",
            ),
        ),
        migrations.AddField(
            model_name="reaction",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="heritage_data.comments",
            ),
        ),
        migrations.AddField(
            model_name="reaction",
            name="entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="heritage_data.culturalentity",
            ),
        ),
        migrations.AddField(
            model_name="reaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="share",
            name="entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shares",
                to="heritage_data.culturalentity",
            ),
        ),
        migrations.AddField(
            model_name="share",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shares",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="fork",
            index=models.Index(
                fields=["original_entity", "created_at"],
                name="forks_origina_7a8663_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reaction",
            index=models.Index(
                fields=["entity", "reaction_type"], name="reactions_entity__445ec3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reaction",
            index=models.Index(
                fields=["comment", "reaction_type"], name="reactions_comment_143177_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="reaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("entity__isnull", False)),
                fields=("user", "entity"),
                name="unique_user_entity_reaction",
            ),
        ),
        migrations.AddConstraint(
            model_name="reaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("comment__isnull", False)),
                fields=("user", "comment"),
                name="unique_user_comment_reaction",
            ),
        ),
    ]
