# Generated by Django 5.2.8 on 2026-03-03 08:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heritage_data", "0003_fork_reaction_share_alter_comments_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicContribution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_reference_id",
                    models.CharField(
                        blank=True,
                        help_text="External ID reference (from QR code) if entity not in system",
                        max_length=255,
                    ),
                ),
                (
                    "entity_name",
                    models.CharField(
                        help_text="Name/label of the heritage site from QR code",
                        max_length=255,
                    ),
                ),
                (
                    "contribution_type",
                    models.CharField(
                        choices=[
                            ("history", "Historical Information"),
                            ("story", "Story or Legend"),
                            ("tradition", "Cultural Practice/Tradition"),
                            ("memory", "Personal Memory"),
                            ("photo", "Photo Description"),
                            ("correction", "Correction/Update"),
                            ("other", "Other Information"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="The actual contribution content"),
                ),
                (
                    "contributor_name",
                    models.CharField(blank=True, default="Anonymous", max_length=255),
                ),
                (
                    "contributor_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "contributor_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "source_description",
                    models.TextField(
                        blank=True,
                        help_text="How the contributor knows this information",
                    ),
                ),
                (
                    "submitted_via",
                    models.CharField(
                        choices=[
                            ("qr_scan", "QR Code Scan"),
                            ("web_form", "Web Form"),
                            ("mobile_app", "Mobile App"),
                            ("field_survey", "Field Survey"),
                        ],
                        default="qr_scan",
                        max_length=20,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="GPS latitude where contribution was made",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="GPS longitude where contribution was made",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("incorporated", "Incorporated"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_notes",
                    models.TextField(blank=True, help_text="Notes from reviewer"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        help_text="The entity this contribution is about (if exists in system)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="public_contributions",
                        to="heritage_data.culturalentity",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_public_contributions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Public Contribution",
                "verbose_name_plural": "Public Contributions",
                "db_table": "public_contributions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="public_cont_status_56c0e4_idx",
                    ),
                    models.Index(
                        fields=["entity", "created_at"],
                        name="public_cont_entity__687ba7_idx",
                    ),
                    models.Index(
                        fields=["contribution_type"],
                        name="public_cont_contrib_dc0031_idx",
                    ),
                ],
            },
        ),
    ]
