# Generated by Django 5.2.8 on 2026-03-14 07:37

import uuid
from django.db import migrations

def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model('heritage_data', 'UserProfile')
    for row in MyModel.objects.all():
        row.slug = uuid.uuid4()
        row.save(update_fields=['slug'])

class Migration(migrations.Migration):

    dependencies = [
        ('heritage_data', '0005_userprofile_slug'),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
