# Generated by Django 5.2.8 on 2026-03-14 07:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage_data', '0006_backfill_uuids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public URL-safe identifier for profile pages', unique=True),
        ),
    ]
