# Generated by Django 5.2.12 on 2026-03-20 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage_data', '0009_add_actor_to_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='culturalentity',
            name='fork_depth',
            field=models.PositiveIntegerField(default=0, help_text='0 = root, 1 = direct fork, etc.'),
        ),
        migrations.AddField(
            model_name='culturalentity',
            name='parent_entity',
            field=models.ForeignKey(blank=True, help_text='Immediate parent in the fork tree', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_forks', to='heritage_data.culturalentity'),
        ),
        migrations.AddField(
            model_name='culturalentity',
            name='root_entity',
            field=models.ForeignKey(blank=True, help_text='Root of the fork tree; null if this IS the root', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_forks', to='heritage_data.culturalentity'),
        ),
        migrations.AddField(
            model_name='fork',
            name='diff_summary',
            field=models.JSONField(blank=True, default=dict, help_text='Field-level diff vs parent at fork time'),
        ),
        migrations.AddField(
            model_name='fork',
            name='fork_reason_tag',
            field=models.CharField(choices=[('correction', 'Factual Correction'), ('translation', 'Language / Translation Variant'), ('expansion', 'Add Missing Information'), ('source_addition', 'Source Citation'), ('dispute', 'Dispute Existing Claim'), ('other', 'Other')], default='other', help_text='Structured reason category for the fork', max_length=30),
        ),
        migrations.AddField(
            model_name='fork',
            name='fork_status',
            field=models.CharField(choices=[('active', 'Active'), ('merged', 'Merged'), ('promoted', 'Promoted'), ('rejected', 'Rejected')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='fork',
            name='merged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fork',
            name='merged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_forks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='culturalentity',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending_revision', 'Pending Revision'), ('merged', 'Merged'), ('superseded', 'Superseded')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='culturalentity',
            index=models.Index(fields=['root_entity'], name='cultural_en_root_en_748fc6_idx'),
        ),
        migrations.AddIndex(
            model_name='culturalentity',
            index=models.Index(fields=['parent_entity'], name='cultural_en_parent__81be3d_idx'),
        ),
        migrations.AddIndex(
            model_name='fork',
            index=models.Index(fields=['fork_status'], name='forks_fork_st_165e6e_idx'),
        ),
        migrations.AddIndex(
            model_name='fork',
            index=models.Index(fields=['fork_reason_tag'], name='forks_fork_re_0bfcd4_idx'),
        ),
    ]
