# Generated by Django 5.2.8 on 2026-04-12 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "heritage_data",
            "0012_merge_0005_reviewer_role_request_0011_backfill_fork_lineage",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="ReviewerRoleRequest",
        ),
    ]
