# Generated by Django 5.2.8 on 2026-04-18 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heritage_data", "0013_delete_reviewerrolerequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="cultural_entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="heritage_data.culturalentity",
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="submission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="heritage_data.submission",
            ),
        ),
    ]
