# Generated by Django 5.2.8 on 2026-04-18 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heritage_data', '0015_reviewer_application'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reviewerapplication',
            new_name='reviewer_ap_user_id_e06095_idx',
            old_name='revapp_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='reviewerapplication',
            new_name='reviewer_ap_status_52115b_idx',
            old_name='revapp_status_created_idx',
        ),
    ]
