# Generated by Django 5.2.8 on 2026-04-25 17:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "heritage_data",
            "0016_rename_revapp_user_created_idx_reviewer_ap_user_id_e06095_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SchemaExtensionProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("published", "Published"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("base_schema_version", models.CharField(blank=True, max_length=128)),
                (
                    "proposed_yaml",
                    models.TextField(help_text="YAML overlay or LinkML fragment"),
                ),
                ("conflict_keys", models.JSONField(blank=True, default=list)),
                ("moderator_comment", models.TextField(blank=True)),
                (
                    "published_schema_version",
                    models.CharField(blank=True, max_length=128),
                ),
                (
                    "published_extension_hash",
                    models.CharField(blank=True, max_length=128),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schema_extension_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "schema_extension_proposals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SchemaExtensionAuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(db_index=True, max_length=40)),
                ("from_status", models.CharField(blank=True, max_length=20)),
                ("to_status", models.CharField(blank=True, max_length=20)),
                ("comment", models.TextField(blank=True)),
                (
                    "schema_version_snapshot",
                    models.CharField(blank=True, max_length=128),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schema_extension_audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_events",
                        to="heritage_data.schemaextensionproposal",
                    ),
                ),
            ],
            options={
                "db_table": "schema_extension_audit_events",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="TriagePolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "w_age",
                    models.DecimalField(decimal_places=3, default=2.5, max_digits=6),
                ),
                (
                    "w_flags",
                    models.DecimalField(decimal_places=3, default=1.5, max_digits=6),
                ),
                (
                    "w_conflict",
                    models.DecimalField(decimal_places=3, default=3.0, max_digits=6),
                ),
                (
                    "w_source",
                    models.DecimalField(decimal_places=3, default=1.0, max_digits=6),
                ),
                ("s_max_days", models.PositiveIntegerField(default=30)),
                ("f_max_flags", models.PositiveIntegerField(default=10)),
                (
                    "tier_rank_json",
                    models.JSONField(
                        default=list,
                        help_text="Ordered source_type values best→worst for trust (see spec assumptions).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triage_policy_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Triage policy",
                "verbose_name_plural": "Triage policies",
                "db_table": "triage_policies",
            },
        ),
        migrations.AddIndex(
            model_name="schemaextensionproposal",
            index=models.Index(
                fields=["status", "submitted_at"], name="schema_exte_status_fbaa59_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schemaextensionproposal",
            index=models.Index(
                fields=["author", "status"], name="schema_exte_author__bc0d27_idx"
            ),
        ),
    ]
