# Generated by Django 5.2.8 on 2026-04-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heritage_data", "0017_triage_policy_and_schema_extension_proposals"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="contributor_mode",
            field=models.CharField(
                choices=[("basic", "Basic"), ("advanced", "Advanced")],
                default="basic",
                help_text="Global contributor experience mode used by ontology forms.",
                max_length=16,
            ),
        ),
    ]
