# Generated by Django 5.2.8 on 2026-05-04 16:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidoc_data', '0011_knowledge_graph_proposals'),
        ('heritage_data', '0018_userprofile_contributor_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='draft', max_length=20)),
                ('canonical_label', models.CharField(max_length=500)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('type_scope', models.CharField(max_length=100)),
                ('anchor_records', models.JSONField(default=list, help_text='[{"entity_type":"person","entity_id":123}, …] CIDOC rows')),
                ('supporting_source_ids', models.JSONField(blank=True, default=list)),
                ('contributor_note', models.TextField(blank=True)),
                ('external_identifiers', models.JSONField(blank=True, default=dict)),
                ('resolution_mode', models.CharField(choices=[('new_cluster', 'Create new cluster'), ('link_existing', 'Link anchors to existing cluster')], default='new_cluster', max_length=32)),
                ('moderator_comment', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_proposals', to=settings.AUTH_USER_MODEL)),
                ('existing_cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_proposals_linking', to='cidoc_data.entitycluster')),
                ('materialized_cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_proposals_materialized', to='cidoc_data.entitycluster')),
            ],
            options={
                'db_table': 'entity_proposals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntityProposalAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=40)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(blank=True, max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_proposal_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='heritage_data.entityproposal')),
            ],
            options={
                'db_table': 'entity_proposal_audit_events',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RelationshipProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='draft', max_length=20)),
                ('subject_entity_type', models.CharField(max_length=100)),
                ('subject_entity_id', models.PositiveIntegerField()),
                ('object_entity_type', models.CharField(max_length=100)),
                ('object_entity_id', models.PositiveIntegerField()),
                ('supporting_source_ids', models.JSONField(blank=True, default=list)),
                ('temporal_scope_edtf', models.CharField(blank=True, max_length=255)),
                ('confidence', models.CharField(default='likely', max_length=20)),
                ('interpretation_note', models.TextField(blank=True)),
                ('moderator_comment', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_proposals', to=settings.AUTH_USER_MODEL)),
                ('materialized_assertion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relationship_proposals_materialized', to='cidoc_data.heritageassertion')),
                ('predicate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relationship_proposals', to='cidoc_data.relationshippredicate')),
                ('primary_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relationship_proposals_primary', to='cidoc_data.datasource')),
            ],
            options={
                'db_table': 'relationship_proposals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RelationshipProposalAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=40)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(blank=True, max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relationship_proposal_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='heritage_data.relationshipproposal')),
            ],
            options={
                'db_table': 'relationship_proposal_audit_events',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='entityproposal',
            index=models.Index(fields=['status', 'submitted_at'], name='entity_prop_status_4c07fc_idx'),
        ),
        migrations.AddIndex(
            model_name='entityproposal',
            index=models.Index(fields=['author', 'status'], name='entity_prop_author__7cf491_idx'),
        ),
        migrations.AddIndex(
            model_name='relationshipproposal',
            index=models.Index(fields=['status', 'submitted_at'], name='relationshi_status_a83353_idx'),
        ),
        migrations.AddIndex(
            model_name='relationshipproposal',
            index=models.Index(fields=['author', 'status'], name='relationshi_author__0389c3_idx'),
        ),
    ]
