# Generated by Django 5.2.8 on 2026-05-16 17:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heritage_data", "0020_media_ingestion_contributor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("abstract", models.TextField(blank=True)),
                (
                    "intended_subject",
                    models.CharField(
                        blank=True,
                        help_text="Free-text subject hint (e.g. 'temple', 'ritual'); guides class suggestions.",
                        max_length=120,
                    ),
                ),
                (
                    "languages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of BCP-47 language tags this project authors in.",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("org", "Organization"),
                            ("public", "Public"),
                        ],
                        default="private",
                        max_length=10,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_review", "In Review"),
                            ("needs_revision", "Needs Revision"),
                            ("approved", "Approved"),
                            ("merged", "Merged"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "schema_version",
                    models.CharField(
                        blank=True,
                        help_text="Git SHA of ontology/HeritageGraph.yaml at project start.",
                        max_length=40,
                    ),
                ),
                (
                    "canvas_state",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Persistent node positions for the drag-and-arrow canvas.",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Free-form tags used by reviewer-queue filters.",
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("merged_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "forked_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forks",
                        to="heritage_data.project",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "projects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("editor", "Editor"),
                            ("viewer", "Viewer"),
                            ("domain_expert", "Domain Expert"),
                        ],
                        default="editor",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_invitations_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="heritage_data.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "project_memberships",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="collaborators",
            field=models.ManyToManyField(
                blank=True,
                related_name="projects",
                through="heritage_data.ProjectMembership",
                through_fields=("project", "user"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ProjectActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("state_changed", "State Changed"),
                            ("member_added", "Member Added"),
                            ("member_removed", "Member Removed"),
                            ("asset_added", "Asset Added"),
                            ("asset_removed", "Asset Removed"),
                            ("entity_linked", "Entity Linked"),
                            ("entity_unlinked", "Entity Unlinked"),
                            ("submitted", "Submitted"),
                            ("reviewed", "Reviewed"),
                            ("merged", "Merged"),
                            ("forked", "Forked"),
                            ("commented", "Commented"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "target_kind",
                    models.CharField(
                        blank=True,
                        help_text="Optional kind hint for the target (e.g. 'entity', 'asset', 'membership').",
                        max_length=40,
                    ),
                ),
                ("target_id", models.CharField(blank=True, max_length=64)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="heritage_data.project",
                    ),
                ),
            ],
            options={
                "db_table": "project_activities",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "created_at"],
                        name="project_act_project_bacef8_idx",
                    ),
                    models.Index(
                        fields=["actor"], name="project_act_actor_i_d15be7_idx"
                    ),
                    models.Index(
                        fields=["action"], name="project_act_action_458aed_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("evidence", "Evidence"),
                            ("primary", "Primary"),
                            ("reference", "Reference"),
                        ],
                        default="evidence",
                        max_length=20,
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_assets",
                        to="heritage_data.media",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="heritage_data.project",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_assets_uploaded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "project_assets",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "role"],
                        name="project_ass_project_87b5b2_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectEntity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role_in_project",
                    models.CharField(
                        blank=True,
                        help_text="Free-text role, e.g. 'subject', 'context', 'reference'.",
                        max_length=120,
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_entities_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_links",
                        to="heritage_data.culturalentity",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entities",
                        to="heritage_data.project",
                    ),
                ),
            ],
            options={
                "db_table": "project_entities",
                "ordering": ["-added_at"],
                "indexes": [
                    models.Index(
                        fields=["project"], name="project_ent_project_91c643_idx"
                    ),
                    models.Index(
                        fields=["entity"], name="project_ent_entity__f55801_idx"
                    ),
                ],
                "unique_together": {("project", "entity")},
            },
        ),
        migrations.AddIndex(
            model_name="projectmembership",
            index=models.Index(
                fields=["project", "role"], name="project_mem_project_ce1662_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectmembership",
            index=models.Index(fields=["user"], name="project_mem_user_id_95343b_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="projectmembership",
            unique_together={("project", "user")},
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["state"], name="projects_state_6175d9_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["visibility"], name="projects_visibil_ea9b2f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["owner"], name="projects_owner_i_c299b3_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["created_at"], name="projects_created_40bcd1_idx"
            ),
        ),
    ]
