# Generated by Django 5.2.8 on 2026-05-16 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage_data', '0021_project_projectmembership_project_collaborators_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='heritage_data.project'),
        ),
        migrations.AddField(
            model_name='notification',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='heritage_data.project'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='heritage_data.culturalentity'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('submission_update', 'Submission Update'), ('comment', 'Comment'), ('moderation', 'Moderation'), ('suggestion_review', 'Edit Suggestion Review'), ('review_decision', 'Review Decision'), ('revision', 'Revision'), ('reaction', 'Reaction'), ('fork', 'Fork'), ('general', 'General'), ('project_state_changed', 'Project State Changed'), ('project_comment', 'Project Comment')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='comments',
            index=models.Index(fields=['project', 'created_at'], name='comments_project_7329f9_idx'),
        ),
    ]
