# Generated by Django 5.2.8 on 2026-05-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage_data', '0022_project_comments_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='ocr_deferred',
            field=models.BooleanField(default=False, help_text='When true, OCR is not auto-queued on upload; use project start-ocr or OCR upload.'),
        ),
    ]
