# Generated by Django 5.2.8 on 2026-06-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage_data', '0024_project_asset_snapshots_review_hooks'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='projectsnapshot',
            new_name='project_sna_project_4aa036_idx',
            old_name='project_snap_project_8947d9_idx',
        ),
        migrations.AlterField(
            model_name='projectasset',
            name='entity_suggestions',
            field=models.JSONField(blank=True, default=list, help_text='Suggested ontology links from OCR/NER pipelines (stub until full matching).'),
        ),
        migrations.AlterField(
            model_name='projectasset',
            name='version_label',
            field=models.CharField(blank=True, help_text='Contributor label for this revision of the attachment (v2, revised-2026, …).', max_length=120),
        ),
        migrations.AlterField(
            model_name='projectsnapshot',
            name='snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Serialized pointers (entity ids, title, slug) captured at merge time.'),
        ),
    ]
