# Generated by Django 5.2.8 on 2026-06-12 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('heritage_data', '0025_rename_project_snap_project_8947d9_idx_project_sna_project_4aa036_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='culturalentity',
            name='accepted_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_for_entity', to='heritage_data.revision', verbose_name='Accepted Revision'),
        ),
        migrations.AddField(
            model_name='culturalentity',
            name='cidoc_content_type',
            field=models.ForeignKey(blank=True, help_text='ContentType of the linked cidoc_data record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='culturalentity',
            name='cidoc_object_id',
            field=models.PositiveIntegerField(blank=True, help_text='Primary key of the linked cidoc_data record', null=True),
        ),
        migrations.AddField(
            model_name='publiccontribution',
            name='promoted_entity',
            field=models.ForeignKey(blank=True, help_text='CulturalEntity created when this contribution was promoted into the structured review pipeline', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_from_public_contributions', to='heritage_data.culturalentity'),
        ),
        migrations.AddIndex(
            model_name='culturalentity',
            index=models.Index(fields=['cidoc_content_type', 'cidoc_object_id'], name='cultural_en_cidoc_c_439046_idx'),
        ),
    ]
