# Generated by Django 5.2.8 on 2026-08-09 16:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage_data', '0030_reconciledlink_curatoralert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.DateField(help_text='First day of the calendar month this snapshot summarises.')),
                ('total_submissions', models.PositiveIntegerField(default=0)),
                ('contributor_rank', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('approval_rate', models.FloatField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_stats_snapshot',
                'ordering': ['-period'],
            },
        ),
        migrations.AlterModelOptions(
            name='userstats',
            options={'verbose_name_plural': 'user stats'},
        ),
        migrations.RenameIndex(
            model_name='curatoralert',
            new_name='curator_ale_status_193873_idx',
            old_name='curator_alert_status_idx',
        ),
        migrations.RenameIndex(
            model_name='curatoralert',
            new_name='curator_ale_issue_t_63d8b2_idx',
            old_name='curator_alert_issue_type_idx',
        ),
        migrations.RenameIndex(
            model_name='mergerequest',
            new_name='merge_reque_project_faebf3_idx',
            old_name='mr_project_status_idx',
        ),
        migrations.RenameIndex(
            model_name='mergerequest',
            new_name='merge_reque_opened__ea474d_idx',
            old_name='mr_opened_by_idx',
        ),
        migrations.RenameIndex(
            model_name='mergerequest',
            new_name='merge_reque_status_f48ccb_idx',
            old_name='mr_status_idx',
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='community_impact_score',
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='impact_score_change',
        ),
        migrations.AlterField(
            model_name='mergerequest',
            name='conflict_diff',
            field=models.JSONField(blank=True, default=dict, help_text='Computed diff: {added, removed, conflicts} triple-count summary.'),
        ),
        migrations.AlterField(
            model_name='mergerequest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mergerequest',
            name='merge_activity_uri',
            field=models.URLField(blank=True, help_text='PROV-O MergeActivity IRI written after successful merge.', max_length=300),
        ),
        migrations.AlterField(
            model_name='mergerequest',
            name='new_pids',
            field=models.JSONField(blank=True, default=list, help_text='List of newly minted global PIDs after merge.'),
        ),
        migrations.AlterField(
            model_name='mergerequest',
            name='pid_collisions',
            field=models.JSONField(blank=True, default=list, help_text='List of PID IRIs that collide with the main graph.'),
        ),
        migrations.AlterField(
            model_name='mergerequest',
            name='reviewer_note',
            field=models.TextField(blank=True, help_text='Reviewer feedback (changes requested or approval verification note).'),
        ),
        migrations.AlterField(
            model_name='mergerequest',
            name='shacl_report',
            field=models.JSONField(blank=True, default=dict, help_text='Cached SHACL validation report at time of MR opening.'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='accepted_count',
            field=models.PositiveIntegerField(default=0, help_text='Contributions accepted or merged after review.'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='approval_rate',
            field=models.FloatField(blank=True, default=None, help_text='accepted_count / total_reviewed as a percentage. Null until at least one contribution has been reviewed.', null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='approval_rate_change',
            field=models.FloatField(blank=True, default=None, help_text="Percentage-point difference between the approval rate of this month's submission cohort and last month's. Null unless both cohorts contain reviewed contributions.", null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='contributor_rank',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='1-based rank by profile score. Null when the user has no profile.', null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='rank_change',
            field=models.IntegerField(blank=True, default=None, help_text='Places gained since the most recent earlier UserStatsSnapshot (positive = improved). Null when no earlier snapshot exists.', null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='submissions_growth',
            field=models.FloatField(blank=True, default=None, help_text='Percent change in submissions created this month vs last month. Null when last month has no submissions to divide by.', null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='total_reviewed',
            field=models.PositiveIntegerField(default=0, help_text='Contributions with a terminal review decision.'),
        ),
        migrations.AddField(
            model_name='userstatssnapshot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='userstatssnapshot',
            constraint=models.UniqueConstraint(fields=('user', 'period'), name='unique_user_stats_snapshot_period'),
        ),
    ]
