# Generated by Django 5.2.8 on 2026-05-28 12:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_fix_email_usernames'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('login_success', 'Login success'), ('login_failure', 'Login failure'), ('token_refresh', 'Token refresh'), ('logout', 'Logout')], max_length=32)),
                ('provider', models.CharField(choices=[('google', 'Google'), ('github', 'GitHub'), ('jwt', 'JWT'), ('dev', 'Dev')], max_length=16)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('failure_reason', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users_auth_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='users_auth__created_e0ece6_idx'), models.Index(fields=['email', '-created_at'], name='users_auth__email_e18261_idx'), models.Index(fields=['ip_address', '-created_at'], name='users_auth__ip_addr_70c9eb_idx')],
            },
        ),
    ]
