// AUTO-GENERATED — do not edit by hand.
// Source:  ontology/HeritageGraph.yaml + tools/ui-vizmap.yaml
// Regen:   python3 tools/gen_heritage_viz_config.py  (or: make ontology)
// Hash:    64ad8fff9a58cdf8
//
// Cytoscape schema graph (/graphview → Ontology tab).

export type OntologyCategory =
  | 'tangible'
  | 'conceptual'
  | 'event'
  | 'social'
  | 'spatial'
  | 'provenance'
  | 'kumari'
  | 'enum'
  | 'external';

export interface OntologyNode {
  id: string;
  label: string;
  category: OntologyCategory;
  cidocMapping: string;
  description: string;
  parent?: string;
}

export interface OntologyEdge {
  id: string;
  source: string;
  target: string;
  label: string;
  edgeType: 'is_a' | 'object_property';
}

export interface OntologyGraphData {
  nodes: OntologyNode[];
  edges: OntologyEdge[];
}

export const CATEGORY_COLORS: Record<
  OntologyCategory,
  { bg: string; border: string; text: string; label: string }
> = {
  tangible: { bg: "#3b82f6", border: "#2563eb", text: "#fff", label: "Tangible Heritage" },
  conceptual: { bg: "#8b5cf6", border: "#7c3aed", text: "#fff", label: "Conceptual Entities" },
  event: { bg: "#f59e0b", border: "#d97706", text: "#fff", label: "Events" },
  social: { bg: "#10b981", border: "#059669", text: "#fff", label: "Social / Actors" },
  spatial: { bg: "#06b6d4", border: "#0891b2", text: "#fff", label: "Spatiotemporal" },
  provenance: { bg: "#ec4899", border: "#db2777", text: "#fff", label: "Provenance" },
  kumari: { bg: "#ef4444", border: "#dc2626", text: "#fff", label: "Living Goddess" },
  enum: { bg: "#94a3b8", border: "#64748b", text: "#fff", label: "Enumerations" },
  external: { bg: "#78716c", border: "#57534e", text: "#fff", label: "External (CRM/AAT)" },
};

const NODES: OntologyNode[] = [
  { id: "Activity", label: "Activity", category: "event", cidocMapping: "prov:Activity", description: "Direct LinkML representation of prov:Activity. Applied to events and processes that use, transform, generate, document, assess, or verify entities." },
  { id: "Actor", label: "Actor", category: "tangible", cidocMapping: "crm:E39_Actor", description: "General actor (person or group) responsible for events" },
  { id: "AgeCriterion", label: "AgeCriterion", category: "tangible", cidocMapping: "heritageGraph:AgeCriterion", description: "Candidate must be within the prescribed pre-pubescent age range.", parent: "SelectionCriterion" },
  { id: "Agent", label: "Agent", category: "tangible", cidocMapping: "prov:Agent", description: "Direct LinkML representation of prov:Agent. Agents bear responsibility for activities or entities. PROV-O permits an individual agent also to be typed as an Entity, but does not define every Agent as a subclass of Entity." },
  { id: "ArchitecturalElement", label: "ArchitecturalElement", category: "tangible", cidocMapping: "heritageGraph:ArchitecturalElement", description: "Carved or constructed component of an architectural structure (e.g., Gajur, Torana, Tundal)" },
  { id: "ArchitecturalStructure", label: "ArchitecturalStructure", category: "tangible", cidocMapping: "heritageGraph:ArchitecturalStructure", description: "Physical structures built for religious, social, or civic purposes. Links to events of production, use, custody, and documentation.", parent: "HumanMadeObject" },
  { id: "ArchivalRecord", label: "ArchivalRecord", category: "tangible", cidocMapping: "heritageGraph:ArchivalRecord", description: "Government or institutional administrative record", parent: "DataSource" },
  { id: "AssertableEntity", label: "AssertableEntity", category: "tangible", cidocMapping: "crminf:E1_Entity", description: "Any entity that can be the subject of a heritage assertion" },
  { id: "Assertion", label: "Assertion", category: "tangible", cidocMapping: "crminf:I2_Belief", description: "A provenance-bearing belief or claim about a heritage entity or event. The assertion is represented as CRMinf I2 Belief and as a prov:Entity, allowing source, attribution, generation time, revision, confidence, and reconciliation status to be recorded explicitly." },
  { id: "AssertionSubject", label: "AssertionSubject", category: "tangible", cidocMapping: "heritageGraph:AssertionSubject", description: "Any HeritageGraph entity or event that may be the subject of an assertion." },
  { id: "BuddhistMonument", label: "BuddhistMonument", category: "tangible", cidocMapping: "heritageGraph:BuddhistMonument", description: "Buddhist sacred structure (Stupa, Chaitya) with circumambulation and ritual activation patterns", parent: "ArchitecturalStructure" },
  { id: "CalendarSystem", label: "CalendarSystem", category: "tangible", cidocMapping: "heritageGraph:CalendarSystem", description: "Calendar reckoning system with conversion rules for multi-calendar temporal reasoning" },
  { id: "CasteGroup", label: "CasteGroup", category: "social", cidocMapping: "heritageGraph:CasteGroup", description: "Hereditary social group (Jati) with specific ritual roles and occupational duties", parent: "Actor" },
  { id: "Chaitya", label: "Chaitya", category: "tangible", cidocMapping: "heritageGraph:Chaitya", description: "Buddhist votive shrine (chaitya); votive stupa form found across the Kathmandu Valley.", parent: "ReligiousStructure" },
  { id: "ChariotFestival", label: "ChariotFestival", category: "event", cidocMapping: "heritageGraph:ChariotFestival", description: "Festival involving ceremonial chariot procession (e.g., Rato Machhindranath Jatra)", parent: "Festival" },
  { id: "ConditionAssessment", label: "ConditionAssessment", category: "tangible", cidocMapping: "crm:E14_Condition_Assessment", description: "Event of evaluating the physical state of a heritage object or structure" },
  { id: "ConditionState", label: "ConditionState", category: "tangible", cidocMapping: "crm:E3_Condition_State", description: "A physical condition state of a heritage object" },
  { id: "Consecration", label: "Consecration", category: "event", cidocMapping: "heritageGraph:Consecration", description: "Ritual event that transforms an object into a sacred vessel (e.g., Prana Pratistha for Murti)" },
  { id: "Container", label: "Container", category: "tangible", cidocMapping: "Container", description: "Root container for cultural heritage data instances. PLACEMENT RULE: put each instance in the most specific collection available (e.g. a Festival in festivals, not ritual_events; a Person in persons, not actors); broader collections exist for instances of the general classes only." },
  { id: "CulturalEntity", label: "CulturalEntity", category: "tangible", cidocMapping: "heritageGraph:CulturalEntity", description: "High-level cultural contribution (monuments, festivals, rituals, traditions, artifacts) for the heritage_data review workflow." },
  { id: "DataCustodian", label: "DataCustodian", category: "tangible", cidocMapping: "heritageGraph:DataCustodian", description: "Institution or person currently responsible for stewarding heritage data.", parent: "Actor" },
  { id: "DataSource", label: "DataSource", category: "tangible", cidocMapping: "heritageGraph:DataSource", description: "Original source from which heritage information was derived" },
  { id: "Deity", label: "Deity", category: "conceptual", cidocMapping: "heritageGraph:Deity", description: "Divine conceptual entity in Hindu, Buddhist, or syncretic traditions. Distinct from physical representations (Murti) and ritual presences." },
  { id: "DestructionEvent", label: "DestructionEvent", category: "event", cidocMapping: "crm:E6_Destruction", description: "Event that destroyed or damaged a structure.", parent: "HistoricalEvent" },
  { id: "Dharmashala", label: "Dharmashala", category: "tangible", cidocMapping: "heritageGraph:Dharmashala", description: "Pilgrim lodge operated by a Guthi organization", parent: "RestHouse" },
  { id: "DhungeDhara", label: "DhungeDhara", category: "tangible", cidocMapping: "heritageGraph:DhungeDhara", description: "Stone spout (hiti) with carved imagery, used for ritual bathing and daily water supply", parent: "WaterStructure" },
  { id: "DocumentationActivity", label: "DocumentationActivity", category: "event", cidocMapping: "heritageGraph:DocumentationActivity", description: "Activity that records information about a heritage entity or event and may generate information objects or assertions. It aligns CIDOC CRM documentation practices with prov:Activity." },
  { id: "Enshrinement", label: "Enshrinement", category: "event", cidocMapping: "heritageGraph:Enshrinement", description: "Event of installing a deity's murti or symbol within a temple sanctum" },
  { id: "Entity", label: "Entity", category: "tangible", cidocMapping: "prov:Entity", description: "Direct LinkML representation of prov:Entity. Applied to physical, digital, conceptual, and assertion-bearing things that participate in provenance relations. PROVENANCE SCOPE (design decision): for classes whose instances are real-world referents (structures, deities, places, actors), the provenance slots (was_derived_from, was_attributed_to, was_generated_by, generated_at_time) describe the DATA RECORD about the referent, not the referent itself -- a stupa is not generated by the survey that records it. Referent-level history is modelled through events (Production, DestructionEvent, etc.). RDF deployments SHOULD carry record-level provenance in named graphs or on InformationObject/Assertion nodes." },
  { id: "FearlessnessAssessment", label: "FearlessnessAssessment", category: "event", cidocMapping: "heritageGraph:FearlessnessAssessment", description: "The 'fearlessness test' popularly described (animal heads, masked dancers in darkness). Its historical and contemporary practice is DISPUTED -- some former Kumaris contest how it is described. Represented as an assessment whose accounts are source-attributed via has_assertion, NOT as a mandatory criterion.", parent: "RitualAssessment" },
  { id: "Festival", label: "Festival", category: "event", cidocMapping: "heritageGraph:Festival", description: "Large-scale community ritual event (Jatra) involving processions, music, and collective participation", parent: "RitualEvent" },
  { id: "FieldSurveyActivity", label: "FieldSurveyActivity", category: "event", cidocMapping: "heritageGraph:FieldSurveyActivity", description: "The activity of measuring, photographing, or assessing a site in person.", parent: "DocumentationActivity" },
  { id: "FieldSurveyDataset", label: "FieldSurveyDataset", category: "tangible", cidocMapping: "heritageGraph:FieldSurveyDataset", description: "The structured data or report resulting from a field survey.", parent: "DataSource" },
  { id: "Group", label: "Group", category: "social", cidocMapping: "crm:E74_Group", description: "CIDOC-CRM/LinkedArt interop class for Yale LUX alignment (not user-contributable)." },
  { id: "Guthi", label: "Guthi", category: "social", cidocMapping: "heritageGraph:Guthi", description: "Endowed trust organization unique to Nepal, managing temples, rituals, and land through hereditary or voluntary membership", parent: "Actor" },
  { id: "HeritageAssertion", label: "HeritageAssertion", category: "tangible", cidocMapping: "crminf:I2_Belief", description: "A single factual claim about a heritage entity, with explicit source, author, date, and confidence" },
  { id: "HistoricalEvent", label: "HistoricalEvent", category: "event", cidocMapping: "heritageGraph:HistoricalEvent", description: "Major event affecting heritage structures or ritual life (earthquake, epidemic, political transition, fire, flood)." },
  { id: "HistoricalPeriod", label: "HistoricalPeriod", category: "spatial", cidocMapping: "heritageGraph:HistoricalPeriod", description: "A named, time-bounded historical period of Nepal (e.g., Lichhavi, Malla, Shah). A temporal frame within which heritage entities and events are situated — distinct from a single HistoricalEvent." },
  { id: "HoroscopeCompatibilityCriterion", label: "HoroscopeCompatibilityCriterion", category: "tangible", cidocMapping: "heritageGraph:HoroscopeCompatibilityCriterion", description: "Candidate's horoscope must be compatible with the city and ruling authority.", parent: "SelectionCriterion" },
  { id: "HumanMadeObject", label: "HumanMadeObject", category: "tangible", cidocMapping: "crm:E22_Human-Made_Object", description: "Physical objects created by human activity" },
  { id: "IconographicObject", label: "IconographicObject", category: "tangible", cidocMapping: "heritageGraph:IconographicObject", description: "Sacred visual art objects that depict or embody deities through iconographic conventions", parent: "HumanMadeObject" },
  { id: "InformationObject", label: "InformationObject", category: "provenance", cidocMapping: "heritageGraph:InformationObject", description: "A recorded piece of information about heritage", parent: "DataSource" },
  { id: "KumariEnthronementEvent", label: "KumariEnthronementEvent", category: "event", cidocMapping: "heritageGraph:KumariEnthronementEvent", description: "Ritual installing a selected girl into the Kumari role and residence, activating the tenure (distinct from selection, which chooses her, and retirement, which ends it).", parent: "KumariLifecycleEvent" },
  { id: "KumariHouse", label: "KumariHouse", category: "tangible", cidocMapping: "heritageGraph:KumariHouse", description: "God-house residence of a Kumari during tenure (e.g., Kumari Ghar, Kathmandu). Specialised ReligiousStructure.", parent: "ReligiousStructure" },
  { id: "KumariLifecycleEvent", label: "KumariLifecycleEvent", category: "event", cidocMapping: "heritageGraph:KumariLifecycleEvent", description: "Abstract event that bounds a KumariTenure (selection, enthronement, or retirement). Each concrete subclass requires exactly one tenure edge via slot_usage: initiated_tenure (selection), ended_tenure_of (retirement), or bounds_tenure itself (enthronement).", parent: "RitualEvent" },
  { id: "KumariRetirementEvent", label: "KumariRetirementEvent", category: "event", cidocMapping: "heritageGraph:KumariRetirementEvent", description: "Ritual or administrative event that formally ends a Living Goddess tenure, returning the person to secular status. Common triggers: first menstruation, injury causing blood loss, serious illness.", parent: "KumariLifecycleEvent" },
  { id: "KumariRole", label: "KumariRole", category: "tangible", cidocMapping: "heritageGraph:KumariRole", description: "The role/office of Kumari (living-goddess embodiment) that a person assumes for the duration of a KumariTenure. The role is the type; the tenure is the time-bounded holding of it; the person is the holder." },
  { id: "KumariSelectionEvent", label: "KumariSelectionEvent", category: "event", cidocMapping: "heritageGraph:KumariSelectionEvent", description: "Tantric ritual process of selecting a new Living Goddess from eligible candidates. Involves examination of 32 auspicious physical marks (lakshana), horoscope matching with the city and ruling authority, and tests of fearlessness (e.g., remaining calm among buffalo heads and masked dancers in darkness). Performed by committee of Vajracharya priests, royal priest (Raj Jyotish), and astrologer.", parent: "KumariLifecycleEvent" },
  { id: "KumariTenure", label: "KumariTenure", category: "tangible", cidocMapping: "heritageGraph:KumariTenure", description: "Time-bounded role where a person embodies a deity as Living Goddess (Kumari), residing at a specific god-house and supported by religious institutions. This class captures the unique Nepali tradition of living deity embodiment in young girls selected from Buddhist Shakya/Vajracharya families." },
  { id: "LineageCriterion", label: "LineageCriterion", category: "tangible", cidocMapping: "heritageGraph:LineageCriterion", description: "Candidate must belong to an eligible lineage (Shakya / Vajracharya Newar Buddhist family).", parent: "SelectionCriterion" },
  { id: "LivingGoddessRetirement", label: "LivingGoddessRetirement", category: "kumari", cidocMapping: "heritageGraph:LivingGoddessRetirement", description: "Ritual or administrative event that formally ends a Living Goddess tenure, marking the person's return to secular status. Common triggers include first menstruation, injury causing blood loss, or serious illness. This event terminates the divine embodiment and restores the girl to ordinary status.", parent: "RitualEvent" },
  { id: "LivingGoddessSelection", label: "LivingGoddessSelection", category: "kumari", cidocMapping: "heritageGraph:LivingGoddessSelection", description: "Tantric ritual process of selecting a new Living Goddess from eligible candidates. Involves examination of 32 auspicious physical marks (lakshana), horoscope matching with the city and ruling authority, and tests of fearlessness (e.g., remaining calm among buffalo heads and masked dancers in darkness). Performed by committee of Vajracharya priests, royal priest (Raj Jyotish), and astrologer.", parent: "RitualEvent" },
  { id: "LivingGoddessTenure", label: "LivingGoddessTenure", category: "kumari", cidocMapping: "crm:E4_Period", description: "Time-bounded role where a person embodies a deity as Living Goddess (Kumari), residing at a specific god-house and supported by religious institutions. This class captures the unique Nepali tradition of living deity embodiment in young girls selected from Buddhist Shakya/Vajracharya families." },
  { id: "MaskedDance", label: "MaskedDance", category: "event", cidocMapping: "heritageGraph:MaskedDance", description: "Festival featuring masked dancers embodying deities (e.g., Kartik Naach)", parent: "Festival" },
  { id: "Material", label: "Material", category: "tangible", cidocMapping: "crm:E57_Material", description: "Physical substance used in construction or crafting" },
  { id: "Metadata", label: "Metadata", category: "tangible", cidocMapping: "Metadata", description: "Dataset metadata information" },
  { id: "Murti", label: "Murti", category: "tangible", cidocMapping: "heritageGraph:Murti", description: "Consecrated statue of a deity, ritually activated to serve as divine presence (not merely depiction)", parent: "IconographicObject" },
  { id: "OralHistoryInterview", label: "OralHistoryInterview", category: "tangible", cidocMapping: "heritageGraph:OralHistoryInterview", description: "The interaction event between a researcher and a knowledge holder.", parent: "DocumentationActivity" },
  { id: "OralHistoryRecording", label: "OralHistoryRecording", category: "tangible", cidocMapping: "heritageGraph:OralHistoryRecording", description: "The recording or transcript of an oral history interview.", parent: "DataSource" },
  { id: "Pati", label: "Pati", category: "tangible", cidocMapping: "heritageGraph:Pati", description: "Open-air pavilion for resting travelers", parent: "RestHouse" },
  { id: "Paubha", label: "Paubha", category: "tangible", cidocMapping: "heritageGraph:Paubha", description: "Traditional Newari scroll painting (thangka) with mandala and deity iconography", parent: "IconographicObject" },
  { id: "Person", label: "Person", category: "social", cidocMapping: "crm:E21_Person", description: "Individual person who performs, commissions, documents, or verifies heritage activities", parent: "Actor" },
  { id: "PhysicalHeritageThing", label: "PhysicalHeritageThing", category: "tangible", cidocMapping: "heritageGraph:PhysicalHeritageThing", description: "Union of the tangible heritage classes: architectural structures, iconographic objects, and standalone architectural elements. Used as the range of slots that apply to any physical heritage thing (production, custody, condition assessment)." },
  { id: "PhysicalIntegrityCriterion", label: "PhysicalIntegrityCriterion", category: "tangible", cidocMapping: "heritageGraph:PhysicalIntegrityCriterion", description: "Candidate must have an unblemished body with no scars, wounds, or loss of blood/teeth.", parent: "SelectionCriterion" },
  { id: "Place", label: "Place", category: "spatial", cidocMapping: "crm:E53_Place", description: "Defined geographic location where events occur and structures exist" },
  { id: "Pokhari", label: "Pokhari", category: "tangible", cidocMapping: "heritageGraph:Pokhari", description: "Pond or tank for water storage, ritual bathing, and ecological management", parent: "WaterStructure" },
  { id: "Production", label: "Production", category: "event", cidocMapping: "crm:E12_Production", description: "Event of creating an architectural structure, murti, or paubha" },
  { id: "Proposition", label: "Proposition", category: "tangible", cidocMapping: "heritageGraph:Proposition", description: "A single machine-readable proposition (subject - predicate - object) held true by an Assertion. Modelled as a singleton proposition set (CRMinf I4); the predicate is a URI/CURIE, the object either a heritage entity or a literal." },
  { id: "ReligiousStructure", label: "ReligiousStructure", category: "tangible", cidocMapping: "heritageGraph:ReligiousStructure", description: "Architectural structure whose defining purpose is religious: enshrines a deity and/or is a locus of ritual activation. Abstract grouping for sacred structures across traditions (temple, stupa, chaitya).", parent: "ArchitecturalStructure" },
  { id: "ReligiousTradition", label: "ReligiousTradition", category: "conceptual", cidocMapping: "heritageGraph:ReligiousTradition", description: "Religious or philosophical tradition (e.g., Hindu, Buddhist, Syncretic)" },
  { id: "RestHouse", label: "RestHouse", category: "tangible", cidocMapping: "heritageGraph:RestHouse", description: "Community structures for travelers and pilgrims, maintained by Guthi organizations", parent: "ArchitecturalStructure" },
  { id: "RitualAssessment", label: "RitualAssessment", category: "event", cidocMapping: "heritageGraph:RitualAssessment", description: "A performed assessment carried out during Kumari selection. Modelled as an event (not a hard criterion) so that source-specific, possibly conflicting accounts of whether/how it was conducted attach as provenanced Assertions rather than being asserted as fact.", parent: "RitualEvent" },
  { id: "RitualEvent", label: "RitualEvent", category: "event", cidocMapping: "heritageGraph:RitualEvent", description: "Intentional ritual activity that activates sacred space, invokes deities, and binds social groups" },
  { id: "Sattal", label: "Sattal", category: "tangible", cidocMapping: "heritageGraph:Sattal", description: "Multi-story rest house (3-5 floors) with ritual and social functions", parent: "RestHouse" },
  { id: "SelectionCriterion", label: "SelectionCriterion", category: "tangible", cidocMapping: "heritageGraph:SelectionCriterion", description: "An eligibility criterion a candidate must satisfy to assume the Kumari role. Modelled as explicit subclasses so 'what are the eligibility criteria?' is a subclass query, not free text." },
  { id: "Set", label: "Set", category: "provenance", cidocMapping: "la:Set", description: "CIDOC-CRM/LinkedArt interop class for Yale LUX alignment (not user-contributable)." },
  { id: "Stupa", label: "Stupa", category: "tangible", cidocMapping: "heritageGraph:Stupa", description: "Buddhist dome-shaped reliquary shrine with circumambulation and ritual activation (e.g., Boudhanath, Swayambhunath).", parent: "ReligiousStructure" },
  { id: "SyncreticRelationship", label: "SyncreticRelationship", category: "conceptual", cidocMapping: "heritageGraph:SyncreticRelationship", description: "Formalizes the syncretic equivalence between divine entities across different theological frameworks. Following CIDOC CRM E13, it treats syncretism as a propositional claim with associated epistemic authority and provenance." },
  { id: "Technique", label: "Technique", category: "tangible", cidocMapping: "crm:E29_Design_or_Procedure", description: "Method or craft process used in production or ritual" },
  { id: "Temple", label: "Temple", category: "tangible", cidocMapping: "heritageGraph:Temple", description: "Religious structure characterized by deity enshrinement and ritual activation. Legal designation (e.g. 'Ancient Monument' under Nepal law) is recorded per-instance via a governance assertion, not as a class criterion.", parent: "ReligiousStructure" },
  { id: "ThirtyTwoPerfectionsCriterion", label: "ThirtyTwoPerfectionsCriterion", category: "tangible", cidocMapping: "heritageGraph:ThirtyTwoPerfectionsCriterion", description: "Candidate must exhibit the battis lakshana (thirty-two perfections/auspicious bodily marks).", parent: "SelectionCriterion" },
  { id: "TimeSpan", label: "TimeSpan", category: "spatial", cidocMapping: "crm:E52_Time-Span", description: "Temporal extent of an event or period" },
  { id: "TransferOfCustody", label: "TransferOfCustody", category: "tangible", cidocMapping: "crm:E10_Transfer_of_Custody", description: "Event of transferring responsibility for temple maintenance, ritual performance, or artifact stewardship" },
  { id: "Verification", label: "Verification", category: "tangible", cidocMapping: "heritageGraph:Verification", description: "Process of cross-checking heritage claims against multiple sources", parent: "DocumentationActivity" },
  { id: "WaterStructure", label: "WaterStructure", category: "tangible", cidocMapping: "heritageGraph:WaterStructure", description: "Engineered water supply systems with ritual and civic significance", parent: "ArchitecturalStructure" },
  { id: "ArchitecturalStyle", label: "ArchitecturalStyle", category: "enum", cidocMapping: "heritageGraph:ArchitecturalStyle", description: "A vocabulary of architectural styles for South Asian heritage, mapped to CIDOC E55 Type." },
  { id: "ArchitecturalStyle_Chaitya", label: "Chaitya", category: "enum", cidocMapping: "heritageGraph:ArchitecturalStyle#Chaitya", description: "Buddhist votive shrine style", parent: "ArchitecturalStyle" },
  { id: "ArchitecturalStyle_Dome", label: "Dome", category: "enum", cidocMapping: "heritageGraph:ArchitecturalStyle#Dome", description: "Dome-based style (Mughal/Neo-classical influence)", parent: "ArchitecturalStyle" },
  { id: "ArchitecturalStyle_Pagoda", label: "Pagoda", category: "enum", cidocMapping: "heritageGraph:ArchitecturalStyle#Pagoda", description: "Multi-tiered roof style indigenous to Nepal", parent: "ArchitecturalStyle" },
  { id: "ArchitecturalStyle_Shikhara", label: "Shikhara", category: "enum", cidocMapping: "heritageGraph:ArchitecturalStyle#Shikhara", description: "North Indian spire-shaped style", parent: "ArchitecturalStyle" },
  { id: "ArchitecturalStyle_Stupa", label: "Stupa", category: "enum", cidocMapping: "heritageGraph:ArchitecturalStyle#Stupa", description: "Buddhist dome-shaped reliquary", parent: "ArchitecturalStyle" },
  { id: "ConditionType", label: "ConditionType", category: "enum", cidocMapping: "heritageGraph:ConditionType", description: "Controlled vocabulary for the physical condition of heritage objects and structures." },
  { id: "ConditionType_Damaged", label: "Damaged", category: "enum", cidocMapping: "heritageGraph:ConditionType#Damaged", description: "Partially damaged", parent: "ConditionType" },
  { id: "ConditionType_Good", label: "Good", category: "enum", cidocMapping: "heritageGraph:ConditionType#Good", description: "No significant damage", parent: "ConditionType" },
  { id: "ConditionType_Restored", label: "Restored", category: "enum", cidocMapping: "heritageGraph:ConditionType#Restored", description: "Repaired and stabilized", parent: "ConditionType" },
  { id: "ConditionType_Ruined", label: "Ruined", category: "enum", cidocMapping: "heritageGraph:ConditionType#Ruined", description: "Severely damaged or collapsed", parent: "ConditionType" },
  { id: "CulturalEntityCategory", label: "CulturalEntityCategory", category: "enum", cidocMapping: "heritageGraph:CulturalEntityCategory", description: "Domain category for a high-level cultural entity contribution." },
  { id: "CulturalEntityCategory_artifact", label: "artifact", category: "enum", cidocMapping: "heritageGraph:CulturalEntityCategory#artifact", description: "artifact", parent: "CulturalEntityCategory" },
  { id: "CulturalEntityCategory_document", label: "document", category: "enum", cidocMapping: "heritageGraph:CulturalEntityCategory#document", description: "document", parent: "CulturalEntityCategory" },
  { id: "CulturalEntityCategory_festival", label: "festival", category: "enum", cidocMapping: "heritageGraph:CulturalEntityCategory#festival", description: "festival", parent: "CulturalEntityCategory" },
  { id: "CulturalEntityCategory_monument", label: "monument", category: "enum", cidocMapping: "heritageGraph:CulturalEntityCategory#monument", description: "Monument or built heritage", parent: "CulturalEntityCategory" },
  { id: "CulturalEntityCategory_other", label: "other", category: "enum", cidocMapping: "heritageGraph:CulturalEntityCategory#other", description: "other", parent: "CulturalEntityCategory" },
  { id: "CulturalEntityCategory_ritual", label: "ritual", category: "enum", cidocMapping: "heritageGraph:CulturalEntityCategory#ritual", description: "ritual", parent: "CulturalEntityCategory" },
  { id: "CulturalEntityCategory_tradition", label: "tradition", category: "enum", cidocMapping: "heritageGraph:CulturalEntityCategory#tradition", description: "tradition", parent: "CulturalEntityCategory" },
  { id: "DatePrecision", label: "DatePrecision", category: "enum", cidocMapping: "heritageGraph:DatePrecision", description: "Controlled vocabulary for the temporal precision of recorded heritage dates." },
  { id: "DatePrecision_Century", label: "Century", category: "enum", cidocMapping: "heritageGraph:DatePrecision#Century", description: "Within century range", parent: "DatePrecision" },
  { id: "DatePrecision_Circa", label: "Circa", category: "enum", cidocMapping: "heritageGraph:DatePrecision#Circa", description: "Approximate date", parent: "DatePrecision" },
  { id: "DatePrecision_Decade", label: "Decade", category: "enum", cidocMapping: "heritageGraph:DatePrecision#Decade", description: "Within 10-year range", parent: "DatePrecision" },
  { id: "DatePrecision_Exact", label: "Exact", category: "enum", cidocMapping: "heritageGraph:DatePrecision#Exact", description: "Precise date known", parent: "DatePrecision" },
  { id: "DatePrecision_Year", label: "Year", category: "enum", cidocMapping: "heritageGraph:DatePrecision#Year", description: "Year-level precision only", parent: "DatePrecision" },
  { id: "ExistenceStatus", label: "ExistenceStatus", category: "enum", cidocMapping: "heritageGraph:ExistenceStatus", description: "Controlled vocabulary for whether a heritage structure still exists physically." },
  { id: "ExistenceStatus_Destroyed", label: "Destroyed", category: "enum", cidocMapping: "heritageGraph:ExistenceStatus#Destroyed", description: "Known to have been destroyed; no physical remains", parent: "ExistenceStatus" },
  { id: "ExistenceStatus_Extant", label: "Extant", category: "enum", cidocMapping: "heritageGraph:ExistenceStatus#Extant", description: "Currently exists in physical form", parent: "ExistenceStatus" },
  { id: "ExistenceStatus_Hypothetical", label: "Hypothetical", category: "enum", cidocMapping: "heritageGraph:ExistenceStatus#Hypothetical", description: "Reconstructed or theorized; never physically realized", parent: "ExistenceStatus" },
  { id: "ExistenceStatus_Lost", label: "Lost", category: "enum", cidocMapping: "heritageGraph:ExistenceStatus#Lost", description: "Existence documented but location/remains unknown", parent: "ExistenceStatus" },
  { id: "ExistenceStatus_PartiallyExtant", label: "PartiallyExtant", category: "enum", cidocMapping: "heritageGraph:ExistenceStatus#PartiallyExtant", description: "Fragments or ruins remain", parent: "ExistenceStatus" },
  { id: "ExistenceStatus_Unknown", label: "Unknown", category: "enum", cidocMapping: "heritageGraph:ExistenceStatus#Unknown", description: "Existence status uncertain", parent: "ExistenceStatus" },
  { id: "GuthiType", label: "GuthiType", category: "enum", cidocMapping: "heritageGraph:GuthiType", description: "Controlled vocabulary of Guthi functional types (CRM E55_Type)" },
  { id: "GuthiType_JatraGuthi", label: "JatraGuthi", category: "enum", cidocMapping: "heritageGraph:GuthiType#JatraGuthi", description: "Festival organization trust", parent: "GuthiType" },
  { id: "GuthiType_NashaGuthi", label: "NashaGuthi", category: "enum", cidocMapping: "heritageGraph:GuthiType#NashaGuthi", description: "Music and dance trust", parent: "GuthiType" },
  { id: "GuthiType_PujaGuthi", label: "PujaGuthi", category: "enum", cidocMapping: "heritageGraph:GuthiType#PujaGuthi", description: "Daily worship trust", parent: "GuthiType" },
  { id: "GuthiType_RajGuthi", label: "RajGuthi", category: "enum", cidocMapping: "heritageGraph:GuthiType#RajGuthi", description: "Royal endowment trust", parent: "GuthiType" },
  { id: "GuthiType_SanGuthi", label: "SanGuthi", category: "enum", cidocMapping: "heritageGraph:GuthiType#SanGuthi", description: "Life-cycle ritual trust", parent: "GuthiType" },
  { id: "GuthiType_SanaGuthi", label: "SanaGuthi", category: "enum", cidocMapping: "heritageGraph:GuthiType#SanaGuthi", description: "Agricultural cooperative trust", parent: "GuthiType" },
  { id: "GuthiType_SiGuthi", label: "SiGuthi", category: "enum", cidocMapping: "heritageGraph:GuthiType#SiGuthi", description: "Funeral trust", parent: "GuthiType" },
  { id: "GuthiType_TempleGuthi", label: "TempleGuthi", category: "enum", cidocMapping: "heritageGraph:GuthiType#TempleGuthi", description: "Temple maintenance trust", parent: "GuthiType" },
  { id: "RitualType", label: "RitualType", category: "enum", cidocMapping: "heritageGraph:RitualType", description: "Controlled vocabulary of ritual and festival activity types in Kathmandu Valley living heritage." },
  { id: "RitualType_Abhisheka", label: "Abhisheka", category: "enum", cidocMapping: "heritageGraph:RitualType#Abhisheka", description: "Ritual bathing/anointing of deity", parent: "RitualType" },
  { id: "RitualType_Bhajan", label: "Bhajan", category: "enum", cidocMapping: "heritageGraph:RitualType#Bhajan", description: "Devotional singing ritual", parent: "RitualType" },
  { id: "RitualType_ChariotProcession", label: "ChariotProcession", category: "enum", cidocMapping: "heritageGraph:RitualType#ChariotProcession", description: "Ritual chariot pulling", parent: "RitualType" },
  { id: "RitualType_Circumambulation", label: "Circumambulation", category: "enum", cidocMapping: "heritageGraph:RitualType#Circumambulation", description: "Ritual circular movement around sacred site", parent: "RitualType" },
  { id: "RitualType_DeinstallationRitual", label: "DeinstallationRitual", category: "enum", cidocMapping: "heritageGraph:RitualType#DeinstallationRitual", description: "De-installation/conclusion ritual", parent: "RitualType" },
  { id: "RitualType_Homa", label: "Homa", category: "enum", cidocMapping: "heritageGraph:RitualType#Homa", description: "Fire offering ritual", parent: "RitualType" },
  { id: "RitualType_InstallationRitual", label: "InstallationRitual", category: "enum", cidocMapping: "heritageGraph:RitualType#InstallationRitual", description: "Installation/enshrinement ritual", parent: "RitualType" },
  { id: "RitualType_Jatra", label: "Jatra", category: "enum", cidocMapping: "heritageGraph:RitualType#Jatra", description: "Festival procession ritual", parent: "RitualType" },
  { id: "RitualType_KamyaPuja", label: "KamyaPuja", category: "enum", cidocMapping: "heritageGraph:RitualType#KamyaPuja", description: "Desire-based optional worship", parent: "RitualType" },
  { id: "RitualType_MaskedPerformance", label: "MaskedPerformance", category: "enum", cidocMapping: "heritageGraph:RitualType#MaskedPerformance", description: "Ritual masked dance", parent: "RitualType" },
  { id: "RitualType_NaimittikaPuja", label: "NaimittikaPuja", category: "enum", cidocMapping: "heritageGraph:RitualType#NaimittikaPuja", description: "Occasional/Festival worship", parent: "RitualType" },
  { id: "RitualType_NityaPuja", label: "NityaPuja", category: "enum", cidocMapping: "heritageGraph:RitualType#NityaPuja", description: "Daily mandatory worship", parent: "RitualType" },
  { id: "RitualType_ProcessionRitual", label: "ProcessionRitual", category: "enum", cidocMapping: "heritageGraph:RitualType#ProcessionRitual", description: "Ritual procession/movement", parent: "RitualType" },
  { id: "RitualType_ProcessionalMovement", label: "ProcessionalMovement", category: "enum", cidocMapping: "heritageGraph:RitualType#ProcessionalMovement", description: "General ritual movement between locations", parent: "RitualType" },
  { id: "RitualType_RelicTour", label: "RelicTour", category: "enum", cidocMapping: "heritageGraph:RitualType#RelicTour", description: "Procession with sacred relics between sites", parent: "RitualType" },
  { id: "RitualType_ReturningRitual", label: "ReturningRitual", category: "enum", cidocMapping: "heritageGraph:RitualType#ReturningRitual", description: "Return to normal state ritual", parent: "RitualType" },
  { id: "RitualType_RitualConsecration", label: "RitualConsecration", category: "enum", cidocMapping: "heritageGraph:RitualType#RitualConsecration", description: "Consecration/activation ritual", parent: "RitualType" },
  { id: "RitualType_Vrata", label: "Vrata", category: "enum", cidocMapping: "heritageGraph:RitualType#Vrata", description: "Vow observance ritual", parent: "RitualType" },
  { id: "RitualType_Yagna", label: "Yagna", category: "enum", cidocMapping: "heritageGraph:RitualType#Yagna", description: "Vedic sacrifice ritual", parent: "RitualType" },
  { id: "SyncreticType", label: "SyncreticType", category: "enum", cidocMapping: "heritageGraph:SyncreticType", description: "Controlled vocabulary for kinds of syncretic theological relationships between deities." },
  { id: "SyncreticType_Appropriation", label: "Appropriation", category: "enum", cidocMapping: "heritageGraph:SyncreticType#Appropriation", description: "Deity borrowed from one tradition into another", parent: "SyncreticType" },
  { id: "SyncreticType_Equivalence", label: "Equivalence", category: "enum", cidocMapping: "heritageGraph:SyncreticType#Equivalence", description: "Same deity in different traditions (e.g., Avalokiteshvara = Matsyendranath)", parent: "SyncreticType" },
  { id: "SyncreticType_Fusion", label: "Fusion", category: "enum", cidocMapping: "heritageGraph:SyncreticType#Fusion", description: "Intrinsically syncretic deity merging multiple traditions", parent: "SyncreticType" },
  { id: "SyncreticType_Historical", label: "Historical", category: "enum", cidocMapping: "heritageGraph:SyncreticType#Historical", description: "Gradual syncretism over time", parent: "SyncreticType" },
];

const IS_A_EDGES: OntologyEdge[] = [
  { id: "isa__AgeCriterion__SelectionCriterion", source: "AgeCriterion", target: "SelectionCriterion", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__ArchitecturalStructure__HumanMadeObject", source: "ArchitecturalStructure", target: "HumanMadeObject", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__ArchivalRecord__DataSource", source: "ArchivalRecord", target: "DataSource", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__BuddhistMonument__ArchitecturalStructure", source: "BuddhistMonument", target: "ArchitecturalStructure", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__CasteGroup__Actor", source: "CasteGroup", target: "Actor", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__Chaitya__ReligiousStructure", source: "Chaitya", target: "ReligiousStructure", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__ChariotFestival__Festival", source: "ChariotFestival", target: "Festival", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__DataCustodian__Actor", source: "DataCustodian", target: "Actor", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__DestructionEvent__HistoricalEvent", source: "DestructionEvent", target: "HistoricalEvent", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__Dharmashala__RestHouse", source: "Dharmashala", target: "RestHouse", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__DhungeDhara__WaterStructure", source: "DhungeDhara", target: "WaterStructure", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__FearlessnessAssessment__RitualAssessment", source: "FearlessnessAssessment", target: "RitualAssessment", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__Festival__RitualEvent", source: "Festival", target: "RitualEvent", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__FieldSurveyActivity__DocumentationActivity", source: "FieldSurveyActivity", target: "DocumentationActivity", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__FieldSurveyDataset__DataSource", source: "FieldSurveyDataset", target: "DataSource", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__Guthi__Actor", source: "Guthi", target: "Actor", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__HoroscopeCompatibilityCriterion__SelectionCriterion", source: "HoroscopeCompatibilityCriterion", target: "SelectionCriterion", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__IconographicObject__HumanMadeObject", source: "IconographicObject", target: "HumanMadeObject", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__InformationObject__DataSource", source: "InformationObject", target: "DataSource", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__KumariEnthronementEvent__KumariLifecycleEvent", source: "KumariEnthronementEvent", target: "KumariLifecycleEvent", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__KumariHouse__ReligiousStructure", source: "KumariHouse", target: "ReligiousStructure", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__KumariLifecycleEvent__RitualEvent", source: "KumariLifecycleEvent", target: "RitualEvent", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__KumariRetirementEvent__KumariLifecycleEvent", source: "KumariRetirementEvent", target: "KumariLifecycleEvent", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__KumariSelectionEvent__KumariLifecycleEvent", source: "KumariSelectionEvent", target: "KumariLifecycleEvent", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__LineageCriterion__SelectionCriterion", source: "LineageCriterion", target: "SelectionCriterion", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__LivingGoddessRetirement__RitualEvent", source: "LivingGoddessRetirement", target: "RitualEvent", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__LivingGoddessSelection__RitualEvent", source: "LivingGoddessSelection", target: "RitualEvent", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__MaskedDance__Festival", source: "MaskedDance", target: "Festival", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__Murti__IconographicObject", source: "Murti", target: "IconographicObject", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__OralHistoryInterview__DocumentationActivity", source: "OralHistoryInterview", target: "DocumentationActivity", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__OralHistoryRecording__DataSource", source: "OralHistoryRecording", target: "DataSource", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__Pati__RestHouse", source: "Pati", target: "RestHouse", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__Paubha__IconographicObject", source: "Paubha", target: "IconographicObject", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__Person__Actor", source: "Person", target: "Actor", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__PhysicalIntegrityCriterion__SelectionCriterion", source: "PhysicalIntegrityCriterion", target: "SelectionCriterion", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__Pokhari__WaterStructure", source: "Pokhari", target: "WaterStructure", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__ReligiousStructure__ArchitecturalStructure", source: "ReligiousStructure", target: "ArchitecturalStructure", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__RestHouse__ArchitecturalStructure", source: "RestHouse", target: "ArchitecturalStructure", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__RitualAssessment__RitualEvent", source: "RitualAssessment", target: "RitualEvent", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__Sattal__RestHouse", source: "Sattal", target: "RestHouse", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__Stupa__ReligiousStructure", source: "Stupa", target: "ReligiousStructure", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__Temple__ReligiousStructure", source: "Temple", target: "ReligiousStructure", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__ThirtyTwoPerfectionsCriterion__SelectionCriterion", source: "ThirtyTwoPerfectionsCriterion", target: "SelectionCriterion", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__Verification__DocumentationActivity", source: "Verification", target: "DocumentationActivity", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__WaterStructure__ArchitecturalStructure", source: "WaterStructure", target: "ArchitecturalStructure", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__ArchitecturalStyle_Chaitya__ArchitecturalStyle", source: "ArchitecturalStyle_Chaitya", target: "ArchitecturalStyle", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__ArchitecturalStyle_Dome__ArchitecturalStyle", source: "ArchitecturalStyle_Dome", target: "ArchitecturalStyle", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__ArchitecturalStyle_Pagoda__ArchitecturalStyle", source: "ArchitecturalStyle_Pagoda", target: "ArchitecturalStyle", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__ArchitecturalStyle_Shikhara__ArchitecturalStyle", source: "ArchitecturalStyle_Shikhara", target: "ArchitecturalStyle", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__ArchitecturalStyle_Stupa__ArchitecturalStyle", source: "ArchitecturalStyle_Stupa", target: "ArchitecturalStyle", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__ConditionType_Damaged__ConditionType", source: "ConditionType_Damaged", target: "ConditionType", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__ConditionType_Good__ConditionType", source: "ConditionType_Good", target: "ConditionType", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__ConditionType_Restored__ConditionType", source: "ConditionType_Restored", target: "ConditionType", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__ConditionType_Ruined__ConditionType", source: "ConditionType_Ruined", target: "ConditionType", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__CulturalEntityCategory_artifact__CulturalEntityCategory", source: "CulturalEntityCategory_artifact", target: "CulturalEntityCategory", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__CulturalEntityCategory_document__CulturalEntityCategory", source: "CulturalEntityCategory_document", target: "CulturalEntityCategory", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__CulturalEntityCategory_festival__CulturalEntityCategory", source: "CulturalEntityCategory_festival", target: "CulturalEntityCategory", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__CulturalEntityCategory_monument__CulturalEntityCategory", source: "CulturalEntityCategory_monument", target: "CulturalEntityCategory", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__CulturalEntityCategory_other__CulturalEntityCategory", source: "CulturalEntityCategory_other", target: "CulturalEntityCategory", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__CulturalEntityCategory_ritual__CulturalEntityCategory", source: "CulturalEntityCategory_ritual", target: "CulturalEntityCategory", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__CulturalEntityCategory_tradition__CulturalEntityCategory", source: "CulturalEntityCategory_tradition", target: "CulturalEntityCategory", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__DatePrecision_Century__DatePrecision", source: "DatePrecision_Century", target: "DatePrecision", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__DatePrecision_Circa__DatePrecision", source: "DatePrecision_Circa", target: "DatePrecision", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__DatePrecision_Decade__DatePrecision", source: "DatePrecision_Decade", target: "DatePrecision", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__DatePrecision_Exact__DatePrecision", source: "DatePrecision_Exact", target: "DatePrecision", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__DatePrecision_Year__DatePrecision", source: "DatePrecision_Year", target: "DatePrecision", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__ExistenceStatus_Destroyed__ExistenceStatus", source: "ExistenceStatus_Destroyed", target: "ExistenceStatus", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__ExistenceStatus_Extant__ExistenceStatus", source: "ExistenceStatus_Extant", target: "ExistenceStatus", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__ExistenceStatus_Hypothetical__ExistenceStatus", source: "ExistenceStatus_Hypothetical", target: "ExistenceStatus", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__ExistenceStatus_Lost__ExistenceStatus", source: "ExistenceStatus_Lost", target: "ExistenceStatus", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__ExistenceStatus_PartiallyExtant__ExistenceStatus", source: "ExistenceStatus_PartiallyExtant", target: "ExistenceStatus", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__ExistenceStatus_Unknown__ExistenceStatus", source: "ExistenceStatus_Unknown", target: "ExistenceStatus", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__GuthiType_JatraGuthi__GuthiType", source: "GuthiType_JatraGuthi", target: "GuthiType", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__GuthiType_NashaGuthi__GuthiType", source: "GuthiType_NashaGuthi", target: "GuthiType", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__GuthiType_PujaGuthi__GuthiType", source: "GuthiType_PujaGuthi", target: "GuthiType", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__GuthiType_RajGuthi__GuthiType", source: "GuthiType_RajGuthi", target: "GuthiType", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__GuthiType_SanGuthi__GuthiType", source: "GuthiType_SanGuthi", target: "GuthiType", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__GuthiType_SanaGuthi__GuthiType", source: "GuthiType_SanaGuthi", target: "GuthiType", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__GuthiType_SiGuthi__GuthiType", source: "GuthiType_SiGuthi", target: "GuthiType", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__GuthiType_TempleGuthi__GuthiType", source: "GuthiType_TempleGuthi", target: "GuthiType", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__RitualType_Abhisheka__RitualType", source: "RitualType_Abhisheka", target: "RitualType", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__RitualType_Bhajan__RitualType", source: "RitualType_Bhajan", target: "RitualType", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__RitualType_ChariotProcession__RitualType", source: "RitualType_ChariotProcession", target: "RitualType", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__RitualType_Circumambulation__RitualType", source: "RitualType_Circumambulation", target: "RitualType", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__RitualType_DeinstallationRitual__RitualType", source: "RitualType_DeinstallationRitual", target: "RitualType", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__RitualType_Homa__RitualType", source: "RitualType_Homa", target: "RitualType", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__RitualType_InstallationRitual__RitualType", source: "RitualType_InstallationRitual", target: "RitualType", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__RitualType_Jatra__RitualType", source: "RitualType_Jatra", target: "RitualType", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__RitualType_KamyaPuja__RitualType", source: "RitualType_KamyaPuja", target: "RitualType", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__RitualType_MaskedPerformance__RitualType", source: "RitualType_MaskedPerformance", target: "RitualType", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__RitualType_NaimittikaPuja__RitualType", source: "RitualType_NaimittikaPuja", target: "RitualType", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__RitualType_NityaPuja__RitualType", source: "RitualType_NityaPuja", target: "RitualType", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__RitualType_ProcessionRitual__RitualType", source: "RitualType_ProcessionRitual", target: "RitualType", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__RitualType_ProcessionalMovement__RitualType", source: "RitualType_ProcessionalMovement", target: "RitualType", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__RitualType_RelicTour__RitualType", source: "RitualType_RelicTour", target: "RitualType", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__RitualType_ReturningRitual__RitualType", source: "RitualType_ReturningRitual", target: "RitualType", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__RitualType_RitualConsecration__RitualType", source: "RitualType_RitualConsecration", target: "RitualType", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__RitualType_Vrata__RitualType", source: "RitualType_Vrata", target: "RitualType", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__RitualType_Yagna__RitualType", source: "RitualType_Yagna", target: "RitualType", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__SyncreticType_Appropriation__SyncreticType", source: "SyncreticType_Appropriation", target: "SyncreticType", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__SyncreticType_Equivalence__SyncreticType", source: "SyncreticType_Equivalence", target: "SyncreticType", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__SyncreticType_Fusion__SyncreticType", source: "SyncreticType_Fusion", target: "SyncreticType", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__SyncreticType_Historical__SyncreticType", source: "SyncreticType_Historical", target: "SyncreticType", label: 'is_a', edgeType: 'is_a' },
];

const PROPERTY_EDGES: OntologyEdge[] = [
  { id: "op_0", source: "Activity", target: "Entity", label: "generated", edgeType: 'object_property' },
  { id: "op_1", source: "Activity", target: "Entity", label: "used", edgeType: 'object_property' },
  { id: "op_2", source: "Activity", target: "Agent", label: "was_associated_with", edgeType: 'object_property' },
  { id: "op_3", source: "Activity", target: "Activity", label: "was_influenced_by", edgeType: 'object_property' },
  { id: "op_4", source: "Activity", target: "Agent", label: "was_influenced_by", edgeType: 'object_property' },
  { id: "op_5", source: "Activity", target: "Entity", label: "was_influenced_by", edgeType: 'object_property' },
  { id: "op_6", source: "Activity", target: "Activity", label: "was_informed_by", edgeType: 'object_property' },
  { id: "op_7", source: "Agent", target: "Agent", label: "acted_on_behalf_of", edgeType: 'object_property' },
  { id: "op_8", source: "Agent", target: "Activity", label: "was_influenced_by", edgeType: 'object_property' },
  { id: "op_9", source: "Agent", target: "Agent", label: "was_influenced_by", edgeType: 'object_property' },
  { id: "op_10", source: "Agent", target: "Entity", label: "was_influenced_by", edgeType: 'object_property' },
  { id: "op_11", source: "ArchitecturalElement", target: "ArchitecturalStructure", label: "is_component_of", edgeType: 'object_property' },
  { id: "op_12", source: "ArchitecturalStructure", target: "DestructionEvent", label: "destruction_event", edgeType: 'object_property' },
  { id: "op_13", source: "ArchitecturalStructure", target: "DataSource", label: "documented_in_source", edgeType: 'object_property' },
  { id: "op_14", source: "ArchitecturalStructure", target: "ExistenceStatus", label: "existence_status", edgeType: 'object_property' },
  { id: "op_15", source: "ArchitecturalStructure", target: "ArchitecturalStyle", label: "has_architectural_style", edgeType: 'object_property' },
  { id: "op_16", source: "ArchitecturalStructure", target: "Assertion", label: "has_assertion", edgeType: 'object_property' },
  { id: "op_17", source: "ArchitecturalStructure", target: "ArchitecturalElement", label: "has_component", edgeType: 'object_property' },
  { id: "op_18", source: "ArchitecturalStructure", target: "ConditionAssessment", label: "has_condition_assessment", edgeType: 'object_property' },
  { id: "op_19", source: "ArchitecturalStructure", target: "Place", label: "has_current_location", edgeType: 'object_property' },
  { id: "op_20", source: "ArchitecturalStructure", target: "Place", label: "hypothesized_location", edgeType: 'object_property' },
  { id: "op_21", source: "ArchitecturalStructure", target: "Production", label: "was_produced_by_event", edgeType: 'object_property' },
  { id: "op_22", source: "Assertion", target: "AssertionSubject", label: "asserts_about", edgeType: 'object_property' },
  { id: "op_23", source: "Assertion", target: "Proposition", label: "asserts_proposition", edgeType: 'object_property' },
  { id: "op_24", source: "Assertion", target: "Assertion", label: "supersedes_assertion", edgeType: 'object_property' },
  { id: "op_25", source: "Assertion", target: "Agent", label: "was_attributed_to", edgeType: 'object_property' },
  { id: "op_26", source: "Assertion", target: "Entity", label: "was_derived_from", edgeType: 'object_property' },
  { id: "op_27", source: "Assertion", target: "Activity", label: "was_generated_by", edgeType: 'object_property' },
  { id: "op_28", source: "CalendarSystem", target: "ReligiousTradition", label: "is_primary_for_tradition", edgeType: 'object_property' },
  { id: "op_29", source: "ConditionAssessment", target: "ConditionState", label: "assessed_condition_state", edgeType: 'object_property' },
  { id: "op_30", source: "ConditionAssessment", target: "PhysicalHeritageThing", label: "assessed_object", edgeType: 'object_property' },
  { id: "op_31", source: "ConditionAssessment", target: "Actor", label: "carried_out_by", edgeType: 'object_property' },
  { id: "op_32", source: "ConditionAssessment", target: "TimeSpan", label: "has_timespan", edgeType: 'object_property' },
  { id: "op_33", source: "ConditionState", target: "ConditionType", label: "has_condition_type", edgeType: 'object_property' },
  { id: "op_34", source: "Consecration", target: "Actor", label: "carried_out_by", edgeType: 'object_property' },
  { id: "op_35", source: "Consecration", target: "Murti", label: "consecrated_object", edgeType: 'object_property' },
  { id: "op_36", source: "Consecration", target: "TimeSpan", label: "has_timespan", edgeType: 'object_property' },
  { id: "op_37", source: "Consecration", target: "Deity", label: "makes_deity_present", edgeType: 'object_property' },
  { id: "op_38", source: "Consecration", target: "Place", label: "took_place_at", edgeType: 'object_property' },
  { id: "op_39", source: "CulturalEntity", target: "CulturalEntityCategory", label: "category", edgeType: 'object_property' },
  { id: "op_40", source: "DataSource", target: "Actor", label: "datacite_creator", edgeType: 'object_property' },
  { id: "op_41", source: "DataSource", target: "Actor", label: "datacite_publisher", edgeType: 'object_property' },
  { id: "op_42", source: "DataSource", target: "TimeSpan", label: "publication_timespan", edgeType: 'object_property' },
  { id: "op_43", source: "Deity", target: "ReligiousTradition", label: "has_religious_tradition", edgeType: 'object_property' },
  { id: "op_44", source: "Deity", target: "IconographicObject", label: "is_depicted_in", edgeType: 'object_property' },
  { id: "op_45", source: "Deity", target: "Enshrinement", label: "is_enshrined_through_event", edgeType: 'object_property' },
  { id: "op_46", source: "Deity", target: "RitualEvent", label: "is_invoked_in_ritual", edgeType: 'object_property' },
  { id: "op_47", source: "DestructionEvent", target: "TimeSpan", label: "has_timespan", edgeType: 'object_property' },
  { id: "op_48", source: "DestructionEvent", target: "Place", label: "took_place_at", edgeType: 'object_property' },
  { id: "op_49", source: "DocumentationActivity", target: "AssertionSubject", label: "documents", edgeType: 'object_property' },
  { id: "op_50", source: "DocumentationActivity", target: "Entity", label: "generated", edgeType: 'object_property' },
  { id: "op_51", source: "DocumentationActivity", target: "TimeSpan", label: "has_timespan", edgeType: 'object_property' },
  { id: "op_52", source: "DocumentationActivity", target: "Agent", label: "was_associated_with", edgeType: 'object_property' },
  { id: "op_53", source: "Enshrinement", target: "Actor", label: "carried_out_by", edgeType: 'object_property' },
  { id: "op_54", source: "Enshrinement", target: "Deity", label: "enshrined_deity", edgeType: 'object_property' },
  { id: "op_55", source: "Enshrinement", target: "Temple", label: "enshrined_in_structure", edgeType: 'object_property' },
  { id: "op_56", source: "Enshrinement", target: "TimeSpan", label: "has_timespan", edgeType: 'object_property' },
  { id: "op_57", source: "Entity", target: "Agent", label: "was_attributed_to", edgeType: 'object_property' },
  { id: "op_58", source: "Entity", target: "Entity", label: "was_derived_from", edgeType: 'object_property' },
  { id: "op_59", source: "Entity", target: "Activity", label: "was_generated_by", edgeType: 'object_property' },
  { id: "op_60", source: "Entity", target: "Activity", label: "was_influenced_by", edgeType: 'object_property' },
  { id: "op_61", source: "Entity", target: "Agent", label: "was_influenced_by", edgeType: 'object_property' },
  { id: "op_62", source: "Entity", target: "Entity", label: "was_influenced_by", edgeType: 'object_property' },
  { id: "op_63", source: "Festival", target: "RitualEvent", label: "includes_ritual_event", edgeType: 'object_property' },
  { id: "op_64", source: "Guthi", target: "GuthiType", label: "guthi_type", edgeType: 'object_property' },
  { id: "op_65", source: "Guthi", target: "Person", label: "has_membership", edgeType: 'object_property' },
  { id: "op_66", source: "Guthi", target: "ArchitecturalStructure", label: "holds_custody_of", edgeType: 'object_property' },
  { id: "op_67", source: "Guthi", target: "RitualEvent", label: "performs_ritual", edgeType: 'object_property' },
  { id: "op_68", source: "HeritageAssertion", target: "AssertableEntity", label: "asserts_about_entity", edgeType: 'object_property' },
  { id: "op_69", source: "HeritageAssertion", target: "RitualEvent", label: "asserts_about_event", edgeType: 'object_property' },
  { id: "op_70", source: "HeritageAssertion", target: "Assertion", label: "supersedes_assertion", edgeType: 'object_property' },
  { id: "op_71", source: "HeritageAssertion", target: "Person", label: "was_attributed_to_agent", edgeType: 'object_property' },
  { id: "op_72", source: "HeritageAssertion", target: "DataSource", label: "was_derived_from_source", edgeType: 'object_property' },
  { id: "op_73", source: "HistoricalEvent", target: "ArchitecturalStructure", label: "architectural_structures", edgeType: 'object_property' },
  { id: "op_74", source: "HistoricalEvent", target: "TimeSpan", label: "has_timespan", edgeType: 'object_property' },
  { id: "op_75", source: "HistoricalEvent", target: "RitualEvent", label: "includes_ritual_event", edgeType: 'object_property' },
  { id: "op_76", source: "HistoricalEvent", target: "Place", label: "took_place_at", edgeType: 'object_property' },
  { id: "op_77", source: "HistoricalPeriod", target: "TimeSpan", label: "has_timespan", edgeType: 'object_property' },
  { id: "op_78", source: "HumanMadeObject", target: "ConditionAssessment", label: "has_condition_assessment", edgeType: 'object_property' },
  { id: "op_79", source: "HumanMadeObject", target: "Place", label: "has_current_location", edgeType: 'object_property' },
  { id: "op_80", source: "HumanMadeObject", target: "TransferOfCustody", label: "has_custody_event", edgeType: 'object_property' },
  { id: "op_81", source: "HumanMadeObject", target: "RitualEvent", label: "participates_in_ritual", edgeType: 'object_property' },
  { id: "op_82", source: "HumanMadeObject", target: "DocumentationActivity", label: "was_documented_by", edgeType: 'object_property' },
  { id: "op_83", source: "HumanMadeObject", target: "Production", label: "was_produced_by_event", edgeType: 'object_property' },
  { id: "op_84", source: "IconographicObject", target: "Deity", label: "depicts_deity", edgeType: 'object_property' },
  { id: "op_85", source: "IconographicObject", target: "Place", label: "has_current_location", edgeType: 'object_property' },
  { id: "op_86", source: "IconographicObject", target: "RitualEvent", label: "participates_in_ritual", edgeType: 'object_property' },
  { id: "op_87", source: "IconographicObject", target: "Actor", label: "used_by", edgeType: 'object_property' },
  { id: "op_88", source: "IconographicObject", target: "Production", label: "was_produced_by_event", edgeType: 'object_property' },
  { id: "op_89", source: "InformationObject", target: "AssertionSubject", label: "is_about", edgeType: 'object_property' },
  { id: "op_90", source: "InformationObject", target: "DocumentationActivity", label: "was_documented_by", edgeType: 'object_property' },
  { id: "op_91", source: "InformationObject", target: "Activity", label: "was_generated_by", edgeType: 'object_property' },
  { id: "op_92", source: "KumariEnthronementEvent", target: "KumariTenure", label: "bounds_tenure", edgeType: 'object_property' },
  { id: "op_93", source: "KumariEnthronementEvent", target: "Actor", label: "carried_out_by", edgeType: 'object_property' },
  { id: "op_94", source: "KumariEnthronementEvent", target: "KumariRole", label: "confers_role", edgeType: 'object_property' },
  { id: "op_95", source: "KumariEnthronementEvent", target: "Person", label: "enthroned_person", edgeType: 'object_property' },
  { id: "op_96", source: "KumariEnthronementEvent", target: "Assertion", label: "has_assertion", edgeType: 'object_property' },
  { id: "op_97", source: "KumariEnthronementEvent", target: "TimeSpan", label: "has_timespan", edgeType: 'object_property' },
  { id: "op_98", source: "KumariEnthronementEvent", target: "Place", label: "took_place_at", edgeType: 'object_property' },
  { id: "op_99", source: "KumariEnthronementEvent", target: "DocumentationActivity", label: "was_documented_by", edgeType: 'object_property' },
  { id: "op_100", source: "KumariLifecycleEvent", target: "KumariTenure", label: "bounds_tenure", edgeType: 'object_property' },
  { id: "op_101", source: "KumariRetirementEvent", target: "Actor", label: "carried_out_by", edgeType: 'object_property' },
  { id: "op_102", source: "KumariRetirementEvent", target: "KumariTenure", label: "ended_tenure_of", edgeType: 'object_property' },
  { id: "op_103", source: "KumariRetirementEvent", target: "Assertion", label: "has_assertion", edgeType: 'object_property' },
  { id: "op_104", source: "KumariRetirementEvent", target: "TimeSpan", label: "has_timespan", edgeType: 'object_property' },
  { id: "op_105", source: "KumariRetirementEvent", target: "Actor", label: "performed_by_group", edgeType: 'object_property' },
  { id: "op_106", source: "KumariRetirementEvent", target: "CasteGroup", label: "performed_by_group", edgeType: 'object_property' },
  { id: "op_107", source: "KumariRetirementEvent", target: "Guthi", label: "performed_by_group", edgeType: 'object_property' },
  { id: "op_108", source: "KumariRetirementEvent", target: "Place", label: "took_place_at", edgeType: 'object_property' },
  { id: "op_109", source: "KumariRetirementEvent", target: "DocumentationActivity", label: "was_documented_by", edgeType: 'object_property' },
  { id: "op_110", source: "KumariRole", target: "Deity", label: "role_deity", edgeType: 'object_property' },
  { id: "op_111", source: "KumariSelectionEvent", target: "Actor", label: "carried_out_by", edgeType: 'object_property' },
  { id: "op_112", source: "KumariSelectionEvent", target: "KumariRole", label: "confers_role", edgeType: 'object_property' },
  { id: "op_113", source: "KumariSelectionEvent", target: "Assertion", label: "has_assertion", edgeType: 'object_property' },
  { id: "op_114", source: "KumariSelectionEvent", target: "SelectionCriterion", label: "has_criterion", edgeType: 'object_property' },
  { id: "op_115", source: "KumariSelectionEvent", target: "TimeSpan", label: "has_timespan", edgeType: 'object_property' },
  { id: "op_116", source: "KumariSelectionEvent", target: "KumariTenure", label: "initiated_tenure", edgeType: 'object_property' },
  { id: "op_117", source: "KumariSelectionEvent", target: "Actor", label: "performed_by_group", edgeType: 'object_property' },
  { id: "op_118", source: "KumariSelectionEvent", target: "CasteGroup", label: "performed_by_group", edgeType: 'object_property' },
  { id: "op_119", source: "KumariSelectionEvent", target: "Guthi", label: "performed_by_group", edgeType: 'object_property' },
  { id: "op_120", source: "KumariSelectionEvent", target: "Person", label: "selected_person", edgeType: 'object_property' },
  { id: "op_121", source: "KumariSelectionEvent", target: "Place", label: "took_place_at", edgeType: 'object_property' },
  { id: "op_122", source: "KumariSelectionEvent", target: "DocumentationActivity", label: "was_documented_by", edgeType: 'object_property' },
  { id: "op_123", source: "KumariTenure", target: "KumariRole", label: "assumes_role", edgeType: 'object_property' },
  { id: "op_124", source: "KumariTenure", target: "Deity", label: "embodied_deity", edgeType: 'object_property' },
  { id: "op_125", source: "KumariTenure", target: "KumariEnthronementEvent", label: "enthroned_through", edgeType: 'object_property' },
  { id: "op_126", source: "KumariTenure", target: "Actor", label: "had_participant", edgeType: 'object_property' },
  { id: "op_127", source: "KumariTenure", target: "TimeSpan", label: "has_timespan", edgeType: 'object_property' },
  { id: "op_128", source: "KumariTenure", target: "ArchitecturalStructure", label: "residence_structure", edgeType: 'object_property' },
  { id: "op_129", source: "KumariTenure", target: "KumariRetirementEvent", label: "retired_through", edgeType: 'object_property' },
  { id: "op_130", source: "KumariTenure", target: "KumariSelectionEvent", label: "selected_through", edgeType: 'object_property' },
  { id: "op_131", source: "KumariTenure", target: "Guthi", label: "supported_by_institution", edgeType: 'object_property' },
  { id: "op_132", source: "KumariTenure", target: "DocumentationActivity", label: "was_documented_by", edgeType: 'object_property' },
  { id: "op_133", source: "LivingGoddessRetirement", target: "Actor", label: "carried_out_by", edgeType: 'object_property' },
  { id: "op_134", source: "LivingGoddessRetirement", target: "KumariTenure", label: "ended_tenure_of", edgeType: 'object_property' },
  { id: "op_135", source: "LivingGoddessRetirement", target: "HeritageAssertion", label: "has_provenance_assertion", edgeType: 'object_property' },
  { id: "op_136", source: "LivingGoddessRetirement", target: "TimeSpan", label: "has_timespan", edgeType: 'object_property' },
  { id: "op_137", source: "LivingGoddessRetirement", target: "Actor", label: "performed_by_group", edgeType: 'object_property' },
  { id: "op_138", source: "LivingGoddessRetirement", target: "CasteGroup", label: "performed_by_group", edgeType: 'object_property' },
  { id: "op_139", source: "LivingGoddessRetirement", target: "Guthi", label: "performed_by_group", edgeType: 'object_property' },
  { id: "op_140", source: "LivingGoddessRetirement", target: "Place", label: "took_place_at", edgeType: 'object_property' },
  { id: "op_141", source: "LivingGoddessRetirement", target: "DocumentationActivity", label: "was_documented_by", edgeType: 'object_property' },
  { id: "op_142", source: "LivingGoddessSelection", target: "Actor", label: "carried_out_by", edgeType: 'object_property' },
  { id: "op_143", source: "LivingGoddessSelection", target: "HeritageAssertion", label: "has_provenance_assertion", edgeType: 'object_property' },
  { id: "op_144", source: "LivingGoddessSelection", target: "TimeSpan", label: "has_timespan", edgeType: 'object_property' },
  { id: "op_145", source: "LivingGoddessSelection", target: "KumariTenure", label: "initiated_tenure", edgeType: 'object_property' },
  { id: "op_146", source: "LivingGoddessSelection", target: "Actor", label: "performed_by_group", edgeType: 'object_property' },
  { id: "op_147", source: "LivingGoddessSelection", target: "CasteGroup", label: "performed_by_group", edgeType: 'object_property' },
  { id: "op_148", source: "LivingGoddessSelection", target: "Guthi", label: "performed_by_group", edgeType: 'object_property' },
  { id: "op_149", source: "LivingGoddessSelection", target: "Person", label: "selected_person", edgeType: 'object_property' },
  { id: "op_150", source: "LivingGoddessSelection", target: "Place", label: "took_place_at", edgeType: 'object_property' },
  { id: "op_151", source: "LivingGoddessSelection", target: "DocumentationActivity", label: "was_documented_by", edgeType: 'object_property' },
  { id: "op_152", source: "LivingGoddessTenure", target: "Deity", label: "embodied_deity", edgeType: 'object_property' },
  { id: "op_153", source: "LivingGoddessTenure", target: "Actor", label: "had_participant", edgeType: 'object_property' },
  { id: "op_154", source: "LivingGoddessTenure", target: "LivingGoddessRetirement", label: "has_retirement_event", edgeType: 'object_property' },
  { id: "op_155", source: "LivingGoddessTenure", target: "TimeSpan", label: "has_timespan", edgeType: 'object_property' },
  { id: "op_156", source: "LivingGoddessTenure", target: "ArchitecturalStructure", label: "residence_structure", edgeType: 'object_property' },
  { id: "op_157", source: "LivingGoddessTenure", target: "Guthi", label: "supported_by_institution", edgeType: 'object_property' },
  { id: "op_158", source: "LivingGoddessTenure", target: "DocumentationActivity", label: "was_documented_by", edgeType: 'object_property' },
  { id: "op_159", source: "Murti", target: "Consecration", label: "consecrated_by_event", edgeType: 'object_property' },
  { id: "op_160", source: "Murti", target: "Deity", label: "is_about_deity", edgeType: 'object_property' },
  { id: "op_161", source: "Person", target: "TimeSpan", label: "birth_timespan", edgeType: 'object_property' },
  { id: "op_162", source: "Person", target: "RitualEvent", label: "carried_out_activity", edgeType: 'object_property' },
  { id: "op_163", source: "Person", target: "TimeSpan", label: "death_timespan", edgeType: 'object_property' },
  { id: "op_164", source: "Person", target: "Guthi", label: "member_of_group", edgeType: 'object_property' },
  { id: "op_165", source: "Place", target: "ArchitecturalStructure", label: "contains_structure", edgeType: 'object_property' },
  { id: "op_166", source: "Production", target: "Actor", label: "carried_out_by", edgeType: 'object_property' },
  { id: "op_167", source: "Production", target: "Actor", label: "commissioned_by", edgeType: 'object_property' },
  { id: "op_168", source: "Production", target: "Assertion", label: "has_assertion", edgeType: 'object_property' },
  { id: "op_169", source: "Production", target: "TimeSpan", label: "has_timespan", edgeType: 'object_property' },
  { id: "op_170", source: "Production", target: "PhysicalHeritageThing", label: "produced_object", edgeType: 'object_property' },
  { id: "op_171", source: "Production", target: "Place", label: "took_place_at", edgeType: 'object_property' },
  { id: "op_172", source: "Production", target: "Technique", label: "used_technique", edgeType: 'object_property' },
  { id: "op_173", source: "Production", target: "DocumentationActivity", label: "was_documented_by", edgeType: 'object_property' },
  { id: "op_174", source: "Proposition", target: "AssertionSubject", label: "proposition_object_entity", edgeType: 'object_property' },
  { id: "op_175", source: "Proposition", target: "AssertionSubject", label: "proposition_subject", edgeType: 'object_property' },
  { id: "op_176", source: "RitualAssessment", target: "Person", label: "assesses_candidate", edgeType: 'object_property' },
  { id: "op_177", source: "RitualAssessment", target: "Actor", label: "carried_out_by", edgeType: 'object_property' },
  { id: "op_178", source: "RitualAssessment", target: "Assertion", label: "has_assertion", edgeType: 'object_property' },
  { id: "op_179", source: "RitualAssessment", target: "TimeSpan", label: "has_timespan", edgeType: 'object_property' },
  { id: "op_180", source: "RitualAssessment", target: "KumariSelectionEvent", label: "part_of_selection", edgeType: 'object_property' },
  { id: "op_181", source: "RitualAssessment", target: "DocumentationActivity", label: "was_documented_by", edgeType: 'object_property' },
  { id: "op_182", source: "RitualEvent", target: "Actor", label: "carried_out_by", edgeType: 'object_property' },
  { id: "op_183", source: "RitualEvent", target: "Place", label: "end_place", edgeType: 'object_property' },
  { id: "op_184", source: "RitualEvent", target: "Assertion", label: "has_assertion", edgeType: 'object_property' },
  { id: "op_185", source: "RitualEvent", target: "TimeSpan", label: "has_timespan", edgeType: 'object_property' },
  { id: "op_186", source: "RitualEvent", target: "Deity", label: "invokes_deity", edgeType: 'object_property' },
  { id: "op_187", source: "RitualEvent", target: "Festival", label: "is_part_of_festival", edgeType: 'object_property' },
  { id: "op_188", source: "RitualEvent", target: "Guthi", label: "managed_by_guthi", edgeType: 'object_property' },
  { id: "op_189", source: "RitualEvent", target: "RitualEvent", label: "occurs_after", edgeType: 'object_property' },
  { id: "op_190", source: "RitualEvent", target: "RitualEvent", label: "occurs_before", edgeType: 'object_property' },
  { id: "op_191", source: "RitualEvent", target: "Actor", label: "performed_by_group", edgeType: 'object_property' },
  { id: "op_192", source: "RitualEvent", target: "CasteGroup", label: "performed_by_group", edgeType: 'object_property' },
  { id: "op_193", source: "RitualEvent", target: "Guthi", label: "performed_by_group", edgeType: 'object_property' },
  { id: "op_194", source: "RitualEvent", target: "PhysicalHeritageThing", label: "ritual_on_structure", edgeType: 'object_property' },
  { id: "op_195", source: "RitualEvent", target: "RitualType", label: "ritual_type", edgeType: 'object_property' },
  { id: "op_196", source: "RitualEvent", target: "Place", label: "route_places", edgeType: 'object_property' },
  { id: "op_197", source: "RitualEvent", target: "Place", label: "start_place", edgeType: 'object_property' },
  { id: "op_198", source: "RitualEvent", target: "Material", label: "used_materials", edgeType: 'object_property' },
  { id: "op_199", source: "RitualEvent", target: "DocumentationActivity", label: "was_documented_by", edgeType: 'object_property' },
  { id: "op_200", source: "SyncreticRelationship", target: "Deity", label: "assigned_equivalent", edgeType: 'object_property' },
  { id: "op_201", source: "SyncreticRelationship", target: "Deity", label: "assigned_to_deity", edgeType: 'object_property' },
  { id: "op_202", source: "SyncreticRelationship", target: "DataSource", label: "documented_in_source", edgeType: 'object_property' },
  { id: "op_203", source: "SyncreticRelationship", target: "SyncreticType", label: "syncretic_type", edgeType: 'object_property' },
  { id: "op_204", source: "SyncreticRelationship", target: "Entity", label: "used", edgeType: 'object_property' },
  { id: "op_205", source: "SyncreticRelationship", target: "DocumentationActivity", label: "was_documented_by", edgeType: 'object_property' },
  { id: "op_206", source: "Temple", target: "Enshrinement", label: "enshrines_deity_through_event", edgeType: 'object_property' },
  { id: "op_207", source: "Temple", target: "ArchitecturalStyle", label: "has_architectural_style", edgeType: 'object_property' },
  { id: "op_208", source: "TimeSpan", target: "CalendarSystem", label: "calendar_system", edgeType: 'object_property' },
  { id: "op_209", source: "TimeSpan", target: "DatePrecision", label: "date_precision", edgeType: 'object_property' },
  { id: "op_210", source: "TransferOfCustody", target: "TimeSpan", label: "has_timespan", edgeType: 'object_property' },
  { id: "op_211", source: "TransferOfCustody", target: "Place", label: "took_place_at", edgeType: 'object_property' },
  { id: "op_212", source: "TransferOfCustody", target: "Actor", label: "transferred_from_actor", edgeType: 'object_property' },
  { id: "op_213", source: "TransferOfCustody", target: "PhysicalHeritageThing", label: "transferred_object", edgeType: 'object_property' },
  { id: "op_214", source: "TransferOfCustody", target: "Actor", label: "transferred_to_actor", edgeType: 'object_property' },
  { id: "op_215", source: "TransferOfCustody", target: "Guthi", label: "transferred_to_guthi", edgeType: 'object_property' },
  { id: "op_216", source: "Verification", target: "Assertion", label: "verified_assertion", edgeType: 'object_property' },
  { id: "op_217", source: "Verification", target: "Person", label: "verified_by_expert", edgeType: 'object_property' },
];

export function getOntologyGraphData(): OntologyGraphData {
  return { nodes: NODES, edges: [...IS_A_EDGES, ...PROPERTY_EDGES] };
}

export function getNodeById(id: string): OntologyNode | undefined {
  return NODES.find((n) => n.id === id);
}

export function getNodesByCategory(c: OntologyCategory): OntologyNode[] {
  return NODES.filter((n) => n.category === c);
}

export function getEdgesForNode(nodeId: string): OntologyEdge[] {
  return [...IS_A_EDGES, ...PROPERTY_EDGES].filter(
    (e) => e.source === nodeId || e.target === nodeId,
  );
}

export function getOntologyStats() {
  const data = getOntologyGraphData();
  const hgNodes = data.nodes.filter((n) => n.category !== 'external');
  return {
    totalClasses: hgNodes.length,
    objectProperties: data.edges.filter((e) => e.edgeType === 'object_property').length,
    hierarchyEdges: data.edges.filter((e) => e.edgeType === 'is_a').length,
    categories: new Set(data.nodes.map((n) => n.category)).size,
    externalClasses: data.nodes.filter((n) => n.category === 'external').length,
    enumMembers: data.nodes.filter((n) => n.parent?.includes('Enum')).length,
  };
}
