// AUTO-GENERATED — do not edit by hand.
// Source:  ontology/HeritageGraph.yaml + tools/ui-vizmap.yaml
// Regen:   python3 tools/gen_heritage_viz_config.py  (or: make ontology)
// Hash:    926fcfd1486d5def
//
// Cytoscape schema graph (/graphview → Ontology tab).

export type OntologyCategory =
  | 'tangible'
  | 'conceptual'
  | 'event'
  | 'social'
  | 'spatial'
  | 'provenance'
  | 'kumari'
  | 'enum'
  | 'external';

export interface OntologyNode {
  id: string;
  label: string;
  category: OntologyCategory;
  cidocMapping: string;
  description: string;
  parent?: string;
}

export interface OntologyEdge {
  id: string;
  source: string;
  target: string;
  label: string;
  edgeType: 'is_a' | 'object_property';
}

export interface OntologyGraphData {
  nodes: OntologyNode[];
  edges: OntologyEdge[];
}

export const CATEGORY_COLORS: Record<
  OntologyCategory,
  { bg: string; border: string; text: string; label: string }
> = {
  tangible: { bg: "#3b82f6", border: "#2563eb", text: "#fff", label: "Tangible Heritage" },
  conceptual: { bg: "#8b5cf6", border: "#7c3aed", text: "#fff", label: "Conceptual Entities" },
  event: { bg: "#f59e0b", border: "#d97706", text: "#fff", label: "Events" },
  social: { bg: "#10b981", border: "#059669", text: "#fff", label: "Social / Actors" },
  spatial: { bg: "#06b6d4", border: "#0891b2", text: "#fff", label: "Spatiotemporal" },
  provenance: { bg: "#ec4899", border: "#db2777", text: "#fff", label: "Provenance" },
  kumari: { bg: "#ef4444", border: "#dc2626", text: "#fff", label: "Living Goddess" },
  enum: { bg: "#94a3b8", border: "#64748b", text: "#fff", label: "Enumerations" },
  external: { bg: "#78716c", border: "#57534e", text: "#fff", label: "External (CRM/AAT)" },
};

const NODES: OntologyNode[] = [
  { id: "Acquisition", label: "Acquisition", category: "tangible", cidocMapping: "crm:E8_Acquisition", description: "CIDOC-CRM/LinkedArt interop class for Yale LUX alignment (not user-contributable)." },
  { id: "Actor", label: "Actor", category: "tangible", cidocMapping: "crm:E39_Actor", description: "General actor (person or group) responsible for events" },
  { id: "ArchitecturalElement", label: "ArchitecturalElement", category: "tangible", cidocMapping: "crm:E25_Architectural_Element", description: "Carved or constructed component of an architectural structure (e.g., Gajur, Torana, Tundal)" },
  { id: "ArchitecturalStructure", label: "ArchitecturalStructure", category: "tangible", cidocMapping: "heritageGraph:ArchitecturalStructure", description: "Physical structures built for religious, social, or civic purposes. Links to events of production, use, custody, and documentation.", parent: "HumanMadeObject" },
  { id: "ArchivalRecord", label: "ArchivalRecord", category: "tangible", cidocMapping: "heritageGraph:ArchivalRecord", description: "Government or institutional administrative record", parent: "DataSource" },
  { id: "AssertableEntity", label: "AssertableEntity", category: "tangible", cidocMapping: "crminf:E1_Entity", description: "Any entity that can be the subject of a heritage assertion" },
  { id: "AttributeAssignment", label: "AttributeAssignment", category: "tangible", cidocMapping: "crm:E13_Attribute_Assignment", description: "CIDOC-CRM/LinkedArt interop class for Yale LUX alignment (not user-contributable)." },
  { id: "BeginningOfExistence", label: "BeginningOfExistence", category: "tangible", cidocMapping: "crm:E63_Beginning_of_Existence", description: "CIDOC-CRM/LinkedArt interop class for Yale LUX alignment (not user-contributable)." },
  { id: "Birth", label: "Birth", category: "tangible", cidocMapping: "crm:E67_Birth", description: "CIDOC-CRM/LinkedArt interop class for Yale LUX alignment (not user-contributable)." },
  { id: "BuddhistMonument", label: "BuddhistMonument", category: "tangible", cidocMapping: "heritageGraph:BuddhistMonument", description: "Buddhist sacred structure (Stupa, Chaitya) with circumambulation and ritual activation patterns", parent: "ArchitecturalStructure" },
  { id: "CalendarSystem", label: "CalendarSystem", category: "tangible", cidocMapping: "time:Calendar", description: "Calendar reckoning system with conversion rules for multi-calendar temporal reasoning" },
  { id: "CasteGroup", label: "CasteGroup", category: "social", cidocMapping: "heritageGraph:CasteGroup", description: "Hereditary social group (Jati) with specific ritual roles and occupational duties" },
  { id: "Chaitya", label: "Chaitya", category: "tangible", cidocMapping: "heritageGraph:Chaitya", description: "Buddhist votive shrine or prayer hall", parent: "BuddhistMonument" },
  { id: "ChariotFestival", label: "ChariotFestival", category: "event", cidocMapping: "heritageGraph:ChariotFestival", description: "Festival involving ceremonial chariot procession (e.g., Rato Machhindranath Jatra)", parent: "Festival" },
  { id: "ConditionAssessment", label: "ConditionAssessment", category: "tangible", cidocMapping: "crm:E14_Condition_Assessment", description: "Event of evaluating the physical state of a heritage object or structure" },
  { id: "ConditionState", label: "ConditionState", category: "tangible", cidocMapping: "crm:E3_Condition_State", description: "A physical condition state of a heritage object" },
  { id: "Consecration", label: "Consecration", category: "event", cidocMapping: "heritageGraph:Consecration", description: "Ritual event that transforms an object into a sacred vessel (e.g., Prana Pratistha for Murti)" },
  { id: "Container", label: "Container", category: "tangible", cidocMapping: "Container", description: "Root container for cultural heritage data instances" },
  { id: "CulturalEntity", label: "CulturalEntity", category: "tangible", cidocMapping: "heritageGraph:CulturalEntity", description: "High-level cultural contribution (monuments, festivals, rituals, traditions, artifacts) for the heritage_data review workflow." },
  { id: "CuratedHolding", label: "CuratedHolding", category: "tangible", cidocMapping: "crm:E78_Curated_Holding", description: "CIDOC-CRM/LinkedArt interop class for Yale LUX alignment (not user-contributable)." },
  { id: "CurationActivity", label: "CurationActivity", category: "event", cidocMapping: "crm:E87_Curation_Activity", description: "CIDOC-CRM/LinkedArt interop class for Yale LUX alignment (not user-contributable)." },
  { id: "Currency", label: "Currency", category: "tangible", cidocMapping: "crm:E98_Currency", description: "CIDOC-CRM/LinkedArt interop class for Yale LUX alignment (not user-contributable)." },
  { id: "DataCustodian", label: "DataCustodian", category: "tangible", cidocMapping: "prov:Agent", description: "Institution or person currently stewarding heritage data" },
  { id: "DataSource", label: "DataSource", category: "tangible", cidocMapping: "heritageGraph:DataSource", description: "Original source from which heritage information was derived" },
  { id: "Death", label: "Death", category: "tangible", cidocMapping: "crm:E69_Death", description: "CIDOC-CRM/LinkedArt interop class for Yale LUX alignment (not user-contributable)." },
  { id: "Deity", label: "Deity", category: "conceptual", cidocMapping: "crm:E28_Conceptual_Object", description: "Divine conceptual entity in Hindu, Buddhist, or syncretic traditions. Distinct from physical representations (Murti) and ritual presences." },
  { id: "DestructionEvent", label: "DestructionEvent", category: "event", cidocMapping: "crm:E6_Destruction", description: "Event that destroyed or damaged a structure.", parent: "HistoricalEvent" },
  { id: "Dharmashala", label: "Dharmashala", category: "tangible", cidocMapping: "heritageGraph:Dharmashala", description: "Pilgrim lodge operated by a Guthi organization", parent: "RestHouse" },
  { id: "DhungeDhara", label: "DhungeDhara", category: "tangible", cidocMapping: "heritageGraph:DhungeDhara", description: "Stone spout (hiti) with carved imagery, used for ritual bathing and daily water supply", parent: "WaterStructure" },
  { id: "DigitalObject", label: "DigitalObject", category: "tangible", cidocMapping: "crmdig:D1_Digital_Object", description: "CIDOC-CRM/LinkedArt interop class for Yale LUX alignment (not user-contributable)." },
  { id: "Dimension", label: "Dimension", category: "tangible", cidocMapping: "crm:E54_Dimension", description: "CIDOC-CRM/LinkedArt interop class for Yale LUX alignment (not user-contributable)." },
  { id: "Dissolution", label: "Dissolution", category: "tangible", cidocMapping: "crm:E68_Dissolution", description: "CIDOC-CRM/LinkedArt interop class for Yale LUX alignment (not user-contributable)." },
  { id: "DocumentationActivity", label: "DocumentationActivity", category: "event", cidocMapping: "heritageGraph:DocumentationActivity", description: "The intellectual or technical process of recording information about a heritage entity, aligning CIDOC E13 (Attribute Assignment) with PROV-O Activity." },
  { id: "Encounter", label: "Encounter", category: "tangible", cidocMapping: "crmsci:S19_Encounter_Event", description: "CIDOC-CRM/LinkedArt interop class for Yale LUX alignment (not user-contributable)." },
  { id: "EndOfExistence", label: "EndOfExistence", category: "tangible", cidocMapping: "crm:E64_End_of_Existence", description: "CIDOC-CRM/LinkedArt interop class for Yale LUX alignment (not user-contributable)." },
  { id: "Enshrinement", label: "Enshrinement", category: "event", cidocMapping: "heritageGraph:Enshrinement", description: "Event of installing a deity's murti or symbol within a temple sanctum" },
  { id: "Festival", label: "Festival", category: "event", cidocMapping: "heritageGraph:Festival", description: "Large-scale community ritual event (Jatra) involving processions, music, and collective participation", parent: "RitualEvent" },
  { id: "FieldSurveyActivity", label: "FieldSurveyActivity", category: "event", cidocMapping: "crmsci:S4_Observation", description: "The activity of measuring, photographing, or assessing a site in person.", parent: "DocumentationActivity" },
  { id: "FieldSurveyDataset", label: "FieldSurveyDataset", category: "tangible", cidocMapping: "crm:E31_Document", description: "The structured data or report resulting from a field survey.", parent: "DataSource" },
  { id: "Formation", label: "Formation", category: "tangible", cidocMapping: "crm:E66_Formation", description: "CIDOC-CRM/LinkedArt interop class for Yale LUX alignment (not user-contributable)." },
  { id: "Group", label: "Group", category: "social", cidocMapping: "crm:E74_Group", description: "CIDOC-CRM/LinkedArt interop class for Yale LUX alignment (not user-contributable)." },
  { id: "Guthi", label: "Guthi", category: "social", cidocMapping: "heritageGraph:Guthi", description: "Endowed trust organization unique to Nepal, managing temples, rituals, and land through hereditary or voluntary membership" },
  { id: "HeritageAssertion", label: "HeritageAssertion", category: "tangible", cidocMapping: "crminf:I2_Belief", description: "A single factual claim about a heritage entity, with explicit source, author, date, and confidence" },
  { id: "HistoricalEvent", label: "HistoricalEvent", category: "event", cidocMapping: "crm:E5_Event", description: "Major event affecting heritage structures or ritual life (earthquake, epidemic, political transition, fire, flood)." },
  { id: "HistoricalPeriod", label: "HistoricalPeriod", category: "spatial", cidocMapping: "heritageGraph:HistoricalPeriod", description: "A named, time-bounded historical period of Nepal (e.g., Lichhavi, Malla, Shah). A temporal frame within which heritage entities and events are situated — distinct from a single HistoricalEvent." },
  { id: "HumanMadeObject", label: "HumanMadeObject", category: "tangible", cidocMapping: "crm:E22_Human-Made_Object", description: "Physical objects created by human activity" },
  { id: "IconographicObject", label: "IconographicObject", category: "tangible", cidocMapping: "heritageGraph:IconographicObject", description: "Sacred visual art objects that depict or embody deities through iconographic conventions", parent: "HumanMadeObject" },
  { id: "Identifier", label: "Identifier", category: "tangible", cidocMapping: "crm:E42_Identifier", description: "CIDOC-CRM/LinkedArt interop class for Yale LUX alignment (not user-contributable)." },
  { id: "InformationObject", label: "InformationObject", category: "provenance", cidocMapping: "heritageGraph:InformationObject", description: "A recorded piece of information about heritage", parent: "DataSource" },
  { id: "Inscription", label: "Inscription", category: "tangible", cidocMapping: "crm:E34_Inscription", description: "CIDOC-CRM/LinkedArt interop class for Yale LUX alignment (not user-contributable)." },
  { id: "Language", label: "Language", category: "tangible", cidocMapping: "crm:E56_Language", description: "CIDOC-CRM/LinkedArt interop class for Yale LUX alignment (not user-contributable)." },
  { id: "LegalObject", label: "LegalObject", category: "tangible", cidocMapping: "crm:E72_Legal_Object", description: "CIDOC-CRM/LinkedArt interop class for Yale LUX alignment (not user-contributable)." },
  { id: "LinguisticObject", label: "LinguisticObject", category: "tangible", cidocMapping: "crm:E33_Linguistic_Object", description: "CIDOC-CRM/LinkedArt interop class for Yale LUX alignment (not user-contributable)." },
  { id: "LivingGoddessRetirement", label: "LivingGoddessRetirement", category: "kumari", cidocMapping: "heritageGraph:LivingGoddessRetirement", description: "Ritual or administrative event that formally ends a Living Goddess tenure, marking the person's return to secular status. Common triggers include first menstruation, injury causing blood loss, or serious illness. This event terminates the divine embodiment and restores the girl to ordinary status.", parent: "RitualEvent" },
  { id: "LivingGoddessSelection", label: "LivingGoddessSelection", category: "kumari", cidocMapping: "heritageGraph:LivingGoddessSelection", description: "Tantric ritual process of selecting a new Living Goddess from eligible candidates. Involves examination of 32 auspicious physical marks (lakshana), horoscope matching with the city and ruling authority, and tests of fearlessness (e.g., remaining calm among buffalo heads and masked dancers in darkness). Performed by committee of Vajracharya priests, royal priest (Raj Jyotish), and astrologer.", parent: "RitualEvent" },
  { id: "LivingGoddessTenure", label: "LivingGoddessTenure", category: "kumari", cidocMapping: "crm:E4_Period", description: "Time-bounded role where a person embodies a deity as Living Goddess (Kumari), residing at a specific god-house and supported by religious institutions. This class captures the unique Nepali tradition of living deity embodiment in young girls selected from Buddhist Shakya/Vajracharya families." },
  { id: "MaskedDance", label: "MaskedDance", category: "event", cidocMapping: "heritageGraph:MaskedDance", description: "Festival featuring masked dancers embodying deities (e.g., Kartik Naach)", parent: "Festival" },
  { id: "Material", label: "Material", category: "tangible", cidocMapping: "crm:E57_Material", description: "Physical substance used in construction or crafting" },
  { id: "Measurement", label: "Measurement", category: "tangible", cidocMapping: "crm:E16_Measurement", description: "CIDOC-CRM/LinkedArt interop class for Yale LUX alignment (not user-contributable)." },
  { id: "MeasurementUnit", label: "MeasurementUnit", category: "tangible", cidocMapping: "crm:E58_Measurement_Unit", description: "CIDOC-CRM/LinkedArt interop class for Yale LUX alignment (not user-contributable)." },
  { id: "Metadata", label: "Metadata", category: "tangible", cidocMapping: "Metadata", description: "Dataset metadata information" },
  { id: "Modification", label: "Modification", category: "tangible", cidocMapping: "crm:E11_Modification", description: "CIDOC-CRM/LinkedArt interop class for Yale LUX alignment (not user-contributable)." },
  { id: "MonetaryAmount", label: "MonetaryAmount", category: "tangible", cidocMapping: "crm:E97_Monetary_Amount", description: "CIDOC-CRM/LinkedArt interop class for Yale LUX alignment (not user-contributable)." },
  { id: "Move", label: "Move", category: "tangible", cidocMapping: "crm:E9_Move", description: "CIDOC-CRM/LinkedArt interop class for Yale LUX alignment (not user-contributable)." },
  { id: "Murti", label: "Murti", category: "tangible", cidocMapping: "heritageGraph:Murti", description: "Consecrated statue of a deity, ritually activated to serve as divine presence (not merely depiction)", parent: "IconographicObject" },
  { id: "Name", label: "Name", category: "tangible", cidocMapping: "crm:E33_E41_Linguistic_Appellation", description: "CIDOC-CRM/LinkedArt interop class for Yale LUX alignment (not user-contributable)." },
  { id: "OralHistoryInterview", label: "OralHistoryInterview", category: "tangible", cidocMapping: "crm:E65_Creation", description: "The interaction event between a researcher and a knowledge holder.", parent: "DocumentationActivity" },
  { id: "OralHistoryRecording", label: "OralHistoryRecording", category: "tangible", cidocMapping: "crm:E33_Linguistic_Object", description: "The recording or transcript of an oral history interview.", parent: "DataSource" },
  { id: "Pati", label: "Pati", category: "tangible", cidocMapping: "heritageGraph:Pati", description: "Open-air pavilion for resting travelers", parent: "RestHouse" },
  { id: "Paubha", label: "Paubha", category: "tangible", cidocMapping: "heritageGraph:Paubha", description: "Traditional Newari scroll painting (thangka) with mandala and deity iconography", parent: "IconographicObject" },
  { id: "Period", label: "Period", category: "tangible", cidocMapping: "crm:E4_Period", description: "CIDOC-CRM/LinkedArt interop class for Yale LUX alignment (not user-contributable)." },
  { id: "Person", label: "Person", category: "social", cidocMapping: "crm:E21_Person", description: "Individual person who performs, commissions, documents, or verifies heritage activities" },
  { id: "PhysicalHeritageThing", label: "PhysicalHeritageThing", category: "tangible", cidocMapping: "heritageGraph:PhysicalHeritageThing", description: "PhysicalHeritageThing" },
  { id: "Place", label: "Place", category: "spatial", cidocMapping: "crm:E53_Place", description: "Defined geographic location where events occur and structures exist" },
  { id: "Pokhari", label: "Pokhari", category: "tangible", cidocMapping: "heritageGraph:Pokhari", description: "Pond or tank for water storage, ritual bathing, and ecological management", parent: "WaterStructure" },
  { id: "Production", label: "Production", category: "event", cidocMapping: "crm:E12_Production", description: "Event of creating an architectural structure, murti, or paubha" },
  { id: "PropositionalObject", label: "PropositionalObject", category: "tangible", cidocMapping: "crm:E89_Propositional_Object", description: "CIDOC-CRM/LinkedArt interop class for Yale LUX alignment (not user-contributable)." },
  { id: "ProvenanceActivity", label: "ProvenanceActivity", category: "event", cidocMapping: "crm:E7_Activity", description: "CIDOC-CRM/LinkedArt interop class for Yale LUX alignment (not user-contributable)." },
  { id: "ReligiousTradition", label: "ReligiousTradition", category: "conceptual", cidocMapping: "crm:E55_Type", description: "Religious or philosophical tradition (e.g., Hindu, Buddhist, Syncretic)" },
  { id: "RestHouse", label: "RestHouse", category: "tangible", cidocMapping: "heritageGraph:RestHouse", description: "Community structures for travelers and pilgrims, maintained by Guthi organizations", parent: "ArchitecturalStructure" },
  { id: "Right", label: "Right", category: "tangible", cidocMapping: "crm:E30_Right", description: "CIDOC-CRM/LinkedArt interop class for Yale LUX alignment (not user-contributable)." },
  { id: "RitualEvent", label: "RitualEvent", category: "event", cidocMapping: "heritageGraph:RitualEvent", description: "Intentional ritual activity that activates sacred space, invokes deities, and binds social groups" },
  { id: "Sattal", label: "Sattal", category: "tangible", cidocMapping: "heritageGraph:Sattal", description: "Multi-story rest house (3-5 floors) with ritual and social functions", parent: "RestHouse" },
  { id: "Set", label: "Set", category: "provenance", cidocMapping: "la:Set", description: "CIDOC-CRM/LinkedArt interop class for Yale LUX alignment (not user-contributable)." },
  { id: "Stupa", label: "Stupa", category: "tangible", cidocMapping: "heritageGraph:Stupa", description: "Buddhist dome-shaped reliquary shrine (e.g., Boudhanath, Swayambhunath)", parent: "BuddhistMonument" },
  { id: "SyncreticRelationship", label: "SyncreticRelationship", category: "conceptual", cidocMapping: "crm:E13_Attribute_Assignment", description: "Formalizes the syncretic equivalence between divine entities across different theological frameworks. Following CIDOC CRM E13, it treats syncretism as a propositional claim with associated epistemic authority and provenance." },
  { id: "Technique", label: "Technique", category: "tangible", cidocMapping: "crm:E29_Design_or_Procedure", description: "Method or craft process used in production or ritual" },
  { id: "Temple", label: "Temple", category: "tangible", cidocMapping: "heritageGraph:Temple", description: "Sacred architectural structure legally classified as an 'Ancient Monument' under Nepal's preservation laws, characterized by deity enshrinement and ritual activation.", parent: "ArchitecturalStructure" },
  { id: "TimeSpan", label: "TimeSpan", category: "spatial", cidocMapping: "crm:E52_Time-Span", description: "Temporal extent of an event or period" },
  { id: "Title", label: "Title", category: "tangible", cidocMapping: "crm:E35_Title", description: "CIDOC-CRM/LinkedArt interop class for Yale LUX alignment (not user-contributable)." },
  { id: "TransferOfCustody", label: "TransferOfCustody", category: "tangible", cidocMapping: "crm:E10_Transfer_of_Custody", description: "Event of transferring responsibility for temple maintenance, ritual performance, or artifact stewardship" },
  { id: "Verification", label: "Verification", category: "tangible", cidocMapping: "heritageGraph:Verification", description: "Process of cross-checking heritage claims against multiple sources", parent: "DocumentationActivity" },
  { id: "VisualItem", label: "VisualItem", category: "tangible", cidocMapping: "crm:E36_Visual_Item", description: "CIDOC-CRM/LinkedArt interop class for Yale LUX alignment (not user-contributable)." },
  { id: "WaterStructure", label: "WaterStructure", category: "tangible", cidocMapping: "heritageGraph:WaterStructure", description: "Engineered water supply systems with ritual and civic significance", parent: "ArchitecturalStructure" },
  { id: "ArchitecturalStyleEnum", label: "ArchitecturalStyleEnum", category: "enum", cidocMapping: "heritageGraph:ArchitecturalStyleEnum", description: "A vocabulary of architectural styles for South Asian heritage, mapped to CIDOC E55 Type." },
  { id: "ArchitecturalStyleEnum_Chaitya", label: "Chaitya", category: "enum", cidocMapping: "heritageGraph:ArchitecturalStyleEnum#Chaitya", description: "Buddhist votive shrine style", parent: "ArchitecturalStyleEnum" },
  { id: "ArchitecturalStyleEnum_Dome", label: "Dome", category: "enum", cidocMapping: "heritageGraph:ArchitecturalStyleEnum#Dome", description: "Dome-based style (Mughal/Neo-classical influence)", parent: "ArchitecturalStyleEnum" },
  { id: "ArchitecturalStyleEnum_Pagoda", label: "Pagoda", category: "enum", cidocMapping: "heritageGraph:ArchitecturalStyleEnum#Pagoda", description: "Multi-tiered roof style indigenous to Nepal", parent: "ArchitecturalStyleEnum" },
  { id: "ArchitecturalStyleEnum_Shikhara", label: "Shikhara", category: "enum", cidocMapping: "heritageGraph:ArchitecturalStyleEnum#Shikhara", description: "North Indian spire-shaped style", parent: "ArchitecturalStyleEnum" },
  { id: "ArchitecturalStyleEnum_Stupa", label: "Stupa", category: "enum", cidocMapping: "heritageGraph:ArchitecturalStyleEnum#Stupa", description: "Buddhist dome-shaped reliquary", parent: "ArchitecturalStyleEnum" },
  { id: "ConditionTypeEnum", label: "ConditionTypeEnum", category: "enum", cidocMapping: "heritageGraph:ConditionTypeEnum", description: "Enumeration ConditionTypeEnum" },
  { id: "ConditionTypeEnum_Damaged", label: "Damaged", category: "enum", cidocMapping: "heritageGraph:ConditionTypeEnum#Damaged", description: "Partially damaged", parent: "ConditionTypeEnum" },
  { id: "ConditionTypeEnum_Good", label: "Good", category: "enum", cidocMapping: "heritageGraph:ConditionTypeEnum#Good", description: "No significant damage", parent: "ConditionTypeEnum" },
  { id: "ConditionTypeEnum_Restored", label: "Restored", category: "enum", cidocMapping: "heritageGraph:ConditionTypeEnum#Restored", description: "Repaired and stabilized", parent: "ConditionTypeEnum" },
  { id: "ConditionTypeEnum_Ruined", label: "Ruined", category: "enum", cidocMapping: "heritageGraph:ConditionTypeEnum#Ruined", description: "Severely damaged or collapsed", parent: "ConditionTypeEnum" },
  { id: "CulturalEntityCategoryEnum", label: "CulturalEntityCategoryEnum", category: "enum", cidocMapping: "heritageGraph:CulturalEntityCategoryEnum", description: "Domain category for a high-level cultural entity contribution." },
  { id: "CulturalEntityCategoryEnum_artifact", label: "artifact", category: "enum", cidocMapping: "heritageGraph:CulturalEntityCategoryEnum#artifact", description: "artifact", parent: "CulturalEntityCategoryEnum" },
  { id: "CulturalEntityCategoryEnum_document", label: "document", category: "enum", cidocMapping: "heritageGraph:CulturalEntityCategoryEnum#document", description: "document", parent: "CulturalEntityCategoryEnum" },
  { id: "CulturalEntityCategoryEnum_festival", label: "festival", category: "enum", cidocMapping: "heritageGraph:CulturalEntityCategoryEnum#festival", description: "festival", parent: "CulturalEntityCategoryEnum" },
  { id: "CulturalEntityCategoryEnum_monument", label: "monument", category: "enum", cidocMapping: "heritageGraph:CulturalEntityCategoryEnum#monument", description: "Monument or built heritage", parent: "CulturalEntityCategoryEnum" },
  { id: "CulturalEntityCategoryEnum_other", label: "other", category: "enum", cidocMapping: "heritageGraph:CulturalEntityCategoryEnum#other", description: "other", parent: "CulturalEntityCategoryEnum" },
  { id: "CulturalEntityCategoryEnum_ritual", label: "ritual", category: "enum", cidocMapping: "heritageGraph:CulturalEntityCategoryEnum#ritual", description: "ritual", parent: "CulturalEntityCategoryEnum" },
  { id: "CulturalEntityCategoryEnum_tradition", label: "tradition", category: "enum", cidocMapping: "heritageGraph:CulturalEntityCategoryEnum#tradition", description: "tradition", parent: "CulturalEntityCategoryEnum" },
  { id: "DatePrecisionEnum", label: "DatePrecisionEnum", category: "enum", cidocMapping: "heritageGraph:DatePrecisionEnum", description: "Enumeration DatePrecisionEnum" },
  { id: "DatePrecisionEnum_Century", label: "Century", category: "enum", cidocMapping: "heritageGraph:DatePrecisionEnum#Century", description: "Within century range", parent: "DatePrecisionEnum" },
  { id: "DatePrecisionEnum_Circa", label: "Circa", category: "enum", cidocMapping: "heritageGraph:DatePrecisionEnum#Circa", description: "Approximate date", parent: "DatePrecisionEnum" },
  { id: "DatePrecisionEnum_Decade", label: "Decade", category: "enum", cidocMapping: "heritageGraph:DatePrecisionEnum#Decade", description: "Within 10-year range", parent: "DatePrecisionEnum" },
  { id: "DatePrecisionEnum_Exact", label: "Exact", category: "enum", cidocMapping: "heritageGraph:DatePrecisionEnum#Exact", description: "Precise date known", parent: "DatePrecisionEnum" },
  { id: "DatePrecisionEnum_Year", label: "Year", category: "enum", cidocMapping: "heritageGraph:DatePrecisionEnum#Year", description: "Year-level precision only", parent: "DatePrecisionEnum" },
  { id: "ExistenceStatusEnum", label: "ExistenceStatusEnum", category: "enum", cidocMapping: "heritageGraph:ExistenceStatusEnum", description: "Enumeration ExistenceStatusEnum" },
  { id: "ExistenceStatusEnum_Destroyed", label: "Destroyed", category: "enum", cidocMapping: "heritageGraph:ExistenceStatusEnum#Destroyed", description: "Known to have been destroyed; no physical remains", parent: "ExistenceStatusEnum" },
  { id: "ExistenceStatusEnum_Extant", label: "Extant", category: "enum", cidocMapping: "heritageGraph:ExistenceStatusEnum#Extant", description: "Currently exists in physical form", parent: "ExistenceStatusEnum" },
  { id: "ExistenceStatusEnum_Hypothetical", label: "Hypothetical", category: "enum", cidocMapping: "heritageGraph:ExistenceStatusEnum#Hypothetical", description: "Reconstructed or theorized; never physically realized", parent: "ExistenceStatusEnum" },
  { id: "ExistenceStatusEnum_Lost", label: "Lost", category: "enum", cidocMapping: "heritageGraph:ExistenceStatusEnum#Lost", description: "Existence documented but location/remains unknown", parent: "ExistenceStatusEnum" },
  { id: "ExistenceStatusEnum_PartiallyExtant", label: "PartiallyExtant", category: "enum", cidocMapping: "heritageGraph:ExistenceStatusEnum#PartiallyExtant", description: "Fragments or ruins remain", parent: "ExistenceStatusEnum" },
  { id: "ExistenceStatusEnum_Unknown", label: "Unknown", category: "enum", cidocMapping: "heritageGraph:ExistenceStatusEnum#Unknown", description: "Existence status uncertain", parent: "ExistenceStatusEnum" },
  { id: "GuthiTypeEnum", label: "GuthiTypeEnum", category: "enum", cidocMapping: "heritageGraph:GuthiTypeEnum", description: "Controlled vocabulary of Guthi functional types (CRM E55_Type)" },
  { id: "GuthiTypeEnum_JatraGuthi", label: "JatraGuthi", category: "enum", cidocMapping: "heritageGraph:GuthiTypeEnum#JatraGuthi", description: "Festival organization trust", parent: "GuthiTypeEnum" },
  { id: "GuthiTypeEnum_NashaGuthi", label: "NashaGuthi", category: "enum", cidocMapping: "heritageGraph:GuthiTypeEnum#NashaGuthi", description: "Music and dance trust", parent: "GuthiTypeEnum" },
  { id: "GuthiTypeEnum_PujaGuthi", label: "PujaGuthi", category: "enum", cidocMapping: "heritageGraph:GuthiTypeEnum#PujaGuthi", description: "Daily worship trust", parent: "GuthiTypeEnum" },
  { id: "GuthiTypeEnum_RajGuthi", label: "RajGuthi", category: "enum", cidocMapping: "heritageGraph:GuthiTypeEnum#RajGuthi", description: "Royal endowment trust", parent: "GuthiTypeEnum" },
  { id: "GuthiTypeEnum_SanGuthi", label: "SanGuthi", category: "enum", cidocMapping: "heritageGraph:GuthiTypeEnum#SanGuthi", description: "Life-cycle ritual trust", parent: "GuthiTypeEnum" },
  { id: "GuthiTypeEnum_SanaGuthi", label: "SanaGuthi", category: "enum", cidocMapping: "heritageGraph:GuthiTypeEnum#SanaGuthi", description: "Agricultural cooperative trust", parent: "GuthiTypeEnum" },
  { id: "GuthiTypeEnum_SiGuthi", label: "SiGuthi", category: "enum", cidocMapping: "heritageGraph:GuthiTypeEnum#SiGuthi", description: "Funeral trust", parent: "GuthiTypeEnum" },
  { id: "GuthiTypeEnum_TempleGuthi", label: "TempleGuthi", category: "enum", cidocMapping: "heritageGraph:GuthiTypeEnum#TempleGuthi", description: "Temple maintenance trust", parent: "GuthiTypeEnum" },
  { id: "RitualTypeEnum", label: "RitualTypeEnum", category: "enum", cidocMapping: "heritageGraph:RitualTypeEnum", description: "Enumeration RitualTypeEnum" },
  { id: "RitualTypeEnum_Abhisheka", label: "Abhisheka", category: "enum", cidocMapping: "heritageGraph:RitualTypeEnum#Abhisheka", description: "Ritual bathing/anointing of deity", parent: "RitualTypeEnum" },
  { id: "RitualTypeEnum_Bhajan", label: "Bhajan", category: "enum", cidocMapping: "heritageGraph:RitualTypeEnum#Bhajan", description: "Devotional singing ritual", parent: "RitualTypeEnum" },
  { id: "RitualTypeEnum_ChariotProcession", label: "ChariotProcession", category: "enum", cidocMapping: "heritageGraph:RitualTypeEnum#ChariotProcession", description: "Ritual chariot pulling", parent: "RitualTypeEnum" },
  { id: "RitualTypeEnum_Circumambulation", label: "Circumambulation", category: "enum", cidocMapping: "heritageGraph:RitualTypeEnum#Circumambulation", description: "Ritual circular movement around sacred site", parent: "RitualTypeEnum" },
  { id: "RitualTypeEnum_DeinstallationRitual", label: "DeinstallationRitual", category: "enum", cidocMapping: "heritageGraph:RitualTypeEnum#DeinstallationRitual", description: "De-installation/conclusion ritual", parent: "RitualTypeEnum" },
  { id: "RitualTypeEnum_Homa", label: "Homa", category: "enum", cidocMapping: "heritageGraph:RitualTypeEnum#Homa", description: "Fire offering ritual", parent: "RitualTypeEnum" },
  { id: "RitualTypeEnum_InstallationRitual", label: "InstallationRitual", category: "enum", cidocMapping: "heritageGraph:RitualTypeEnum#InstallationRitual", description: "Installation/enshrinement ritual", parent: "RitualTypeEnum" },
  { id: "RitualTypeEnum_Jatra", label: "Jatra", category: "enum", cidocMapping: "heritageGraph:RitualTypeEnum#Jatra", description: "Festival procession ritual", parent: "RitualTypeEnum" },
  { id: "RitualTypeEnum_KamyaPuja", label: "KamyaPuja", category: "enum", cidocMapping: "heritageGraph:RitualTypeEnum#KamyaPuja", description: "Desire-based optional worship", parent: "RitualTypeEnum" },
  { id: "RitualTypeEnum_MaskedPerformance", label: "MaskedPerformance", category: "enum", cidocMapping: "heritageGraph:RitualTypeEnum#MaskedPerformance", description: "Ritual masked dance", parent: "RitualTypeEnum" },
  { id: "RitualTypeEnum_NaimittikaPuja", label: "NaimittikaPuja", category: "enum", cidocMapping: "heritageGraph:RitualTypeEnum#NaimittikaPuja", description: "Occasional/Festival worship", parent: "RitualTypeEnum" },
  { id: "RitualTypeEnum_NityaPuja", label: "NityaPuja", category: "enum", cidocMapping: "heritageGraph:RitualTypeEnum#NityaPuja", description: "Daily mandatory worship", parent: "RitualTypeEnum" },
  { id: "RitualTypeEnum_ProcessionRitual", label: "ProcessionRitual", category: "enum", cidocMapping: "heritageGraph:RitualTypeEnum#ProcessionRitual", description: "Ritual procession/movement", parent: "RitualTypeEnum" },
  { id: "RitualTypeEnum_ProcessionalMovement", label: "ProcessionalMovement", category: "enum", cidocMapping: "heritageGraph:RitualTypeEnum#ProcessionalMovement", description: "General ritual movement between locations", parent: "RitualTypeEnum" },
  { id: "RitualTypeEnum_RelicTour", label: "RelicTour", category: "enum", cidocMapping: "heritageGraph:RitualTypeEnum#RelicTour", description: "Procession with sacred relics between sites", parent: "RitualTypeEnum" },
  { id: "RitualTypeEnum_ReturningRitual", label: "ReturningRitual", category: "enum", cidocMapping: "heritageGraph:RitualTypeEnum#ReturningRitual", description: "Return to normal state ritual", parent: "RitualTypeEnum" },
  { id: "RitualTypeEnum_RitualConsecration", label: "RitualConsecration", category: "enum", cidocMapping: "heritageGraph:RitualTypeEnum#RitualConsecration", description: "Consecration/activation ritual", parent: "RitualTypeEnum" },
  { id: "RitualTypeEnum_Vrata", label: "Vrata", category: "enum", cidocMapping: "heritageGraph:RitualTypeEnum#Vrata", description: "Vow observance ritual", parent: "RitualTypeEnum" },
  { id: "RitualTypeEnum_Yagna", label: "Yagna", category: "enum", cidocMapping: "heritageGraph:RitualTypeEnum#Yagna", description: "Vedic sacrifice ritual", parent: "RitualTypeEnum" },
  { id: "SyncreticTypeEnum", label: "SyncreticTypeEnum", category: "enum", cidocMapping: "heritageGraph:SyncreticTypeEnum", description: "Enumeration SyncreticTypeEnum" },
  { id: "SyncreticTypeEnum_Appropriation", label: "Appropriation", category: "enum", cidocMapping: "heritageGraph:SyncreticTypeEnum#Appropriation", description: "Deity borrowed from one tradition into another", parent: "SyncreticTypeEnum" },
  { id: "SyncreticTypeEnum_Equivalence", label: "Equivalence", category: "enum", cidocMapping: "heritageGraph:SyncreticTypeEnum#Equivalence", description: "Same deity in different traditions (e.g., Avalokiteshvara = Matsyendranath)", parent: "SyncreticTypeEnum" },
  { id: "SyncreticTypeEnum_Fusion", label: "Fusion", category: "enum", cidocMapping: "heritageGraph:SyncreticTypeEnum#Fusion", description: "Intrinsically syncretic deity merging multiple traditions", parent: "SyncreticTypeEnum" },
  { id: "SyncreticTypeEnum_Historical", label: "Historical", category: "enum", cidocMapping: "heritageGraph:SyncreticTypeEnum#Historical", description: "Gradual syncretism over time", parent: "SyncreticTypeEnum" },
];

const IS_A_EDGES: OntologyEdge[] = [
  { id: "isa__ArchitecturalStructure__HumanMadeObject", source: "ArchitecturalStructure", target: "HumanMadeObject", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__ArchivalRecord__DataSource", source: "ArchivalRecord", target: "DataSource", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__BuddhistMonument__ArchitecturalStructure", source: "BuddhistMonument", target: "ArchitecturalStructure", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__Chaitya__BuddhistMonument", source: "Chaitya", target: "BuddhistMonument", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__ChariotFestival__Festival", source: "ChariotFestival", target: "Festival", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__DestructionEvent__HistoricalEvent", source: "DestructionEvent", target: "HistoricalEvent", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__Dharmashala__RestHouse", source: "Dharmashala", target: "RestHouse", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__DhungeDhara__WaterStructure", source: "DhungeDhara", target: "WaterStructure", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__Festival__RitualEvent", source: "Festival", target: "RitualEvent", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__FieldSurveyActivity__DocumentationActivity", source: "FieldSurveyActivity", target: "DocumentationActivity", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__FieldSurveyDataset__DataSource", source: "FieldSurveyDataset", target: "DataSource", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__IconographicObject__HumanMadeObject", source: "IconographicObject", target: "HumanMadeObject", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__InformationObject__DataSource", source: "InformationObject", target: "DataSource", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__LivingGoddessRetirement__RitualEvent", source: "LivingGoddessRetirement", target: "RitualEvent", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__LivingGoddessSelection__RitualEvent", source: "LivingGoddessSelection", target: "RitualEvent", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__MaskedDance__Festival", source: "MaskedDance", target: "Festival", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__Murti__IconographicObject", source: "Murti", target: "IconographicObject", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__OralHistoryInterview__DocumentationActivity", source: "OralHistoryInterview", target: "DocumentationActivity", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__OralHistoryRecording__DataSource", source: "OralHistoryRecording", target: "DataSource", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__Pati__RestHouse", source: "Pati", target: "RestHouse", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__Paubha__IconographicObject", source: "Paubha", target: "IconographicObject", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__Pokhari__WaterStructure", source: "Pokhari", target: "WaterStructure", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__RestHouse__ArchitecturalStructure", source: "RestHouse", target: "ArchitecturalStructure", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__Sattal__RestHouse", source: "Sattal", target: "RestHouse", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__Stupa__BuddhistMonument", source: "Stupa", target: "BuddhistMonument", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__Temple__ArchitecturalStructure", source: "Temple", target: "ArchitecturalStructure", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__Verification__DocumentationActivity", source: "Verification", target: "DocumentationActivity", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__WaterStructure__ArchitecturalStructure", source: "WaterStructure", target: "ArchitecturalStructure", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__ArchitecturalStyleEnum_Chaitya__ArchitecturalStyleEnum", source: "ArchitecturalStyleEnum_Chaitya", target: "ArchitecturalStyleEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__ArchitecturalStyleEnum_Dome__ArchitecturalStyleEnum", source: "ArchitecturalStyleEnum_Dome", target: "ArchitecturalStyleEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__ArchitecturalStyleEnum_Pagoda__ArchitecturalStyleEnum", source: "ArchitecturalStyleEnum_Pagoda", target: "ArchitecturalStyleEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__ArchitecturalStyleEnum_Shikhara__ArchitecturalStyleEnum", source: "ArchitecturalStyleEnum_Shikhara", target: "ArchitecturalStyleEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__ArchitecturalStyleEnum_Stupa__ArchitecturalStyleEnum", source: "ArchitecturalStyleEnum_Stupa", target: "ArchitecturalStyleEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__ConditionTypeEnum_Damaged__ConditionTypeEnum", source: "ConditionTypeEnum_Damaged", target: "ConditionTypeEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__ConditionTypeEnum_Good__ConditionTypeEnum", source: "ConditionTypeEnum_Good", target: "ConditionTypeEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__ConditionTypeEnum_Restored__ConditionTypeEnum", source: "ConditionTypeEnum_Restored", target: "ConditionTypeEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__ConditionTypeEnum_Ruined__ConditionTypeEnum", source: "ConditionTypeEnum_Ruined", target: "ConditionTypeEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__CulturalEntityCategoryEnum_artifact__CulturalEntityCategoryEnum", source: "CulturalEntityCategoryEnum_artifact", target: "CulturalEntityCategoryEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__CulturalEntityCategoryEnum_document__CulturalEntityCategoryEnum", source: "CulturalEntityCategoryEnum_document", target: "CulturalEntityCategoryEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__CulturalEntityCategoryEnum_festival__CulturalEntityCategoryEnum", source: "CulturalEntityCategoryEnum_festival", target: "CulturalEntityCategoryEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__CulturalEntityCategoryEnum_monument__CulturalEntityCategoryEnum", source: "CulturalEntityCategoryEnum_monument", target: "CulturalEntityCategoryEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__CulturalEntityCategoryEnum_other__CulturalEntityCategoryEnum", source: "CulturalEntityCategoryEnum_other", target: "CulturalEntityCategoryEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__CulturalEntityCategoryEnum_ritual__CulturalEntityCategoryEnum", source: "CulturalEntityCategoryEnum_ritual", target: "CulturalEntityCategoryEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__CulturalEntityCategoryEnum_tradition__CulturalEntityCategoryEnum", source: "CulturalEntityCategoryEnum_tradition", target: "CulturalEntityCategoryEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__DatePrecisionEnum_Century__DatePrecisionEnum", source: "DatePrecisionEnum_Century", target: "DatePrecisionEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__DatePrecisionEnum_Circa__DatePrecisionEnum", source: "DatePrecisionEnum_Circa", target: "DatePrecisionEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__DatePrecisionEnum_Decade__DatePrecisionEnum", source: "DatePrecisionEnum_Decade", target: "DatePrecisionEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__DatePrecisionEnum_Exact__DatePrecisionEnum", source: "DatePrecisionEnum_Exact", target: "DatePrecisionEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__DatePrecisionEnum_Year__DatePrecisionEnum", source: "DatePrecisionEnum_Year", target: "DatePrecisionEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__ExistenceStatusEnum_Destroyed__ExistenceStatusEnum", source: "ExistenceStatusEnum_Destroyed", target: "ExistenceStatusEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__ExistenceStatusEnum_Extant__ExistenceStatusEnum", source: "ExistenceStatusEnum_Extant", target: "ExistenceStatusEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__ExistenceStatusEnum_Hypothetical__ExistenceStatusEnum", source: "ExistenceStatusEnum_Hypothetical", target: "ExistenceStatusEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__ExistenceStatusEnum_Lost__ExistenceStatusEnum", source: "ExistenceStatusEnum_Lost", target: "ExistenceStatusEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__ExistenceStatusEnum_PartiallyExtant__ExistenceStatusEnum", source: "ExistenceStatusEnum_PartiallyExtant", target: "ExistenceStatusEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__ExistenceStatusEnum_Unknown__ExistenceStatusEnum", source: "ExistenceStatusEnum_Unknown", target: "ExistenceStatusEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__GuthiTypeEnum_JatraGuthi__GuthiTypeEnum", source: "GuthiTypeEnum_JatraGuthi", target: "GuthiTypeEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__GuthiTypeEnum_NashaGuthi__GuthiTypeEnum", source: "GuthiTypeEnum_NashaGuthi", target: "GuthiTypeEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__GuthiTypeEnum_PujaGuthi__GuthiTypeEnum", source: "GuthiTypeEnum_PujaGuthi", target: "GuthiTypeEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__GuthiTypeEnum_RajGuthi__GuthiTypeEnum", source: "GuthiTypeEnum_RajGuthi", target: "GuthiTypeEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__GuthiTypeEnum_SanGuthi__GuthiTypeEnum", source: "GuthiTypeEnum_SanGuthi", target: "GuthiTypeEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__GuthiTypeEnum_SanaGuthi__GuthiTypeEnum", source: "GuthiTypeEnum_SanaGuthi", target: "GuthiTypeEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__GuthiTypeEnum_SiGuthi__GuthiTypeEnum", source: "GuthiTypeEnum_SiGuthi", target: "GuthiTypeEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__GuthiTypeEnum_TempleGuthi__GuthiTypeEnum", source: "GuthiTypeEnum_TempleGuthi", target: "GuthiTypeEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__RitualTypeEnum_Abhisheka__RitualTypeEnum", source: "RitualTypeEnum_Abhisheka", target: "RitualTypeEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__RitualTypeEnum_Bhajan__RitualTypeEnum", source: "RitualTypeEnum_Bhajan", target: "RitualTypeEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__RitualTypeEnum_ChariotProcession__RitualTypeEnum", source: "RitualTypeEnum_ChariotProcession", target: "RitualTypeEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__RitualTypeEnum_Circumambulation__RitualTypeEnum", source: "RitualTypeEnum_Circumambulation", target: "RitualTypeEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__RitualTypeEnum_DeinstallationRitual__RitualTypeEnum", source: "RitualTypeEnum_DeinstallationRitual", target: "RitualTypeEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__RitualTypeEnum_Homa__RitualTypeEnum", source: "RitualTypeEnum_Homa", target: "RitualTypeEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__RitualTypeEnum_InstallationRitual__RitualTypeEnum", source: "RitualTypeEnum_InstallationRitual", target: "RitualTypeEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__RitualTypeEnum_Jatra__RitualTypeEnum", source: "RitualTypeEnum_Jatra", target: "RitualTypeEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__RitualTypeEnum_KamyaPuja__RitualTypeEnum", source: "RitualTypeEnum_KamyaPuja", target: "RitualTypeEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__RitualTypeEnum_MaskedPerformance__RitualTypeEnum", source: "RitualTypeEnum_MaskedPerformance", target: "RitualTypeEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__RitualTypeEnum_NaimittikaPuja__RitualTypeEnum", source: "RitualTypeEnum_NaimittikaPuja", target: "RitualTypeEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__RitualTypeEnum_NityaPuja__RitualTypeEnum", source: "RitualTypeEnum_NityaPuja", target: "RitualTypeEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__RitualTypeEnum_ProcessionRitual__RitualTypeEnum", source: "RitualTypeEnum_ProcessionRitual", target: "RitualTypeEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__RitualTypeEnum_ProcessionalMovement__RitualTypeEnum", source: "RitualTypeEnum_ProcessionalMovement", target: "RitualTypeEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__RitualTypeEnum_RelicTour__RitualTypeEnum", source: "RitualTypeEnum_RelicTour", target: "RitualTypeEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__RitualTypeEnum_ReturningRitual__RitualTypeEnum", source: "RitualTypeEnum_ReturningRitual", target: "RitualTypeEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__RitualTypeEnum_RitualConsecration__RitualTypeEnum", source: "RitualTypeEnum_RitualConsecration", target: "RitualTypeEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__RitualTypeEnum_Vrata__RitualTypeEnum", source: "RitualTypeEnum_Vrata", target: "RitualTypeEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__RitualTypeEnum_Yagna__RitualTypeEnum", source: "RitualTypeEnum_Yagna", target: "RitualTypeEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__SyncreticTypeEnum_Appropriation__SyncreticTypeEnum", source: "SyncreticTypeEnum_Appropriation", target: "SyncreticTypeEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__SyncreticTypeEnum_Equivalence__SyncreticTypeEnum", source: "SyncreticTypeEnum_Equivalence", target: "SyncreticTypeEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__SyncreticTypeEnum_Fusion__SyncreticTypeEnum", source: "SyncreticTypeEnum_Fusion", target: "SyncreticTypeEnum", label: 'is_a', edgeType: 'is_a' },
  { id: "isa__SyncreticTypeEnum_Historical__SyncreticTypeEnum", source: "SyncreticTypeEnum_Historical", target: "SyncreticTypeEnum", label: 'is_a', edgeType: 'is_a' },
];

const PROPERTY_EDGES: OntologyEdge[] = [
  { id: "op_0", source: "ArchitecturalElement", target: "ArchitecturalStructure", label: "is_component_of", edgeType: 'object_property' },
  { id: "op_1", source: "ArchitecturalStructure", target: "DestructionEvent", label: "destruction_event", edgeType: 'object_property' },
  { id: "op_2", source: "ArchitecturalStructure", target: "DataSource", label: "documented_in_source", edgeType: 'object_property' },
  { id: "op_3", source: "ArchitecturalStructure", target: "ExistenceStatusEnum", label: "existence_status", edgeType: 'object_property' },
  { id: "op_4", source: "ArchitecturalStructure", target: "ArchitecturalStyleEnum", label: "has_architectural_style", edgeType: 'object_property' },
  { id: "op_5", source: "ArchitecturalStructure", target: "ArchitecturalElement", label: "has_component", edgeType: 'object_property' },
  { id: "op_6", source: "ArchitecturalStructure", target: "ConditionAssessment", label: "has_condition_assessment", edgeType: 'object_property' },
  { id: "op_7", source: "ArchitecturalStructure", target: "Place", label: "has_current_location", edgeType: 'object_property' },
  { id: "op_8", source: "ArchitecturalStructure", target: "HeritageAssertion", label: "has_provenance_assertion", edgeType: 'object_property' },
  { id: "op_9", source: "ArchitecturalStructure", target: "Place", label: "hypothesized_location", edgeType: 'object_property' },
  { id: "op_10", source: "ArchitecturalStructure", target: "Production", label: "was_produced_by_event", edgeType: 'object_property' },
  { id: "op_11", source: "CalendarSystem", target: "ReligiousTradition", label: "is_primary_for_tradition", edgeType: 'object_property' },
  { id: "op_12", source: "ConditionAssessment", target: "ConditionState", label: "assessed_condition_state", edgeType: 'object_property' },
  { id: "op_13", source: "ConditionAssessment", target: "PhysicalHeritageThing", label: "assessed_object", edgeType: 'object_property' },
  { id: "op_14", source: "ConditionAssessment", target: "Actor", label: "carried_out_by", edgeType: 'object_property' },
  { id: "op_15", source: "ConditionAssessment", target: "TimeSpan", label: "has_timespan", edgeType: 'object_property' },
  { id: "op_16", source: "ConditionState", target: "ConditionTypeEnum", label: "has_condition_type", edgeType: 'object_property' },
  { id: "op_17", source: "Consecration", target: "Actor", label: "carried_out_by", edgeType: 'object_property' },
  { id: "op_18", source: "Consecration", target: "Murti", label: "consecrated_object", edgeType: 'object_property' },
  { id: "op_19", source: "Consecration", target: "TimeSpan", label: "has_timespan", edgeType: 'object_property' },
  { id: "op_20", source: "Consecration", target: "Deity", label: "makes_deity_present", edgeType: 'object_property' },
  { id: "op_21", source: "Consecration", target: "Place", label: "took_place_at", edgeType: 'object_property' },
  { id: "op_22", source: "CulturalEntity", target: "CulturalEntityCategoryEnum", label: "category", edgeType: 'object_property' },
  { id: "op_23", source: "DataSource", target: "Actor", label: "datacite_creator", edgeType: 'object_property' },
  { id: "op_24", source: "DataSource", target: "Actor", label: "datacite_publisher", edgeType: 'object_property' },
  { id: "op_25", source: "DataSource", target: "TimeSpan", label: "publication_timespan", edgeType: 'object_property' },
  { id: "op_26", source: "Deity", target: "ReligiousTradition", label: "has_religious_tradition", edgeType: 'object_property' },
  { id: "op_27", source: "Deity", target: "IconographicObject", label: "is_depicted_in", edgeType: 'object_property' },
  { id: "op_28", source: "Deity", target: "Enshrinement", label: "is_enshrined_through_event", edgeType: 'object_property' },
  { id: "op_29", source: "Deity", target: "RitualEvent", label: "is_invoked_in_ritual", edgeType: 'object_property' },
  { id: "op_30", source: "DestructionEvent", target: "TimeSpan", label: "has_timespan", edgeType: 'object_property' },
  { id: "op_31", source: "DestructionEvent", target: "Place", label: "took_place_at", edgeType: 'object_property' },
  { id: "op_32", source: "DocumentationActivity", target: "HeritageAssertion", label: "generated_assertion", edgeType: 'object_property' },
  { id: "op_33", source: "DocumentationActivity", target: "TimeSpan", label: "has_timespan", edgeType: 'object_property' },
  { id: "op_34", source: "DocumentationActivity", target: "Person", label: "performed_by_agent", edgeType: 'object_property' },
  { id: "op_35", source: "DocumentationActivity", target: "InformationObject", label: "produced_information_object", edgeType: 'object_property' },
  { id: "op_36", source: "DocumentationActivity", target: "PhysicalHeritageThing", label: "subject_entity", edgeType: 'object_property' },
  { id: "op_37", source: "DocumentationActivity", target: "RitualEvent", label: "subject_event", edgeType: 'object_property' },
  { id: "op_38", source: "Enshrinement", target: "Actor", label: "carried_out_by", edgeType: 'object_property' },
  { id: "op_39", source: "Enshrinement", target: "Deity", label: "enshrined_deity", edgeType: 'object_property' },
  { id: "op_40", source: "Enshrinement", target: "Temple", label: "enshrined_in_structure", edgeType: 'object_property' },
  { id: "op_41", source: "Enshrinement", target: "TimeSpan", label: "has_timespan", edgeType: 'object_property' },
  { id: "op_42", source: "Festival", target: "RitualEvent", label: "includes_ritual_event", edgeType: 'object_property' },
  { id: "op_43", source: "Guthi", target: "GuthiTypeEnum", label: "guthi_type", edgeType: 'object_property' },
  { id: "op_44", source: "Guthi", target: "Person", label: "has_membership", edgeType: 'object_property' },
  { id: "op_45", source: "Guthi", target: "ArchitecturalStructure", label: "holds_custody_of", edgeType: 'object_property' },
  { id: "op_46", source: "Guthi", target: "RitualEvent", label: "performs_ritual", edgeType: 'object_property' },
  { id: "op_47", source: "HeritageAssertion", target: "AssertableEntity", label: "asserts_about_entity", edgeType: 'object_property' },
  { id: "op_48", source: "HeritageAssertion", target: "RitualEvent", label: "asserts_about_event", edgeType: 'object_property' },
  { id: "op_49", source: "HeritageAssertion", target: "HeritageAssertion", label: "supersedes_assertion", edgeType: 'object_property' },
  { id: "op_50", source: "HeritageAssertion", target: "Person", label: "was_attributed_to_agent", edgeType: 'object_property' },
  { id: "op_51", source: "HeritageAssertion", target: "DataSource", label: "was_derived_from_source", edgeType: 'object_property' },
  { id: "op_52", source: "HistoricalEvent", target: "ArchitecturalStructure", label: "architectural_structures", edgeType: 'object_property' },
  { id: "op_53", source: "HistoricalEvent", target: "TimeSpan", label: "has_timespan", edgeType: 'object_property' },
  { id: "op_54", source: "HistoricalEvent", target: "RitualEvent", label: "includes_ritual_event", edgeType: 'object_property' },
  { id: "op_55", source: "HistoricalEvent", target: "Place", label: "took_place_at", edgeType: 'object_property' },
  { id: "op_56", source: "HistoricalPeriod", target: "TimeSpan", label: "has_timespan", edgeType: 'object_property' },
  { id: "op_57", source: "HumanMadeObject", target: "ConditionAssessment", label: "has_condition_assessment", edgeType: 'object_property' },
  { id: "op_58", source: "HumanMadeObject", target: "Place", label: "has_current_location", edgeType: 'object_property' },
  { id: "op_59", source: "HumanMadeObject", target: "TransferOfCustody", label: "has_custody_event", edgeType: 'object_property' },
  { id: "op_60", source: "HumanMadeObject", target: "RitualEvent", label: "participates_in_ritual", edgeType: 'object_property' },
  { id: "op_61", source: "HumanMadeObject", target: "DocumentationActivity", label: "was_documented_by", edgeType: 'object_property' },
  { id: "op_62", source: "HumanMadeObject", target: "Production", label: "was_produced_by_event", edgeType: 'object_property' },
  { id: "op_63", source: "IconographicObject", target: "Deity", label: "depicts_deity", edgeType: 'object_property' },
  { id: "op_64", source: "IconographicObject", target: "Place", label: "has_current_location", edgeType: 'object_property' },
  { id: "op_65", source: "IconographicObject", target: "RitualEvent", label: "participates_in_ritual", edgeType: 'object_property' },
  { id: "op_66", source: "IconographicObject", target: "Actor", label: "used_by", edgeType: 'object_property' },
  { id: "op_67", source: "IconographicObject", target: "Production", label: "was_produced_by_event", edgeType: 'object_property' },
  { id: "op_68", source: "InformationObject", target: "DocumentationActivity", label: "created_by_documentation", edgeType: 'object_property' },
  { id: "op_69", source: "InformationObject", target: "ArchitecturalStructure", label: "is_about_entity", edgeType: 'object_property' },
  { id: "op_70", source: "InformationObject", target: "RitualEvent", label: "is_about_event", edgeType: 'object_property' },
  { id: "op_71", source: "InformationObject", target: "DocumentationActivity", label: "was_documented_by", edgeType: 'object_property' },
  { id: "op_72", source: "LivingGoddessRetirement", target: "Actor", label: "carried_out_by", edgeType: 'object_property' },
  { id: "op_73", source: "LivingGoddessRetirement", target: "LivingGoddessTenure", label: "ended_tenure_of", edgeType: 'object_property' },
  { id: "op_74", source: "LivingGoddessRetirement", target: "HeritageAssertion", label: "has_provenance_assertion", edgeType: 'object_property' },
  { id: "op_75", source: "LivingGoddessRetirement", target: "TimeSpan", label: "has_timespan", edgeType: 'object_property' },
  { id: "op_76", source: "LivingGoddessRetirement", target: "CasteGroup", label: "performed_by_group", edgeType: 'object_property' },
  { id: "op_77", source: "LivingGoddessRetirement", target: "Guthi", label: "performed_by_group", edgeType: 'object_property' },
  { id: "op_78", source: "LivingGoddessRetirement", target: "Place", label: "took_place_at", edgeType: 'object_property' },
  { id: "op_79", source: "LivingGoddessRetirement", target: "DocumentationActivity", label: "was_documented_by", edgeType: 'object_property' },
  { id: "op_80", source: "LivingGoddessSelection", target: "Actor", label: "carried_out_by", edgeType: 'object_property' },
  { id: "op_81", source: "LivingGoddessSelection", target: "HeritageAssertion", label: "has_provenance_assertion", edgeType: 'object_property' },
  { id: "op_82", source: "LivingGoddessSelection", target: "TimeSpan", label: "has_timespan", edgeType: 'object_property' },
  { id: "op_83", source: "LivingGoddessSelection", target: "LivingGoddessTenure", label: "initiated_tenure", edgeType: 'object_property' },
  { id: "op_84", source: "LivingGoddessSelection", target: "CasteGroup", label: "performed_by_group", edgeType: 'object_property' },
  { id: "op_85", source: "LivingGoddessSelection", target: "Guthi", label: "performed_by_group", edgeType: 'object_property' },
  { id: "op_86", source: "LivingGoddessSelection", target: "Person", label: "selected_person", edgeType: 'object_property' },
  { id: "op_87", source: "LivingGoddessSelection", target: "Place", label: "took_place_at", edgeType: 'object_property' },
  { id: "op_88", source: "LivingGoddessSelection", target: "DocumentationActivity", label: "was_documented_by", edgeType: 'object_property' },
  { id: "op_89", source: "LivingGoddessTenure", target: "Deity", label: "embodied_deity", edgeType: 'object_property' },
  { id: "op_90", source: "LivingGoddessTenure", target: "Actor", label: "had_participant", edgeType: 'object_property' },
  { id: "op_91", source: "LivingGoddessTenure", target: "LivingGoddessRetirement", label: "has_retirement_event", edgeType: 'object_property' },
  { id: "op_92", source: "LivingGoddessTenure", target: "TimeSpan", label: "has_timespan", edgeType: 'object_property' },
  { id: "op_93", source: "LivingGoddessTenure", target: "ArchitecturalStructure", label: "residence_structure", edgeType: 'object_property' },
  { id: "op_94", source: "LivingGoddessTenure", target: "Guthi", label: "supported_by_institution", edgeType: 'object_property' },
  { id: "op_95", source: "LivingGoddessTenure", target: "DocumentationActivity", label: "was_documented_by", edgeType: 'object_property' },
  { id: "op_96", source: "Murti", target: "Consecration", label: "consecrated_by_event", edgeType: 'object_property' },
  { id: "op_97", source: "Murti", target: "Deity", label: "is_about_deity", edgeType: 'object_property' },
  { id: "op_98", source: "Person", target: "TimeSpan", label: "birth_timespan", edgeType: 'object_property' },
  { id: "op_99", source: "Person", target: "RitualEvent", label: "carried_out_activity", edgeType: 'object_property' },
  { id: "op_100", source: "Person", target: "TimeSpan", label: "death_timespan", edgeType: 'object_property' },
  { id: "op_101", source: "Person", target: "Guthi", label: "member_of_group", edgeType: 'object_property' },
  { id: "op_102", source: "Place", target: "ArchitecturalStructure", label: "contains_structure", edgeType: 'object_property' },
  { id: "op_103", source: "Production", target: "Actor", label: "carried_out_by", edgeType: 'object_property' },
  { id: "op_104", source: "Production", target: "Actor", label: "commissioned_by", edgeType: 'object_property' },
  { id: "op_105", source: "Production", target: "HeritageAssertion", label: "has_provenance_assertion", edgeType: 'object_property' },
  { id: "op_106", source: "Production", target: "TimeSpan", label: "has_timespan", edgeType: 'object_property' },
  { id: "op_107", source: "Production", target: "PhysicalHeritageThing", label: "produced_object", edgeType: 'object_property' },
  { id: "op_108", source: "Production", target: "Place", label: "took_place_at", edgeType: 'object_property' },
  { id: "op_109", source: "Production", target: "Technique", label: "used_technique", edgeType: 'object_property' },
  { id: "op_110", source: "Production", target: "DocumentationActivity", label: "was_documented_by", edgeType: 'object_property' },
  { id: "op_111", source: "RitualEvent", target: "Actor", label: "carried_out_by", edgeType: 'object_property' },
  { id: "op_112", source: "RitualEvent", target: "Place", label: "end_place", edgeType: 'object_property' },
  { id: "op_113", source: "RitualEvent", target: "HeritageAssertion", label: "has_provenance_assertion", edgeType: 'object_property' },
  { id: "op_114", source: "RitualEvent", target: "TimeSpan", label: "has_timespan", edgeType: 'object_property' },
  { id: "op_115", source: "RitualEvent", target: "Deity", label: "invokes_deity", edgeType: 'object_property' },
  { id: "op_116", source: "RitualEvent", target: "Festival", label: "is_part_of_festival", edgeType: 'object_property' },
  { id: "op_117", source: "RitualEvent", target: "Guthi", label: "managed_by_guthi", edgeType: 'object_property' },
  { id: "op_118", source: "RitualEvent", target: "RitualEvent", label: "occurs_after", edgeType: 'object_property' },
  { id: "op_119", source: "RitualEvent", target: "RitualEvent", label: "occurs_before", edgeType: 'object_property' },
  { id: "op_120", source: "RitualEvent", target: "CasteGroup", label: "performed_by_group", edgeType: 'object_property' },
  { id: "op_121", source: "RitualEvent", target: "Guthi", label: "performed_by_group", edgeType: 'object_property' },
  { id: "op_122", source: "RitualEvent", target: "PhysicalHeritageThing", label: "ritual_on_structure", edgeType: 'object_property' },
  { id: "op_123", source: "RitualEvent", target: "RitualTypeEnum", label: "ritual_type", edgeType: 'object_property' },
  { id: "op_124", source: "RitualEvent", target: "Place", label: "route_places", edgeType: 'object_property' },
  { id: "op_125", source: "RitualEvent", target: "Place", label: "start_place", edgeType: 'object_property' },
  { id: "op_126", source: "RitualEvent", target: "Material", label: "used_materials", edgeType: 'object_property' },
  { id: "op_127", source: "RitualEvent", target: "DocumentationActivity", label: "was_documented_by", edgeType: 'object_property' },
  { id: "op_128", source: "SyncreticRelationship", target: "Actor", label: "assertion_author", edgeType: 'object_property' },
  { id: "op_129", source: "SyncreticRelationship", target: "Deity", label: "assigned_equivalent", edgeType: 'object_property' },
  { id: "op_130", source: "SyncreticRelationship", target: "Deity", label: "assigned_to_deity", edgeType: 'object_property' },
  { id: "op_131", source: "SyncreticRelationship", target: "DataSource", label: "documented_in_source", edgeType: 'object_property' },
  { id: "op_132", source: "SyncreticRelationship", target: "SyncreticTypeEnum", label: "syncretic_type", edgeType: 'object_property' },
  { id: "op_133", source: "SyncreticRelationship", target: "DataSource", label: "was_derived_from_source", edgeType: 'object_property' },
  { id: "op_134", source: "SyncreticRelationship", target: "DocumentationActivity", label: "was_documented_by", edgeType: 'object_property' },
  { id: "op_135", source: "Temple", target: "Enshrinement", label: "enshrines_deity_through_event", edgeType: 'object_property' },
  { id: "op_136", source: "Temple", target: "ArchitecturalStyleEnum", label: "has_architectural_style", edgeType: 'object_property' },
  { id: "op_137", source: "TimeSpan", target: "CalendarSystem", label: "calendar_system", edgeType: 'object_property' },
  { id: "op_138", source: "TimeSpan", target: "DatePrecisionEnum", label: "date_precision", edgeType: 'object_property' },
  { id: "op_139", source: "TransferOfCustody", target: "TimeSpan", label: "has_timespan", edgeType: 'object_property' },
  { id: "op_140", source: "TransferOfCustody", target: "Place", label: "took_place_at", edgeType: 'object_property' },
  { id: "op_141", source: "TransferOfCustody", target: "Actor", label: "transferred_from_actor", edgeType: 'object_property' },
  { id: "op_142", source: "TransferOfCustody", target: "PhysicalHeritageThing", label: "transferred_object", edgeType: 'object_property' },
  { id: "op_143", source: "TransferOfCustody", target: "Actor", label: "transferred_to_actor", edgeType: 'object_property' },
  { id: "op_144", source: "TransferOfCustody", target: "Guthi", label: "transferred_to_guthi", edgeType: 'object_property' },
  { id: "op_145", source: "Verification", target: "HeritageAssertion", label: "verified_assertion", edgeType: 'object_property' },
  { id: "op_146", source: "Verification", target: "Person", label: "verified_by_expert", edgeType: 'object_property' },
];

export function getOntologyGraphData(): OntologyGraphData {
  return { nodes: NODES, edges: [...IS_A_EDGES, ...PROPERTY_EDGES] };
}

export function getNodeById(id: string): OntologyNode | undefined {
  return NODES.find((n) => n.id === id);
}

export function getNodesByCategory(c: OntologyCategory): OntologyNode[] {
  return NODES.filter((n) => n.category === c);
}

export function getEdgesForNode(nodeId: string): OntologyEdge[] {
  return [...IS_A_EDGES, ...PROPERTY_EDGES].filter(
    (e) => e.source === nodeId || e.target === nodeId,
  );
}

export function getOntologyStats() {
  const data = getOntologyGraphData();
  const hgNodes = data.nodes.filter((n) => n.category !== 'external');
  return {
    totalClasses: hgNodes.length,
    objectProperties: data.edges.filter((e) => e.edgeType === 'object_property').length,
    hierarchyEdges: data.edges.filter((e) => e.edgeType === 'is_a').length,
    categories: new Set(data.nodes.map((n) => n.category)).size,
    externalClasses: data.nodes.filter((n) => n.category === 'external').length,
    enumMembers: data.nodes.filter((n) => n.parent?.includes('Enum')).length,
  };
}
