# Generated by Django 5.2.12 on 2026-03-19 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidoc_data', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarSystem',
            fields=[
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('contributor', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('epoch_date_gregorian', models.CharField(blank=True, max_length=100)),
                ('year_offset_from_gregorian', models.IntegerField(blank=True, null=True)),
                ('is_primary_for_tradition', models.CharField(blank=True, max_length=50)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Calendar Systems',
                'db_table': 'calendar_system',
            },
        ),
        migrations.CreateModel(
            name='CasteGroup',
            fields=[
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('contributor', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('traditional_role', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Caste Groups',
                'db_table': 'caste_group',
            },
        ),
        migrations.CreateModel(
            name='KumariRetirement',
            fields=[
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('contributor', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('ended_tenure_of', models.CharField(blank=True, max_length=200)),
                ('carried_out_by', models.CharField(blank=True, max_length=200)),
                ('date_earliest', models.CharField(blank=True, max_length=100)),
                ('took_place_at', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KumariSelection',
            fields=[
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('contributor', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('selected_person', models.CharField(blank=True, max_length=200)),
                ('initiated_tenure', models.CharField(blank=True, max_length=200)),
                ('selection_criteria_met', models.TextField(blank=True)),
                ('date_earliest', models.CharField(blank=True, max_length=100)),
                ('took_place_at', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KumariTenure',
            fields=[
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('contributor', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('had_participant', models.CharField(blank=True, max_length=200)),
                ('embodied_deity', models.CharField(blank=True, max_length=200)),
                ('residence_structure', models.CharField(blank=True, max_length=200)),
                ('date_earliest', models.CharField(blank=True, max_length=100)),
                ('date_latest', models.CharField(blank=True, max_length=100)),
                ('supported_by_institution', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Kumari Tenures',
                'db_table': 'kumari_tenure',
            },
        ),
        migrations.CreateModel(
            name='SyncreticRelationship',
            fields=[
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('contributor', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('assigned_to_deity', models.CharField(blank=True, max_length=200)),
                ('assigned_equivalent', models.TextField(blank=True)),
                ('syncretic_type', models.CharField(blank=True, choices=[('Equivalence', 'Equivalence'), ('Appropriation', 'Appropriation'), ('Fusion', 'Fusion'), ('Historical', 'Historical')], max_length=30)),
                ('documented_in_source', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='guthi',
            name='guthi_type',
            field=models.CharField(choices=[('SiGuthi', 'Si Guthi (Funeral Trust)'), ('JatraGuthi', 'Jatra Guthi (Festival Organization)'), ('PujaGuthi', 'Puja Guthi (Daily Worship)'), ('TempleGuthi', 'Temple Guthi (Temple Maintenance)'), ('NashaGuthi', 'Nasha Guthi (Music and Dance)'), ('SanaGuthi', 'Sana Guthi (Agricultural Cooperative)'), ('SanGuthi', 'San Guthi (Life-cycle Ritual)'), ('RajGuthi', 'Raj Guthi (Royal Endowment)'), ('Other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='heritageassertion',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='Type of the entity this assertion is about', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='heritageassertion',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of the entity this assertion is about', null=True),
        ),
        migrations.AlterField(
            model_name='ritualevent',
            name='ritual_type',
            field=models.CharField(choices=[('NityaPuja', 'Nitya Puja (Daily Worship)'), ('NaimittikaPuja', 'Naimittika Puja (Festival Worship)'), ('KamyaPuja', 'Kamya Puja (Desire-based Worship)'), ('Abhisheka', 'Abhisheka (Ritual Bathing)'), ('Homa', 'Homa (Fire Ritual)'), ('Bhajan', 'Bhajan (Devotional Singing)'), ('Yagna', 'Yagna (Vedic Sacrifice)'), ('Vrata', 'Vrata (Vow Observance)'), ('Jatra', 'Jatra (Festival Procession)'), ('ChariotProcession', 'Chariot Procession'), ('MaskedPerformance', 'Masked Performance'), ('RitualConsecration', 'Ritual Consecration'), ('ProcessionRitual', 'Procession Ritual'), ('InstallationRitual', 'Installation Ritual'), ('DeinstallationRitual', 'Deinstallation Ritual'), ('ReturningRitual', 'Returning Ritual'), ('Circumambulation', 'Circumambulation'), ('RelicTour', 'Relic Tour'), ('ProcessionalMovement', 'Processional Movement'), ('Other', 'Other')], max_length=30),
        ),
    ]
