# Generated by Django 5.2.12 on 2026-03-19 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cidoc_data', '0002_calendarsystem_castegroup_kumariretirement_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kumariretirement',
            table='kumari_retirement',
        ),
        migrations.AlterModelTable(
            name='kumariselection',
            table='kumari_selection',
        ),
        migrations.AlterModelTable(
            name='syncreticrelationship',
            table='syncretic_relationship',
        ),
    ]
