# Generated by Django 5.2.8 on 2026-04-21 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidoc_data', '0004_tenant_schema_registry_dynamic_entity'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_object_id', models.PositiveIntegerField()),
                ('predicate', models.CharField(db_index=True, help_text='ORM field name used for this reference', max_length=200)),
                ('to_object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cidoc_entityref_from_set', to='contenttypes.contenttype')),
                ('to_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cidoc_entityref_to_set', to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'cidoc_entityref',
                'indexes': [models.Index(fields=['to_content_type', 'to_object_id'], name='cidoc_entit_to_cont_4cd28b_idx'), models.Index(fields=['from_content_type', 'from_object_id'], name='cidoc_entit_from_co_ab4d44_idx')],
                'constraints': [models.UniqueConstraint(fields=('from_content_type', 'from_object_id', 'predicate', 'to_content_type', 'to_object_id'), name='cidoc_entityref_unique_edge')],
            },
        ),
    ]
