# Generated by Django 5.2.8 on 2026-04-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidoc_data', '0007_cluster_audit_related_cluster'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='entitycluster',
            new_name='entity_clus_type_sc_22d3e8_idx',
            old_name='entity_clust_type_sc_idx',
        ),
        migrations.RenameIndex(
            model_name='entitycluster',
            new_name='entity_clus_merged__5edad7_idx',
            old_name='entity_clust_merged__idx',
        ),
        migrations.RenameIndex(
            model_name='heritageassertion',
            new_name='cidoc_data__asserte_efba19_idx',
            old_name='heritage_ass_asserte_idx',
        ),
        migrations.RenameIndex(
            model_name='identityresolutioncandidate',
            new_name='identity_re_status_5ff568_idx',
            old_name='identity_res_status_idx',
        ),
        migrations.AlterField(
            model_name='entitycluster',
            name='type_scope',
            field=models.CharField(help_text='Django model name for subjects (e.g. person, location)', max_length=100),
        ),
    ]
