# Generated by Django 5.2.8 on 2026-05-04 16:44 — trimmed to KG proposal schema only

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cidoc_data", "0010_postgis_point_fields"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelationshipPredicate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("label", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "db_table": "relationship_predicate",
                "ordering": ["sort_order", "label"],
            },
        ),
        migrations.AddField(
            model_name="entitycluster",
            name="curated_aliases",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Curated surface aliases (not membership claims; see HeritageAssertion identity.same_referent).",
            ),
        ),
        migrations.AddField(
            model_name="entitycluster",
            name="external_identifiers",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="LOD map e.g. {'wikidata': 'Q123'} — informational unless validated downstream.",
            ),
        ),
        migrations.AddField(
            model_name="heritageassertion",
            name="object_content_type",
            field=models.ForeignKey(
                blank=True,
                help_text="For relationship.* assertions: type of the object entity",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="heritageassertion",
            name="object_object_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="For relationship.* assertions: PK of the object entity",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="heritageassertion",
            name="supporting_sources",
            field=models.ManyToManyField(
                blank=True,
                help_text="Additional sources beyond primary `source` FK",
                related_name="supporting_for_assertions",
                to="cidoc_data.datasource",
            ),
        ),
        migrations.AddField(
            model_name="heritageassertion",
            name="temporal_scope_edtf",
            field=models.CharField(
                blank=True,
                help_text="Optional EDTF or human-readable temporal scope for relationship rows",
                max_length=255,
            ),
        ),
        migrations.AddIndex(
            model_name="heritageassertion",
            index=models.Index(
                fields=["object_content_type", "object_object_id"],
                name="cidoc_data__object__910271_idx",
            ),
        ),
    ]
