# Generated by Django 5.2.8 on 2026-05-16 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cidoc_data", "0012_architecturalstructure_has_current_location"),
        ("cidoc_data", "0012_heritageassertion_agent_fields"),
    ]

    operations = []
