# Generated by Django 5.2.8 on 2026-06-01 16:16

import apps.cidoc_data.edtf_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidoc_data', '0013_merge_20260516_2152'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='architecturalstructure',
            name='cidoc_structure_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='architecturalstructure',
            name='cidoc_structure_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='deity',
            name='cidoc_deity_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='entitycluster',
            name='cidoc_cluster_label_idx',
        ),
        migrations.RemoveIndex(
            model_name='heritageassertion',
            name='cidoc_assertion_contrib_idx',
        ),
        migrations.RemoveIndex(
            model_name='location',
            name='cidoc_location_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='location',
            name='cidoc_location_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='person',
            name='cidoc_person_name_idx',
        ),
        migrations.AlterField(
            model_name='architecturalstructure',
            name='construction_date',
            field=models.CharField(blank=True, max_length=100, validators=[apps.cidoc_data.edtf_field.validate_edtf]),
        ),
        migrations.AlterField(
            model_name='architecturalstructure',
            name='coordinates_legacy',
            field=models.CharField(blank=True, help_text="Legacy 'Lat, Long' string — use point field instead", max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.CharField(blank=True, max_length=100, validators=[apps.cidoc_data.edtf_field.validate_edtf]),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.CharField(blank=True, help_text="e.g., 'Baisakh 15' or EDTF like '1934~'", max_length=100, validators=[apps.cidoc_data.edtf_field.validate_edtf]),
        ),
        migrations.AlterField(
            model_name='kumariretirement',
            name='date_earliest',
            field=models.CharField(blank=True, max_length=100, validators=[apps.cidoc_data.edtf_field.validate_edtf]),
        ),
        migrations.AlterField(
            model_name='kumariselection',
            name='date_earliest',
            field=models.CharField(blank=True, max_length=100, validators=[apps.cidoc_data.edtf_field.validate_edtf]),
        ),
        migrations.AlterField(
            model_name='kumaritenure',
            name='date_earliest',
            field=models.CharField(blank=True, max_length=100, validators=[apps.cidoc_data.edtf_field.validate_edtf]),
        ),
        migrations.AlterField(
            model_name='kumaritenure',
            name='date_latest',
            field=models.CharField(blank=True, max_length=100, validators=[apps.cidoc_data.edtf_field.validate_edtf]),
        ),
        migrations.AlterField(
            model_name='location',
            name='coordinates_legacy',
            field=models.CharField(blank=True, help_text="Legacy 'Lat, Long' string — use point field instead", max_length=50),
        ),
        migrations.AlterField(
            model_name='monument',
            name='coordinates_legacy',
            field=models.CharField(blank=True, help_text="Legacy 'Lat, Long' string — use point field instead", max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.CharField(blank=True, max_length=50, validators=[apps.cidoc_data.edtf_field.validate_edtf]),
        ),
        migrations.AlterField(
            model_name='person',
            name='death_date',
            field=models.CharField(blank=True, max_length=50, validators=[apps.cidoc_data.edtf_field.validate_edtf]),
        ),
    ]
