# Generated by Django 5.2.8 on 2026-06-03 09:43

import apps.cidoc_data.edtf_field
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidoc_data', '0014_remove_architecturalstructure_cidoc_structure_name_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='architecturalstructure',
            name='access_tier',
            field=models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('community_only', 'Community only'), ('sensitive_indigenous', 'Sensitive / indigenous')], default='public', help_text='CARE-aligned access tier for publication and LOD export', max_length=32),
        ),
        migrations.AddField(
            model_name='architecturalstructure',
            name='care_labels',
            field=models.JSONField(blank=True, default=list, help_text='TK/CARE label URIs or codes (e.g. community consent markers)'),
        ),
        migrations.AddField(
            model_name='calendarsystem',
            name='access_tier',
            field=models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('community_only', 'Community only'), ('sensitive_indigenous', 'Sensitive / indigenous')], default='public', help_text='CARE-aligned access tier for publication and LOD export', max_length=32),
        ),
        migrations.AddField(
            model_name='calendarsystem',
            name='care_labels',
            field=models.JSONField(blank=True, default=list, help_text='TK/CARE label URIs or codes (e.g. community consent markers)'),
        ),
        migrations.AddField(
            model_name='castegroup',
            name='access_tier',
            field=models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('community_only', 'Community only'), ('sensitive_indigenous', 'Sensitive / indigenous')], default='public', help_text='CARE-aligned access tier for publication and LOD export', max_length=32),
        ),
        migrations.AddField(
            model_name='castegroup',
            name='care_labels',
            field=models.JSONField(blank=True, default=list, help_text='TK/CARE label URIs or codes (e.g. community consent markers)'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='digitization_activity',
            field=models.CharField(blank=True, help_text='Label for digitization or scanning activity', max_length=300),
        ),
        migrations.AddField(
            model_name='datasource',
            name='iiif_manifest_url',
            field=models.URLField(blank=True, help_text='IIIF Presentation 3 manifest URL (CRMdig/Digital resource)', max_length=500),
        ),
        migrations.AddField(
            model_name='deity',
            name='access_tier',
            field=models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('community_only', 'Community only'), ('sensitive_indigenous', 'Sensitive / indigenous')], default='public', help_text='CARE-aligned access tier for publication and LOD export', max_length=32),
        ),
        migrations.AddField(
            model_name='deity',
            name='care_labels',
            field=models.JSONField(blank=True, default=list, help_text='TK/CARE label URIs or codes (e.g. community consent markers)'),
        ),
        migrations.AddField(
            model_name='event',
            name='access_tier',
            field=models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('community_only', 'Community only'), ('sensitive_indigenous', 'Sensitive / indigenous')], default='public', help_text='CARE-aligned access tier for publication and LOD export', max_length=32),
        ),
        migrations.AddField(
            model_name='event',
            name='care_labels',
            field=models.JSONField(blank=True, default=list, help_text='TK/CARE label URIs or codes (e.g. community consent markers)'),
        ),
        migrations.AddField(
            model_name='festival',
            name='access_tier',
            field=models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('community_only', 'Community only'), ('sensitive_indigenous', 'Sensitive / indigenous')], default='public', help_text='CARE-aligned access tier for publication and LOD export', max_length=32),
        ),
        migrations.AddField(
            model_name='festival',
            name='care_labels',
            field=models.JSONField(blank=True, default=list, help_text='TK/CARE label URIs or codes (e.g. community consent markers)'),
        ),
        migrations.AddField(
            model_name='guthi',
            name='access_tier',
            field=models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('community_only', 'Community only'), ('sensitive_indigenous', 'Sensitive / indigenous')], default='public', help_text='CARE-aligned access tier for publication and LOD export', max_length=32),
        ),
        migrations.AddField(
            model_name='guthi',
            name='care_labels',
            field=models.JSONField(blank=True, default=list, help_text='TK/CARE label URIs or codes (e.g. community consent markers)'),
        ),
        migrations.AddField(
            model_name='heritageassertion',
            name='crminf_conclusion',
            field=models.CharField(blank=True, help_text='Optional CRMinf conclusion code (e.g. confirmed, refuted)', max_length=64),
        ),
        migrations.AddField(
            model_name='heritageassertion',
            name='justification_note',
            field=models.TextField(blank=True, help_text='CRMinf-style justification or reasoning chain summary'),
        ),
        migrations.AddField(
            model_name='historicalperiod',
            name='access_tier',
            field=models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('community_only', 'Community only'), ('sensitive_indigenous', 'Sensitive / indigenous')], default='public', help_text='CARE-aligned access tier for publication and LOD export', max_length=32),
        ),
        migrations.AddField(
            model_name='historicalperiod',
            name='care_labels',
            field=models.JSONField(blank=True, default=list, help_text='TK/CARE label URIs or codes (e.g. community consent markers)'),
        ),
        migrations.AddField(
            model_name='iconographicobject',
            name='access_tier',
            field=models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('community_only', 'Community only'), ('sensitive_indigenous', 'Sensitive / indigenous')], default='public', help_text='CARE-aligned access tier for publication and LOD export', max_length=32),
        ),
        migrations.AddField(
            model_name='iconographicobject',
            name='care_labels',
            field=models.JSONField(blank=True, default=list, help_text='TK/CARE label URIs or codes (e.g. community consent markers)'),
        ),
        migrations.AddField(
            model_name='kumariretirement',
            name='access_tier',
            field=models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('community_only', 'Community only'), ('sensitive_indigenous', 'Sensitive / indigenous')], default='public', help_text='CARE-aligned access tier for publication and LOD export', max_length=32),
        ),
        migrations.AddField(
            model_name='kumariretirement',
            name='care_labels',
            field=models.JSONField(blank=True, default=list, help_text='TK/CARE label URIs or codes (e.g. community consent markers)'),
        ),
        migrations.AddField(
            model_name='kumariselection',
            name='access_tier',
            field=models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('community_only', 'Community only'), ('sensitive_indigenous', 'Sensitive / indigenous')], default='public', help_text='CARE-aligned access tier for publication and LOD export', max_length=32),
        ),
        migrations.AddField(
            model_name='kumariselection',
            name='care_labels',
            field=models.JSONField(blank=True, default=list, help_text='TK/CARE label URIs or codes (e.g. community consent markers)'),
        ),
        migrations.AddField(
            model_name='kumaritenure',
            name='access_tier',
            field=models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('community_only', 'Community only'), ('sensitive_indigenous', 'Sensitive / indigenous')], default='public', help_text='CARE-aligned access tier for publication and LOD export', max_length=32),
        ),
        migrations.AddField(
            model_name='kumaritenure',
            name='care_labels',
            field=models.JSONField(blank=True, default=list, help_text='TK/CARE label URIs or codes (e.g. community consent markers)'),
        ),
        migrations.AddField(
            model_name='location',
            name='access_tier',
            field=models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('community_only', 'Community only'), ('sensitive_indigenous', 'Sensitive / indigenous')], default='public', help_text='CARE-aligned access tier for publication and LOD export', max_length=32),
        ),
        migrations.AddField(
            model_name='location',
            name='care_labels',
            field=models.JSONField(blank=True, default=list, help_text='TK/CARE label URIs or codes (e.g. community consent markers)'),
        ),
        migrations.AddField(
            model_name='monument',
            name='access_tier',
            field=models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('community_only', 'Community only'), ('sensitive_indigenous', 'Sensitive / indigenous')], default='public', help_text='CARE-aligned access tier for publication and LOD export', max_length=32),
        ),
        migrations.AddField(
            model_name='monument',
            name='care_labels',
            field=models.JSONField(blank=True, default=list, help_text='TK/CARE label URIs or codes (e.g. community consent markers)'),
        ),
        migrations.AddField(
            model_name='person',
            name='access_tier',
            field=models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('community_only', 'Community only'), ('sensitive_indigenous', 'Sensitive / indigenous')], default='public', help_text='CARE-aligned access tier for publication and LOD export', max_length=32),
        ),
        migrations.AddField(
            model_name='person',
            name='care_labels',
            field=models.JSONField(blank=True, default=list, help_text='TK/CARE label URIs or codes (e.g. community consent markers)'),
        ),
        migrations.AddField(
            model_name='ritualevent',
            name='access_tier',
            field=models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('community_only', 'Community only'), ('sensitive_indigenous', 'Sensitive / indigenous')], default='public', help_text='CARE-aligned access tier for publication and LOD export', max_length=32),
        ),
        migrations.AddField(
            model_name='ritualevent',
            name='care_labels',
            field=models.JSONField(blank=True, default=list, help_text='TK/CARE label URIs or codes (e.g. community consent markers)'),
        ),
        migrations.AddField(
            model_name='source',
            name='access_tier',
            field=models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('community_only', 'Community only'), ('sensitive_indigenous', 'Sensitive / indigenous')], default='public', help_text='CARE-aligned access tier for publication and LOD export', max_length=32),
        ),
        migrations.AddField(
            model_name='source',
            name='care_labels',
            field=models.JSONField(blank=True, default=list, help_text='TK/CARE label URIs or codes (e.g. community consent markers)'),
        ),
        migrations.AddField(
            model_name='syncreticrelationship',
            name='access_tier',
            field=models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('community_only', 'Community only'), ('sensitive_indigenous', 'Sensitive / indigenous')], default='public', help_text='CARE-aligned access tier for publication and LOD export', max_length=32),
        ),
        migrations.AddField(
            model_name='syncreticrelationship',
            name='care_labels',
            field=models.JSONField(blank=True, default=list, help_text='TK/CARE label URIs or codes (e.g. community consent markers)'),
        ),
        migrations.AddField(
            model_name='tradition',
            name='access_tier',
            field=models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('community_only', 'Community only'), ('sensitive_indigenous', 'Sensitive / indigenous')], default='public', help_text='CARE-aligned access tier for publication and LOD export', max_length=32),
        ),
        migrations.AddField(
            model_name='tradition',
            name='care_labels',
            field=models.JSONField(blank=True, default=list, help_text='TK/CARE label URIs or codes (e.g. community consent markers)'),
        ),
        migrations.CreateModel(
            name='Consecration',
            fields=[
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('contributor', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('access_tier', models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('community_only', 'Community only'), ('sensitive_indigenous', 'Sensitive / indigenous')], default='public', help_text='CARE-aligned access tier for publication and LOD export', max_length=32)),
                ('care_labels', models.JSONField(blank=True, default=list, help_text='TK/CARE label URIs or codes (e.g. community consent markers)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('carried_out_by', models.CharField(blank=True, max_length=300)),
                ('makes_deity_present', models.CharField(blank=True, max_length=200)),
                ('date_earliest', models.CharField(blank=True, max_length=100, validators=[apps.cidoc_data.edtf_field.validate_edtf])),
                ('date_latest', models.CharField(blank=True, max_length=100, validators=[apps.cidoc_data.edtf_field.validate_edtf])),
                ('note', models.TextField(blank=True)),
                ('consecrated_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consecration_events', to='cidoc_data.iconographicobject')),
                ('took_place_at', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consecration_events', to='cidoc_data.location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enshrinement',
            fields=[
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('contributor', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('access_tier', models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('community_only', 'Community only'), ('sensitive_indigenous', 'Sensitive / indigenous')], default='public', help_text='CARE-aligned access tier for publication and LOD export', max_length=32)),
                ('care_labels', models.JSONField(blank=True, default=list, help_text='TK/CARE label URIs or codes (e.g. community consent markers)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('carried_out_by', models.CharField(blank=True, max_length=300)),
                ('date_earliest', models.CharField(blank=True, max_length=100, validators=[apps.cidoc_data.edtf_field.validate_edtf])),
                ('date_latest', models.CharField(blank=True, max_length=100, validators=[apps.cidoc_data.edtf_field.validate_edtf])),
                ('note', models.TextField(blank=True)),
                ('enshrined_deity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enshrinement_events', to='cidoc_data.deity')),
                ('enshrined_in_structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enshrinement_events', to='cidoc_data.architecturalstructure')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('contributor', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('access_tier', models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('community_only', 'Community only'), ('sensitive_indigenous', 'Sensitive / indigenous')], default='public', help_text='CARE-aligned access tier for publication and LOD export', max_length=32)),
                ('care_labels', models.JSONField(blank=True, default=list, help_text='TK/CARE label URIs or codes (e.g. community consent markers)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('carried_out_by', models.CharField(blank=True, max_length=300)),
                ('date_earliest', models.CharField(blank=True, max_length=100, validators=[apps.cidoc_data.edtf_field.validate_edtf])),
                ('date_latest', models.CharField(blank=True, max_length=100, validators=[apps.cidoc_data.edtf_field.validate_edtf])),
                ('note', models.TextField(blank=True)),
                ('produced_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_events', to='cidoc_data.architecturalstructure')),
                ('took_place_at', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_events', to='cidoc_data.location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransferOfCustody',
            fields=[
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('contributor', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('access_tier', models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('community_only', 'Community only'), ('sensitive_indigenous', 'Sensitive / indigenous')], default='public', help_text='CARE-aligned access tier for publication and LOD export', max_length=32)),
                ('care_labels', models.JSONField(blank=True, default=list, help_text='TK/CARE label URIs or codes (e.g. community consent markers)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('transferred_from_actor', models.CharField(blank=True, max_length=300)),
                ('transferred_to_actor', models.CharField(blank=True, max_length=300)),
                ('date_earliest', models.CharField(blank=True, max_length=100, validators=[apps.cidoc_data.edtf_field.validate_edtf])),
                ('date_latest', models.CharField(blank=True, max_length=100, validators=[apps.cidoc_data.edtf_field.validate_edtf])),
                ('note', models.TextField(blank=True)),
                ('took_place_at', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_transfers', to='cidoc_data.location')),
                ('transferred_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_transfers', to='cidoc_data.architecturalstructure')),
                ('transferred_to_guthi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_receipts', to='cidoc_data.guthi')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
