# Generated by Django 5.2.8 on 2026-06-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidoc_data', '0016_backfill_metadata_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architecturalstructure',
            name='existence_status',
            field=models.CharField(blank=True, choices=[('Extant', 'Extant'), ('PartiallyExtant', 'Partially Extant'), ('Destroyed', 'Destroyed'), ('Lost', 'Lost'), ('Hypothetical', 'Hypothetical'), ('Unknown', 'Unknown'), ('Damaged', 'Damaged (legacy)'), ('Restored', 'Restored (legacy)'), ('Relocated', 'Relocated (legacy)'), ('Partially_Extant', 'Partially Extant (legacy)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='monument',
            name='existence_status',
            field=models.CharField(blank=True, choices=[('Extant', 'Extant'), ('PartiallyExtant', 'Partially Extant'), ('Destroyed', 'Destroyed'), ('Lost', 'Lost'), ('Hypothetical', 'Hypothetical'), ('Unknown', 'Unknown'), ('Damaged', 'Damaged (legacy)'), ('Restored', 'Restored (legacy)'), ('Relocated', 'Relocated (legacy)'), ('Partially_Extant', 'Partially Extant (legacy)')], max_length=30),
        ),
    ]
