# Generated by Django 5.x — LodExternalIdentity for DANAM / LOD ETL idempotency

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cidoc_data", "0020_heritageassertion_calendar_timespan"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="LodExternalIdentity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_iri", models.URLField(db_index=True, max_length=500, unique=True)),
                (
                    "object_id",
                    models.CharField(
                        help_text="Stringified PK (supports AutoField and UUID primary keys)",
                        max_length=64,
                    ),
                ),
                (
                    "source_batch_sha256",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 of the import file that last wrote this mapping",
                        max_length=64,
                    ),
                ),
                (
                    "import_pass",
                    models.CharField(
                        blank=True,
                        help_text="Importer pass name (structures, assertions, datasources, …)",
                        max_length=40,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lod_external_identities",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "db_table": "lod_external_identity",
            },
        ),
        migrations.AddIndex(
            model_name="lodexternalidentity",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="lod_externa_content_7f2a1e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lodexternalidentity",
            index=models.Index(fields=["import_pass"], name="lod_externa_import__a1b2c3_idx"),
        ),
    ]
