# Generated by Django 5.2.8 on 2026-08-10 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidoc_data', '0021_lod_external_identity'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='heritageassertion',
            name='assertion_calendar_idx',
        ),
        migrations.RenameIndex(
            model_name='datasource',
            new_name='cidoc_data__source__28d6bf_idx',
            old_name='datasource_type_idx',
        ),
        migrations.RenameIndex(
            model_name='datasource',
            new_name='cidoc_data__access__d35e7a_idx',
            old_name='datasource_tier_idx',
        ),
        migrations.RenameIndex(
            model_name='datasource',
            new_name='cidoc_data__ingest__aaee40_idx',
            old_name='datasource_ingest_idx',
        ),
        migrations.RenameIndex(
            model_name='lodexternalidentity',
            new_name='lod_externa_content_97e355_idx',
            old_name='lod_externa_content_7f2a1e_idx',
        ),
        migrations.RenameIndex(
            model_name='lodexternalidentity',
            new_name='lod_externa_import__d63a3c_idx',
            old_name='lod_externa_import__a1b2c3_idx',
        ),
        migrations.AddField(
            model_name='architecturalstructure',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Registered DataSource backing this record, when one exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cidoc_data.datasource'),
        ),
        migrations.AddField(
            model_name='architecturalstructure',
            name='source_citation',
            field=models.TextField(blank=True, default='', help_text="Where this information came from, in the contributor's own words: a book, inscription, interview, site visit, or personal knowledge."),
        ),
        migrations.AddField(
            model_name='calendarsystem',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Registered DataSource backing this record, when one exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cidoc_data.datasource'),
        ),
        migrations.AddField(
            model_name='calendarsystem',
            name='source_citation',
            field=models.TextField(blank=True, default='', help_text="Where this information came from, in the contributor's own words: a book, inscription, interview, site visit, or personal knowledge."),
        ),
        migrations.AddField(
            model_name='castegroup',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Registered DataSource backing this record, when one exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cidoc_data.datasource'),
        ),
        migrations.AddField(
            model_name='castegroup',
            name='source_citation',
            field=models.TextField(blank=True, default='', help_text="Where this information came from, in the contributor's own words: a book, inscription, interview, site visit, or personal knowledge."),
        ),
        migrations.AddField(
            model_name='consecration',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Registered DataSource backing this record, when one exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cidoc_data.datasource'),
        ),
        migrations.AddField(
            model_name='consecration',
            name='source_citation',
            field=models.TextField(blank=True, default='', help_text="Where this information came from, in the contributor's own words: a book, inscription, interview, site visit, or personal knowledge."),
        ),
        migrations.AddField(
            model_name='deity',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Registered DataSource backing this record, when one exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cidoc_data.datasource'),
        ),
        migrations.AddField(
            model_name='deity',
            name='source_citation',
            field=models.TextField(blank=True, default='', help_text="Where this information came from, in the contributor's own words: a book, inscription, interview, site visit, or personal knowledge."),
        ),
        migrations.AddField(
            model_name='enshrinement',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Registered DataSource backing this record, when one exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cidoc_data.datasource'),
        ),
        migrations.AddField(
            model_name='enshrinement',
            name='source_citation',
            field=models.TextField(blank=True, default='', help_text="Where this information came from, in the contributor's own words: a book, inscription, interview, site visit, or personal knowledge."),
        ),
        migrations.AddField(
            model_name='event',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Registered DataSource backing this record, when one exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cidoc_data.datasource'),
        ),
        migrations.AddField(
            model_name='event',
            name='source_citation',
            field=models.TextField(blank=True, default='', help_text="Where this information came from, in the contributor's own words: a book, inscription, interview, site visit, or personal knowledge."),
        ),
        migrations.AddField(
            model_name='festival',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Registered DataSource backing this record, when one exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cidoc_data.datasource'),
        ),
        migrations.AddField(
            model_name='festival',
            name='source_citation',
            field=models.TextField(blank=True, default='', help_text="Where this information came from, in the contributor's own words: a book, inscription, interview, site visit, or personal knowledge."),
        ),
        migrations.AddField(
            model_name='guthi',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Registered DataSource backing this record, when one exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cidoc_data.datasource'),
        ),
        migrations.AddField(
            model_name='guthi',
            name='source_citation',
            field=models.TextField(blank=True, default='', help_text="Where this information came from, in the contributor's own words: a book, inscription, interview, site visit, or personal knowledge."),
        ),
        migrations.AddField(
            model_name='historicalperiod',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Registered DataSource backing this record, when one exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cidoc_data.datasource'),
        ),
        migrations.AddField(
            model_name='historicalperiod',
            name='source_citation',
            field=models.TextField(blank=True, default='', help_text="Where this information came from, in the contributor's own words: a book, inscription, interview, site visit, or personal knowledge."),
        ),
        migrations.AddField(
            model_name='iconographicobject',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Registered DataSource backing this record, when one exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cidoc_data.datasource'),
        ),
        migrations.AddField(
            model_name='iconographicobject',
            name='source_citation',
            field=models.TextField(blank=True, default='', help_text="Where this information came from, in the contributor's own words: a book, inscription, interview, site visit, or personal knowledge."),
        ),
        migrations.AddField(
            model_name='kumariretirement',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Registered DataSource backing this record, when one exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cidoc_data.datasource'),
        ),
        migrations.AddField(
            model_name='kumariretirement',
            name='source_citation',
            field=models.TextField(blank=True, default='', help_text="Where this information came from, in the contributor's own words: a book, inscription, interview, site visit, or personal knowledge."),
        ),
        migrations.AddField(
            model_name='kumariselection',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Registered DataSource backing this record, when one exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cidoc_data.datasource'),
        ),
        migrations.AddField(
            model_name='kumariselection',
            name='source_citation',
            field=models.TextField(blank=True, default='', help_text="Where this information came from, in the contributor's own words: a book, inscription, interview, site visit, or personal knowledge."),
        ),
        migrations.AddField(
            model_name='kumaritenure',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Registered DataSource backing this record, when one exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cidoc_data.datasource'),
        ),
        migrations.AddField(
            model_name='kumaritenure',
            name='source_citation',
            field=models.TextField(blank=True, default='', help_text="Where this information came from, in the contributor's own words: a book, inscription, interview, site visit, or personal knowledge."),
        ),
        migrations.AddField(
            model_name='location',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Registered DataSource backing this record, when one exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cidoc_data.datasource'),
        ),
        migrations.AddField(
            model_name='location',
            name='source_citation',
            field=models.TextField(blank=True, default='', help_text="Where this information came from, in the contributor's own words: a book, inscription, interview, site visit, or personal knowledge."),
        ),
        migrations.AddField(
            model_name='monument',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Registered DataSource backing this record, when one exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cidoc_data.datasource'),
        ),
        migrations.AddField(
            model_name='monument',
            name='source_citation',
            field=models.TextField(blank=True, default='', help_text="Where this information came from, in the contributor's own words: a book, inscription, interview, site visit, or personal knowledge."),
        ),
        migrations.AddField(
            model_name='person',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Registered DataSource backing this record, when one exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cidoc_data.datasource'),
        ),
        migrations.AddField(
            model_name='person',
            name='source_citation',
            field=models.TextField(blank=True, default='', help_text="Where this information came from, in the contributor's own words: a book, inscription, interview, site visit, or personal knowledge."),
        ),
        migrations.AddField(
            model_name='production',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Registered DataSource backing this record, when one exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cidoc_data.datasource'),
        ),
        migrations.AddField(
            model_name='production',
            name='source_citation',
            field=models.TextField(blank=True, default='', help_text="Where this information came from, in the contributor's own words: a book, inscription, interview, site visit, or personal knowledge."),
        ),
        migrations.AddField(
            model_name='ritualevent',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Registered DataSource backing this record, when one exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cidoc_data.datasource'),
        ),
        migrations.AddField(
            model_name='ritualevent',
            name='source_citation',
            field=models.TextField(blank=True, default='', help_text="Where this information came from, in the contributor's own words: a book, inscription, interview, site visit, or personal knowledge."),
        ),
        migrations.AddField(
            model_name='source',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Registered DataSource backing this record, when one exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cidoc_data.datasource'),
        ),
        migrations.AddField(
            model_name='source',
            name='source_citation',
            field=models.TextField(blank=True, default='', help_text="Where this information came from, in the contributor's own words: a book, inscription, interview, site visit, or personal knowledge."),
        ),
        migrations.AddField(
            model_name='syncreticrelationship',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Registered DataSource backing this record, when one exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cidoc_data.datasource'),
        ),
        migrations.AddField(
            model_name='syncreticrelationship',
            name='source_citation',
            field=models.TextField(blank=True, default='', help_text="Where this information came from, in the contributor's own words: a book, inscription, interview, site visit, or personal knowledge."),
        ),
        migrations.AddField(
            model_name='tradition',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Registered DataSource backing this record, when one exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cidoc_data.datasource'),
        ),
        migrations.AddField(
            model_name='tradition',
            name='source_citation',
            field=models.TextField(blank=True, default='', help_text="Where this information came from, in the contributor's own words: a book, inscription, interview, site visit, or personal knowledge."),
        ),
        migrations.AddField(
            model_name='transferofcustody',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Registered DataSource backing this record, when one exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cidoc_data.datasource'),
        ),
        migrations.AddField(
            model_name='transferofcustody',
            name='source_citation',
            field=models.TextField(blank=True, default='', help_text="Where this information came from, in the contributor's own words: a book, inscription, interview, site visit, or personal knowledge."),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='access_tier',
            field=models.CharField(choices=[('public', 'Public — no restrictions'), ('org_only', 'Organization only'), ('community_only', 'Community only'), ('sensitive_indigenous', 'Sensitive / indigenous knowledge')], default='public', help_text='Access control tier; sensitive_indigenous is excluded from public SPARQL', max_length=30),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='datacite_identifier',
            field=models.CharField(blank=True, help_text='DataCite DOI or persistent identifier (e.g. 10.5281/zenodo.xxx)', max_length=300),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='datacite_resource_type',
            field=models.CharField(choices=[('Dataset', 'Dataset'), ('Image', 'Image'), ('Sound', 'Sound'), ('Text', 'Text'), ('PhysicalObject', 'Physical Object'), ('Collection', 'Collection'), ('Software', 'Software')], default='Dataset', help_text='DataCite resource type (Dataset, Image, Sound, Text, …)', max_length=30),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='iiif_manifest',
            field=models.JSONField(blank=True, help_text='Inline IIIF Presentation v3 manifest (populated by Celery after upload)', null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='pid',
            field=models.URLField(blank=True, help_text='HeritageGraph PID: {RDF_RESOURCE_BASE_URI}/data_source/{uuid}', max_length=300),
        ),
    ]
