"""
Seed TEST relationship assertions between existing CIDOC entities so the live
knowledge graph has edges to exercise the museum's graph/map/timeline rendering.

⚠️  TEST DATA ONLY. Every row is tagged `contributed_by="test-seed"` and carries a
    "remove before publication" note. These are NOT sourced scholarly claims — run
    `--clear` to delete them all before any real/published build.

Each created assertion is `relationship.*` + reconciliation_status="accepted", so
the existing rdf_signals projection writes one triple per row into the Oxigraph
public graph automatically (RDF_SYNC_ENABLED must be on, which is the default).

Usage:
    python manage.py seed_test_relationships          # create test edges
    python manage.py seed_test_relationships --clear   # remove all test edges
    python manage.py seed_test_relationships --per 2   # N objects per subject (default 1)
"""

from __future__ import annotations

import itertools

from apps.cidoc_data.models import (
    ArchitecturalStructure,
    Deity,
    Festival,
    Guthi,
    HeritageAssertion,
    IconographicObject,
    Location,
    Monument,
    Person,
    RitualEvent,
)
from django.contrib.contenttypes.models import ContentType
from django.core.management.base import BaseCommand

SEED_TAG = "test-seed"
SEED_NOTE = "TEST SEED relationship — generated by seed_test_relationships; remove before publication."

# (subject model, object model, relationship predicate suffix)
LINK_PLAN = [
    (ArchitecturalStructure, Location, "located_in"),
    (Monument, Location, "located_in"),
    (Festival, Location, "celebrated_at"),
    (Guthi, Location, "based_in"),
    (RitualEvent, Location, "performed_at"),
    (Person, Location, "associated_with"),
    (IconographicObject, Deity, "depicts"),
    (ArchitecturalStructure, Deity, "dedicated_to"),
    (Festival, Deity, "honors"),
]


class Command(BaseCommand):
    help = "Seed TEST relationship assertions between existing entities (reversible with --clear)."

    def add_arguments(self, parser):
        parser.add_argument("--clear", action="store_true", help="Delete all test-seed assertions.")
        parser.add_argument("--per", type=int, default=1, help="Objects to link per subject.")

    def handle(self, *args, **opts):
        if opts["clear"]:
            deleted, _ = HeritageAssertion.objects.filter(contributed_by=SEED_TAG).delete()
            self.stdout.write(self.style.SUCCESS(f"✓ Removed {deleted} test-seed assertion(s)."))
            self.stdout.write("Run `make rdf-rebuild` to drop the corresponding triples from Oxigraph.")
            return

        per = max(1, int(opts["per"]))
        created = skipped = 0

        for SubjModel, ObjModel, pred in LINK_PLAN:
            subj_ct = ContentType.objects.get_for_model(SubjModel)
            obj_ct = ContentType.objects.get_for_model(ObjModel)
            objects = list(ObjModel.objects.all()[:200])
            if not objects:
                continue
            cycle = itertools.cycle(objects)

            for subj in SubjModel.objects.all()[:500]:
                for _ in range(per):
                    obj = next(cycle)
                    if SubjModel is ObjModel and obj.pk == subj.pk:
                        obj = next(cycle)
                    _, was_created = HeritageAssertion.objects.get_or_create(
                        content_type=subj_ct,
                        object_id=subj.pk,
                        object_content_type=obj_ct,
                        object_object_id=obj.pk,
                        asserted_property=f"relationship.{pred}",
                        defaults={
                            "reconciliation_status": "accepted",
                            "contributed_by": SEED_TAG,
                            "attributed_to_agent": SEED_TAG,
                            "source_citation": (
                                "HeritageGraph test-seed corpus "
                                "(non-scholarly; remove before publication)."
                            ),
                            "assertion_content": SEED_NOTE,
                            "confidence": "likely",
                        },
                    )
                    created += int(was_created)
                    skipped += int(not was_created)

        self.stdout.write(
            self.style.SUCCESS(
                f"✓ Created {created} test relationship(s) ({skipped} already existed)."
            )
        )
        self.stdout.write(
            "Each accepted relationship.* assertion projects one triple via rdf_signals. "
            "If the graph still looks empty, run `make rdf-rebuild` to re-project, then reload "
            "the museum's Live KG. Remove later with: python manage.py seed_test_relationships --clear"
        )
