# Generated by Django 5.2.8 on 2026-06-01 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_rdf_sync_outbox'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rdfsyncoutbox',
            new_name='graph_rdf_s_process_9c6400_idx',
            old_name='graph_rdf_s_process_0a1b2c_idx',
        ),
    ]
