# Generated by Django 5.2.8 on 2026-06-03 09:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_rename_graph_rdf_s_process_0a1b2c_idx_graph_rdf_s_process_9c6400_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerInstitution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('country_code', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2', max_length=2)),
                ('ror_id', models.CharField(blank=True, help_text='ROR institution ID', max_length=64)),
                ('website', models.URLField(blank=True, max_length=500)),
                ('graph_partition_suffix', models.CharField(blank=True, help_text='Optional named-graph suffix for partner-specific assertions', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'graph_partner_institution',
                'ordering': ['name'],
            },
        ),
    ]
