# Generated by Django 5.2.8 on 2026-04-18 15:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("heritage_data", "0013_delete_reviewerrolerequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("pdf_digital", "PDF (digital-born)"),
                            ("pdf_scanned", "PDF (scanned)"),
                            ("image_print", "Image (printed page)"),
                            ("image_handwritten", "Image (handwritten)"),
                            ("image_inscription", "Image (stone/inscription)"),
                        ],
                        help_text="Type of document (affects engine selection)",
                        max_length=50,
                    ),
                ),
                (
                    "classification_confidence",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Confidence score of document type classification (0.0-1.0)",
                        max_digits=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending OCR"),
                            ("processing", "OCR in progress"),
                            ("completed", "OCR completed"),
                            ("failed", "OCR failed"),
                        ],
                        default="pending",
                        help_text="Current OCR processing status",
                        max_length=20,
                    ),
                ),
                (
                    "raw_text",
                    models.TextField(
                        blank=True, help_text="Complete extracted text from all pages"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("processing_started", models.DateTimeField(blank=True, null=True)),
                ("processing_finished", models.DateTimeField(blank=True, null=True)),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error details if processing failed"
                    ),
                ),
                (
                    "cultural_entity",
                    models.ForeignKey(
                        blank=True,
                        help_text="New workflow: associated CulturalEntity (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ocr_documents",
                        to="heritage_data.culturalentity",
                    ),
                ),
                (
                    "media",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocr_document",
                        to="heritage_data.media",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        help_text="Legacy: associated Submission (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ocr_documents",
                        to="heritage_data.submission",
                    ),
                ),
            ],
            options={
                "db_table": "document_processing_uploaded_document",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExtractedField",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        help_text="Target form field name (e.g., 'person_name', 'location')",
                        max_length=255,
                    ),
                ),
                (
                    "field_value",
                    models.TextField(help_text="Extracted value for this field"),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Overall confidence of this extraction (0.0-1.0)",
                        max_digits=3,
                    ),
                ),
                (
                    "source_entity_type",
                    models.CharField(
                        choices=[
                            ("PERSON", "Person"),
                            ("LOCATION", "Location"),
                            ("DATE", "Date"),
                            ("ARTIFACT", "Artifact"),
                            ("EVENT", "Event"),
                            ("TRADITION", "Tradition"),
                            ("ORGANIZATION", "Organization"),
                            ("OTHER", "Other"),
                        ],
                        help_text="NER entity type that produced this field",
                        max_length=50,
                    ),
                ),
                (
                    "vocabulary_match_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        help_text="Score from cross-checking value against Wikidata/AAT (0.0-1.0)",
                        max_digits=3,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        help_text="Document this field was extracted from",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extracted_fields",
                        to="document_processing.uploadeddocument",
                    ),
                ),
            ],
            options={
                "db_table": "document_processing_extracted_field",
                "ordering": ["document", "-confidence"],
            },
        ),
        migrations.CreateModel(
            name="DocumentPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "page_number",
                    models.PositiveIntegerField(help_text="Page number (1-indexed)"),
                ),
                (
                    "raw_text",
                    models.TextField(help_text="Raw OCR-extracted text for this page"),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Average confidence score across engines (0.0-1.0)",
                        max_digits=3,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        help_text="Parent document",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="document_processing.uploadeddocument",
                    ),
                ),
            ],
            options={
                "db_table": "document_processing_document_page",
                "ordering": ["document", "page_number"],
            },
        ),
        migrations.CreateModel(
            name="OCRResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "engine",
                    models.CharField(
                        choices=[
                            ("pdfplumber", "pdfplumber"),
                            ("tesseract", "Tesseract 5"),
                            ("easyocr", "EasyOCR"),
                            ("trocr", "TrOCR (Handwritten)"),
                            ("claude_vision", "Claude Vision (Rescue)"),
                        ],
                        help_text="Which OCR engine produced this result",
                        max_length=50,
                    ),
                ),
                (
                    "text",
                    models.TextField(help_text="Raw text extracted by this engine"),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Confidence score from this engine (0.0-1.0)",
                        max_digits=3,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Engine-specific metadata (e.g., script detected by EasyOCR, model used by TrOCR)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "page",
                    models.ForeignKey(
                        help_text="Page this result came from",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocr_results",
                        to="document_processing.documentpage",
                    ),
                ),
            ],
            options={
                "db_table": "document_processing_ocr_result",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["page", "engine"], name="document_pr_page_id_579d07_idx"
                    ),
                    models.Index(
                        fields=["engine"], name="document_pr_engine_c7422e_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="uploadeddocument",
            index=models.Index(
                fields=["status", "-created_at"], name="document_pr_status_794815_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uploadeddocument",
            index=models.Index(
                fields=["document_type"], name="document_pr_documen_544e3e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="extractedfield",
            index=models.Index(
                fields=["document", "field_name"], name="document_pr_documen_8565cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="extractedfield",
            index=models.Index(
                fields=["source_entity_type"], name="document_pr_source__e5d2ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentpage",
            index=models.Index(
                fields=["document", "page_number"],
                name="document_pr_documen_237135_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentpage",
            unique_together={("document", "page_number")},
        ),
    ]
