# Generated by Django 5.2.8 on 2026-04-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_processing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadeddocument",
            name="claude_vision_invocations",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Count of Claude Vision (or other vision-rescue) invocations for cost control/audit",
            ),
        ),
        migrations.AddField(
            model_name="uploadeddocument",
            name="user_safe_error",
            field=models.TextField(
                blank=True,
                help_text="User-safe error message (no stack traces, minimal PII)",
            ),
        ),
    ]
