# Generated by Django 5.2.8 on 2026-05-16 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("document_processing", "0003_add_metadata_to_uploaded_document"),
        ("document_processing", "0005_chunked_tabular_models"),
    ]

    operations = []
