# Generated by Django 5.2.8 on 2026-05-17 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processing', '0006_merge_20260516_2152'),
        ('heritage_data', '0023_project_ocr_deferred'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project workspace that owns this OCR run (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocr_documents', to='heritage_data.project'),
        ),
    ]
