'use client';

import { useTranslations } from 'next-intl';
import {
  IconDatabase,
  IconGraph,
  IconMapPin,
  IconCube,
  IconLoader2,
  IconInfoCircle,
} from '@tabler/icons-react';

import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { glassCard } from '@/lib/design';
import { cn } from '@/lib/utils';

export type MuseumViewMode = '2d' | 'xr' | 'map';
export type MuseumDataSource = 'demo' | 'live';

export interface MuseumCorpusProvenance {
  generatedBy?: string;
  retrieved?: string;
  imageSource?: string;
  note?: string;
}

interface MuseumToolbarProps {
  viewMode: MuseumViewMode;
  onViewModeChange: (mode: MuseumViewMode) => void;
  dataSource: MuseumDataSource;
  liveLoading: boolean;
  onToggleDataSource: () => void;
  nodeCount: number;
  linkCount: number;
  showStats: boolean;
  provenanceText?: string | null;
  provenance?: MuseumCorpusProvenance | null;
  liveApiBase?: string | null;
}

export function MuseumToolbar({
  viewMode,
  onViewModeChange,
  dataSource,
  liveLoading,
  onToggleDataSource,
  nodeCount,
  linkCount,
  showStats,
  provenanceText,
  provenance,
  liveApiBase,
}: MuseumToolbarProps) {
  const t = useTranslations('heritageMuseum');

  return (
    <div
      className={cn(
        glassCard,
        'flex-shrink-0 flex flex-wrap items-center gap-2 px-3 py-2 border-b border-border rounded-none shadow-none',
      )}
      role="toolbar"
      aria-label={t('filters.regionLabel')}
    >
      <p className="hidden sm:block text-xs text-muted-foreground max-w-xs leading-snug mr-1">
        {t('subtitle')}
      </p>

      {provenanceText ? (
        <p className="hidden lg:block text-[11px] text-muted-foreground/90 max-w-[32rem] truncate">
          {provenanceText}
        </p>
      ) : null}

      <div className="flex-1 min-w-[1rem]" />

      <Popover>
        <PopoverTrigger asChild>
          <Button
            type="button"
            size="sm"
            variant="ghost"
            className="h-8 px-2.5 text-xs gap-1.5"
            aria-label="Methods and provenance"
            title="Methods and provenance"
          >
            <IconInfoCircle className="w-4 h-4" aria-hidden />
            <span className="hidden sm:inline">Methods</span>
          </Button>
        </PopoverTrigger>
        <PopoverContent align="end" sideOffset={8} className="w-[min(34rem,92vw)] p-0">
          <div className="p-4 space-y-3">
            <div className="space-y-1">
              <p className="text-sm font-semibold text-foreground">Methods & provenance</p>
              <p className="text-xs text-muted-foreground">
                This view supports a curated demo corpus (for reproducible demos) and an authenticated live graph mode.
              </p>
            </div>

            <div className="rounded-lg border border-border/70 bg-background/40 p-3">
              <p className="text-xs font-semibold text-foreground mb-1">Data mode</p>
              <p className="text-xs text-muted-foreground">
                <span className="font-mono">{dataSource.toUpperCase()}</span>
                {dataSource === 'live' && liveApiBase ? (
                  <>
                    {' · '}
                    Live API: <span className="font-mono">{liveApiBase}</span>
                  </>
                ) : null}
              </p>
            </div>

            <div className="rounded-lg border border-border/70 bg-background/40 p-3 space-y-2">
              <p className="text-xs font-semibold text-foreground">Demo corpus provenance</p>
              {provenance?.retrieved ? (
                <div className="text-xs text-muted-foreground space-y-1">
                  <p>
                    Frozen: <span className="font-mono">{provenance.retrieved}</span>
                  </p>
                  {provenance.generatedBy ? (
                    <p>
                      Generated by: <span className="font-mono">{provenance.generatedBy}</span>
                    </p>
                  ) : null}
                  {provenance.imageSource ? <p>Image metadata source: {provenance.imageSource}</p> : null}
                  {provenance.note ? <p className="opacity-90">{provenance.note}</p> : null}
                </div>
              ) : (
                <p className="text-xs text-muted-foreground">
                  No demo provenance metadata found in the corpus. (Expected a top-level <span className="font-mono">_provenance</span> block.)
                </p>
              )}
              <p className="text-[11px] text-muted-foreground/90">
                Images include per-file licensing/attribution when available (CC requirements).
              </p>
            </div>

            <div className="rounded-lg border border-border/70 bg-background/40 p-3 space-y-1">
              <p className="text-xs font-semibold text-foreground">Live graph mapping</p>
              <p className="text-xs text-muted-foreground">
                Live mode fetches an instance graph from the backend and maps backend categories to visualization node types
                (see <span className="font-mono">INSTANCE_CAT_MAP</span>). Field extraction is defensive (string/array checks)
                and relations are attached so “Connections” work consistently across demo and live data.
              </p>
            </div>
          </div>
        </PopoverContent>
      </Popover>

      {showStats && (
        <span className="hidden md:inline text-xs text-muted-foreground tabular-nums">
          {t('stats', { nodes: nodeCount, links: linkCount })}
        </span>
      )}

      <Button
        type="button"
        size="sm"
        variant={dataSource === 'live' ? 'default' : 'outline'}
        disabled={liveLoading}
        onClick={onToggleDataSource}
        className="hidden sm:inline-flex gap-1.5 text-xs h-8"
      >
        {liveLoading ? (
          <IconLoader2 className="w-3.5 h-3.5 animate-spin" aria-hidden />
        ) : (
          <IconDatabase className="w-3.5 h-3.5" aria-hidden />
        )}
        {liveLoading
          ? t('dataSource.loading')
          : dataSource === 'live'
            ? t('dataSource.live')
            : t('dataSource.demo')}
      </Button>

      <Tabs
        value={viewMode}
        onValueChange={(v) => onViewModeChange(v as MuseumViewMode)}
        className="shrink-0"
      >
        <TabsList className="h-8">
          <TabsTrigger value="2d" className="text-xs gap-1 px-2.5">
            <IconGraph className="w-3.5 h-3.5" aria-hidden />
            {t('views.graph')}
          </TabsTrigger>
          <TabsTrigger value="map" className="text-xs gap-1 px-2.5">
            <IconMapPin className="w-3.5 h-3.5" aria-hidden />
            {t('views.map')}
          </TabsTrigger>
          <TabsTrigger value="xr" className="text-xs gap-1 px-2.5">
            <IconCube className="w-3.5 h-3.5" aria-hidden />
            {t('views.xr')}
          </TabsTrigger>
        </TabsList>
      </Tabs>

      <div className="hidden lg:flex items-center gap-1 flex-wrap">
        {(['cidoc', 'hg', 'prov', 'jsonld'] as const).map((key) => (
          <Badge key={key} variant="secondary" className="text-[10px] font-mono px-2 py-0">
            {t(`ontologyBadges.${key}`)}
          </Badge>
        ))}
      </div>
    </div>
  );
}
