#!/usr/bin/env python3
"""Emit the OWL/Turtle rendering of the ontology from ``ontology/HeritageGraph.yaml``.

Produces ``ontology/HeritageGraph.ttl``, the TBox loaded into Oxigraph by
``manage.py rdf_load_tbox`` and parsed by ``apps.graph.kg_engine.quality`` for
CIDOC-CRM coverage metrics. Keeping this generated in-repo means the TBox always
matches the deployed schema instead of drifting from an upstream snapshot.

The LinkML OWL generator mints fresh blank-node identifiers on every run and
rdflib's Turtle serializer does not order them stably, so two runs over an
unchanged schema still differ byte-for-byte. Comparisons here are therefore done
on the parsed RDF graph (isomorphism, which canonicalises blank nodes) rather
than on text: ``--check`` only fails on a real semantic difference, and a
regeneration that changes nothing leaves the committed file untouched.

Usage::

    python3 tools/emit_owl_ttl.py            # regenerate if semantically stale
    python3 tools/emit_owl_ttl.py --check    # CI: fail if semantically stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCHEMA = ROOT / "ontology" / "HeritageGraph.yaml"
OUT = ROOT / "ontology" / "HeritageGraph.ttl"

HEADER = (
    "# GENERATED from HeritageGraph.yaml by tools/emit_owl_ttl.py.\n"
    "# DO NOT EDIT THIS FILE - edit the YAML and regenerate (`make owl-ttl`).\n"
)


def render(schema_path: Path) -> str:
    from linkml.generators.owlgen import OwlSchemaGenerator

    body = OwlSchemaGenerator(str(schema_path), mergeimports=False).serialize()
    return HEADER + body


def same_graph(a: str, b: str) -> bool:
    """True when both Turtle documents describe the same RDF graph."""
    from rdflib import Graph
    from rdflib.compare import to_isomorphic

    ga, gb = Graph(), Graph()
    try:
        ga.parse(data=a, format="turtle")
        gb.parse(data=b, format="turtle")
    except Exception:
        return False
    return to_isomorphic(ga) == to_isomorphic(gb)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if the output is stale")
    args = ap.parse_args()

    if not SCHEMA.is_file():
        print(f"error: schema not found: {SCHEMA}", file=sys.stderr)
        return 1

    rendered = render(SCHEMA)
    existing = OUT.read_text() if OUT.is_file() else None

    if args.check:
        if existing is None:
            print(f"error: {OUT} missing; run `make owl-ttl`", file=sys.stderr)
            return 1
        if not same_graph(existing, rendered):
            print(f"error: {OUT} is out of date; run `make owl-ttl`", file=sys.stderr)
            return 1
        print(f"ok: {OUT.relative_to(ROOT)} up to date")
        return 0

    if existing is not None and same_graph(existing, rendered):
        print(f"✓ {OUT.relative_to(ROOT)} already up to date")
        return 0

    OUT.write_text(rendered)
    print(f"✓ {OUT.relative_to(ROOT)} ({len(rendered.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
